/*******************************************************************************
 * @author Reika Kalseki
 *
 * Copyright 2017
 *
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
package Reika.ChromatiCraft.World.Dimension.Structure.Locks;


import net.minecraft.block.Block;
import net.minecraft.init.Blocks;

import Reika.ChromatiCraft.Base.StructureLootRoom;
import Reika.ChromatiCraft.Block.Worldgen.BlockStructureShield.BlockType;
import Reika.ChromatiCraft.Registry.ChromaBlocks;
import Reika.ChromatiCraft.World.Dimension.Structure.LocksGenerator;
import Reika.DragonAPI.Instantiable.Worldgen.ChunkSplicedGenerationCache;

public class LocksLoot extends StructureLootRoom<LocksGenerator> {

	private final boolean shouldFlip;

	public LocksLoot(LocksGenerator s, boolean flip) {
		super(s);
		shouldFlip = flip;
	}

	@Override
	public void generate(ChunkSplicedGenerationCache world, int x, int y, int z) {

		this.generateBlocks(world, x, y, z);
		this.generateAir(world, x, y, z);
	}

	private void generateBlocks(ChunkSplicedGenerationCache world, int x, int y, int z) {

		Block b = ChromaBlocks.STRUCTSHIELD.getBlockInstance();
		int ms = BlockType.STONE.metadata;
		int ml = BlockType.LIGHT.metadata;
		int mg = BlockType.GLASS.metadata;
		int mc = BlockType.CRACKS.metadata;

		int f = shouldFlip ? -1 : 1;

		this.placeCore(x+f*4, y+2, z-f*5);

		for (int i = -1; i <= 1; i++)
			for (int k = -1; k <= 1; k++)
				parent.addBreakable(x+f*4+i, y, z-f*5+k);

		world.setBlock(x+f*0, y+0, z-f*2, b, ms);
		world.setBlock(x+f*0, y+0, z-f*3, b, ms);
		world.setBlock(x+f*0, y+0, z-f*4, b, ms);
		world.setBlock(x+f*0, y+0, z-f*5, b, ms);
		world.setBlock(x+f*0, y+0, z-f*6, b, ms);
		world.setBlock(x+f*0, y+0, z-f*7, b, ms);
		world.setBlock(x+f*0, y+0, z-f*8, b, ms);
		world.setBlock(x+f*0, y+1, z-f*2, b, ms);
		world.setBlock(x+f*0, y+1, z-f*3, b, ms);
		world.setBlock(x+f*0, y+1, z-f*4, b, ms);
		world.setBlock(x+f*0, y+1, z-f*5, b, ms);
		world.setBlock(x+f*0, y+1, z-f*6, b, ms);
		world.setBlock(x+f*0, y+1, z-f*7, b, ms);
		world.setBlock(x+f*0, y+1, z-f*8, b, ms);
		world.setBlock(x+f*0, y+2, z-f*2, b, ms);
		world.setBlock(x+f*0, y+2, z-f*3, b, ms);
		world.setBlock(x+f*0, y+2, z-f*4, b, ms);
		world.setBlock(x+f*0, y+2, z-f*5, b, ms);
		world.setBlock(x+f*0, y+2, z-f*6, b, ms);
		world.setBlock(x+f*0, y+2, z-f*7, b, ms);
		world.setBlock(x+f*0, y+2, z-f*8, b, ms);
		world.setBlock(x+f*0, y+3, z-f*2, b, ms);
		world.setBlock(x+f*0, y+3, z-f*3, b, ms);
		world.setBlock(x+f*0, y+3, z-f*4, b, ms);
		world.setBlock(x+f*0, y+3, z-f*5, b, ms);
		world.setBlock(x+f*0, y+3, z-f*6, b, ms);
		world.setBlock(x+f*0, y+3, z-f*7, b, ms);
		world.setBlock(x+f*0, y+3, z-f*8, b, ms);
		world.setBlock(x+f*0, y+4, z-f*2, b, ms);
		world.setBlock(x+f*0, y+4, z-f*3, b, ms);
		world.setBlock(x+f*0, y+4, z-f*4, b, ms);
		world.setBlock(x+f*0, y+4, z-f*5, b, ms);
		world.setBlock(x+f*0, y+4, z-f*6, b, ms);
		world.setBlock(x+f*0, y+4, z-f*7, b, ms);
		world.setBlock(x+f*0, y+4, z-f*8, b, ms);
		world.setBlock(x+f*0, y+5, z-f*3, b, ms);
		world.setBlock(x+f*0, y+5, z-f*4, b, ms);
		world.setBlock(x+f*0, y+5, z-f*5, b, ms);
		world.setBlock(x+f*0, y+5, z-f*6, b, ms);
		world.setBlock(x+f*0, y+5, z-f*7, b, ms);
		world.setBlock(x+f*1, y+0, z-f*1, b, ms);
		world.setBlock(x+f*1, y+0, z-f*2, b, ms);
		world.setBlock(x+f*1, y+0, z-f*3, b, ms);
		world.setBlock(x+f*1, y+0, z-f*4, b, ms);
		world.setBlock(x+f*1, y+0, z-f*5, b, ms);
		world.setBlock(x+f*1, y+0, z-f*6, b, ms);
		world.setBlock(x+f*1, y+0, z-f*7, b, ms);
		world.setBlock(x+f*1, y+0, z-f*8, b, ms);
		world.setBlock(x+f*1, y+0, z-f*9, b, ms);
		world.setBlock(x+f*1, y+1, z-f*1, b, ms);
		world.setBlock(x+f*1, y+1, z-f*9, b, ms);
		world.setBlock(x+f*1, y+2, z-f*1, b, ms);
		world.setBlock(x+f*1, y+2, z-f*9, b, ms);
		world.setBlock(x+f*1, y+3, z-f*1, b, ms);
		world.setBlock(x+f*1, y+3, z-f*9, b, ms);
		world.setBlock(x+f*1, y+4, z-f*1, b, ms);
		world.setBlock(x+f*1, y+4, z-f*4, b, ms);
		world.setBlock(x+f*1, y+4, z-f*5, b, ml);
		world.setBlock(x+f*1, y+4, z-f*6, b, ms);
		world.setBlock(x+f*1, y+4, z-f*9, b, ms);
		world.setBlock(x+f*1, y+5, z-f*2, b, ms);
		world.setBlock(x+f*1, y+5, z-f*8, b, ms);
		world.setBlock(x+f*1, y+6, z-f*3, b, ms);
		world.setBlock(x+f*1, y+6, z-f*4, b, ms);
		world.setBlock(x+f*1, y+6, z-f*5, b, ms);
		world.setBlock(x+f*1, y+6, z-f*6, b, ms);
		world.setBlock(x+f*1, y+6, z-f*7, b, ms);
		world.setBlock(x+f*2, y+0, z-f*0, b, ms);
		world.setBlock(x+f*2, y+0, z-f*1, b, ms);
		world.setBlock(x+f*2, y+0, z-f*2, b, ms);
		world.setBlock(x+f*2, y+0, z-f*3, b, ms);
		world.setBlock(x+f*2, y+0, z-f*4, b, ms);
		world.setBlock(x+f*2, y+0, z-f*5, b, ms);
		world.setBlock(x+f*2, y+0, z-f*6, b, ms);
		world.setBlock(x+f*2, y+0, z-f*7, b, ms);
		world.setBlock(x+f*2, y+0, z-f*8, b, ms);
		world.setBlock(x+f*2, y+0, z-f*9, b, ms);
		world.setBlock(x+f*2, y+0, z-f*10, b, ms);
		world.setBlock(x+f*2, y+1, z-f*0, b, ms);
		world.setBlock(x+f*2, y+1, z-f*4, b, ms);
		world.setBlock(x+f*2, y+1, z-f*5, b, ms);
		world.setBlock(x+f*2, y+1, z-f*6, b, ms);
		world.setBlock(x+f*2, y+1, z-f*10, b, ms);
		world.setBlock(x+f*2, y+2, z-f*0, b, ms);
		world.setBlock(x+f*2, y+2, z-f*4, b, ms);
		world.setBlock(x+f*2, y+2, z-f*5, b, mg);
		world.setBlock(x+f*2, y+2, z-f*6, b, ms);
		world.setBlock(x+f*2, y+2, z-f*10, b, ms);
		world.setBlock(x+f*2, y+3, z-f*0, b, ms);
		world.setBlock(x+f*2, y+3, z-f*4, b, ms);
		world.setBlock(x+f*2, y+3, z-f*5, b, ms);
		world.setBlock(x+f*2, y+3, z-f*6, b, ms);
		world.setBlock(x+f*2, y+3, z-f*10, b, ms);
		world.setBlock(x+f*2, y+4, z-f*0, b, ms);
		world.setBlock(x+f*2, y+4, z-f*4, b, ms);
		world.setBlock(x+f*2, y+4, z-f*5, b, ms);
		world.setBlock(x+f*2, y+4, z-f*6, b, ms);
		world.setBlock(x+f*2, y+4, z-f*10, b, ms);
		world.setBlock(x+f*2, y+5, z-f*1, b, ms);
		world.setBlock(x+f*2, y+5, z-f*2, b, ms);
		world.setBlock(x+f*2, y+5, z-f*8, b, ms);
		world.setBlock(x+f*2, y+5, z-f*9, b, ms);
		world.setBlock(x+f*2, y+6, z-f*3, b, ms);
		world.setBlock(x+f*2, y+6, z-f*4, b, ms);
		world.setBlock(x+f*2, y+6, z-f*5, b, ms);
		world.setBlock(x+f*2, y+6, z-f*6, b, ms);
		world.setBlock(x+f*2, y+6, z-f*7, b, ms);
		world.setBlock(x+f*3, y+0, z-f*0, b, ms);
		world.setBlock(x+f*3, y+0, z-f*1, b, ms);
		world.setBlock(x+f*3, y+0, z-f*2, b, ms);
		world.setBlock(x+f*3, y+0, z-f*3, b, ms);
		world.setBlock(x+f*3, y+0, z-f*4, b, ms);
		world.setBlock(x+f*3, y+0, z-f*5, b, ms);
		world.setBlock(x+f*3, y+0, z-f*6, b, ms);
		world.setBlock(x+f*3, y+0, z-f*7, b, ms);
		world.setBlock(x+f*3, y+0, z-f*8, b, ms);
		world.setBlock(x+f*3, y+0, z-f*9, b, ms);
		world.setBlock(x+f*3, y+0, z-f*10, b, ms);
		world.setBlock(x+f*3, y+1, z-f*0, b, ms);
		world.setBlock(x+f*3, y+1, z-f*3, b, ms);
		world.setBlock(x+f*3, y+1, z-f*7, b, ms);
		world.setBlock(x+f*3, y+2, z-f*0, b, ms);
		world.setBlock(x+f*3, y+2, z-f*3, b, ms);
		world.setBlock(x+f*3, y+2, z-f*7, b, ms);
		world.setBlock(x+f*3, y+3, z-f*0, b, ms);
		world.setBlock(x+f*3, y+3, z-f*3, b, ms);
		world.setBlock(x+f*3, y+3, z-f*7, b, ms);
		world.setBlock(x+f*3, y+4, z-f*0, b, ms);
		world.setBlock(x+f*3, y+4, z-f*3, b, ms);
		world.setBlock(x+f*3, y+4, z-f*7, b, ms);
		world.setBlock(x+f*3, y+4, z-f*10, b, ms);
		world.setBlock(x+f*3, y+5, z-f*1, b, ms);
		world.setBlock(x+f*3, y+5, z-f*2, b, ms);
		world.setBlock(x+f*3, y+5, z-f*3, b, ms);
		world.setBlock(x+f*3, y+5, z-f*7, b, ms);
		world.setBlock(x+f*3, y+5, z-f*8, b, ms);
		world.setBlock(x+f*3, y+5, z-f*9, b, ms);
		world.setBlock(x+f*3, y+6, z-f*3, b, ms);
		world.setBlock(x+f*3, y+6, z-f*4, b, ms);
		world.setBlock(x+f*3, y+6, z-f*5, b, ms);
		world.setBlock(x+f*3, y+6, z-f*6, b, ms);
		world.setBlock(x+f*3, y+6, z-f*7, b, ms);
		world.setBlock(x+f*4, y+0, z-f*0, b, ms);
		world.setBlock(x+f*4, y+0, z-f*1, b, ms);
		world.setBlock(x+f*4, y+0, z-f*2, b, ms);
		world.setBlock(x+f*4, y+0, z-f*3, b, ms);
		world.setBlock(x+f*4, y+0, z-f*4, b, ms);
		world.setBlock(x+f*4, y+0, z-f*5, b, ms);
		world.setBlock(x+f*4, y+0, z-f*6, b, ms);
		world.setBlock(x+f*4, y+0, z-f*7, b, ms);
		world.setBlock(x+f*4, y+0, z-f*8, b, ms);
		world.setBlock(x+f*4, y+0, z-f*9, b, ms);
		world.setBlock(x+f*4, y+0, z-f*10, b, ms);
		world.setBlock(x+f*4, y+1, z-f*0, b, ms);
		world.setBlock(x+f*4, y+1, z-f*3, b, mc);
		world.setBlock(x+f*4, y+1, z-f*7, b, ms);
		world.setBlock(x+f*4, y+2, z-f*0, b, ml);
		world.setBlock(x+f*4, y+2, z-f*3, b, mc);
		world.setBlock(x+f*4, y+2, z-f*7, b, ml);
		world.setBlock(x+f*4, y+3, z-f*0, b, ms);
		world.setBlock(x+f*4, y+3, z-f*3, b, mc);
		world.setBlock(x+f*4, y+3, z-f*7, b, ms);
		world.setBlock(x+f*4, y+4, z-f*0, b, ms);
		world.setBlock(x+f*4, y+4, z-f*1, b, ms);
		world.setBlock(x+f*4, y+4, z-f*2, b, ms);
		world.setBlock(x+f*4, y+4, z-f*3, b, ms);
		world.setBlock(x+f*4, y+4, z-f*7, b, ms);
		world.setBlock(x+f*4, y+4, z-f*10, b, ms);
		world.setBlock(x+f*4, y+5, z-f*1, b, ms);
		world.setBlock(x+f*4, y+5, z-f*2, b, ms);
		world.setBlock(x+f*4, y+5, z-f*3, b, ms);
		world.setBlock(x+f*4, y+5, z-f*7, b, ms);
		world.setBlock(x+f*4, y+5, z-f*8, b, ms);
		world.setBlock(x+f*4, y+5, z-f*9, b, ms);
		world.setBlock(x+f*4, y+6, z-f*3, b, ms);
		world.setBlock(x+f*4, y+6, z-f*4, b, ms);
		world.setBlock(x+f*4, y+6, z-f*5, b, ms);
		world.setBlock(x+f*4, y+6, z-f*6, b, ms);
		world.setBlock(x+f*4, y+6, z-f*7, b, ms);
		world.setBlock(x+f*5, y+0, z-f*0, b, ms);
		world.setBlock(x+f*5, y+0, z-f*1, b, ms);
		world.setBlock(x+f*5, y+0, z-f*2, b, ms);
		world.setBlock(x+f*5, y+0, z-f*3, b, ms);
		world.setBlock(x+f*5, y+0, z-f*4, b, ms);
		world.setBlock(x+f*5, y+0, z-f*5, b, ms);
		world.setBlock(x+f*5, y+0, z-f*6, b, ms);
		world.setBlock(x+f*5, y+0, z-f*7, b, ms);
		world.setBlock(x+f*5, y+0, z-f*8, b, ms);
		world.setBlock(x+f*5, y+0, z-f*9, b, ms);
		world.setBlock(x+f*5, y+0, z-f*10, b, ms);
		world.setBlock(x+f*5, y+1, z-f*0, b, ms);
		world.setBlock(x+f*5, y+1, z-f*3, b, ms);
		world.setBlock(x+f*5, y+1, z-f*7, b, ms);
		world.setBlock(x+f*5, y+2, z-f*0, b, ms);
		world.setBlock(x+f*5, y+2, z-f*3, b, ms);
		world.setBlock(x+f*5, y+2, z-f*7, b, ms);
		world.setBlock(x+f*5, y+3, z-f*0, b, ms);
		world.setBlock(x+f*5, y+3, z-f*3, b, ms);
		world.setBlock(x+f*5, y+3, z-f*7, b, ms);
		world.setBlock(x+f*5, y+4, z-f*0, b, ms);
		world.setBlock(x+f*5, y+4, z-f*3, b, ms);
		world.setBlock(x+f*5, y+4, z-f*7, b, ms);
		world.setBlock(x+f*5, y+4, z-f*10, b, ms);
		world.setBlock(x+f*5, y+5, z-f*1, b, ms);
		world.setBlock(x+f*5, y+5, z-f*2, b, ms);
		world.setBlock(x+f*5, y+5, z-f*3, b, ms);
		world.setBlock(x+f*5, y+5, z-f*7, b, ms);
		world.setBlock(x+f*5, y+5, z-f*8, b, ms);
		world.setBlock(x+f*5, y+5, z-f*9, b, ms);
		world.setBlock(x+f*5, y+6, z-f*3, b, ms);
		world.setBlock(x+f*5, y+6, z-f*4, b, ms);
		world.setBlock(x+f*5, y+6, z-f*5, b, ms);
		world.setBlock(x+f*5, y+6, z-f*6, b, ms);
		world.setBlock(x+f*5, y+6, z-f*7, b, ms);
		world.setBlock(x+f*6, y+0, z-f*0, b, ms);
		world.setBlock(x+f*6, y+0, z-f*1, b, ms);
		world.setBlock(x+f*6, y+0, z-f*2, b, ms);
		world.setBlock(x+f*6, y+0, z-f*3, b, ms);
		world.setBlock(x+f*6, y+0, z-f*4, b, ms);
		world.setBlock(x+f*6, y+0, z-f*5, b, ms);
		world.setBlock(x+f*6, y+0, z-f*6, b, ms);
		world.setBlock(x+f*6, y+0, z-f*7, b, ms);
		world.setBlock(x+f*6, y+0, z-f*8, b, ms);
		world.setBlock(x+f*6, y+0, z-f*9, b, ms);
		world.setBlock(x+f*6, y+0, z-f*10, b, ms);
		world.setBlock(x+f*6, y+1, z-f*0, b, ms);
		world.setBlock(x+f*6, y+1, z-f*4, b, ms);
		world.setBlock(x+f*6, y+1, z-f*5, b, ms);
		world.setBlock(x+f*6, y+1, z-f*6, b, ms);
		world.setBlock(x+f*6, y+1, z-f*10, b, ms);
		world.setBlock(x+f*6, y+2, z-f*0, b, ms);
		world.setBlock(x+f*6, y+2, z-f*4, b, ms);
		world.setBlock(x+f*6, y+2, z-f*5, b, mg);
		world.setBlock(x+f*6, y+2, z-f*6, b, ms);
		world.setBlock(x+f*6, y+2, z-f*10, b, ms);
		world.setBlock(x+f*6, y+3, z-f*0, b, ms);
		world.setBlock(x+f*6, y+3, z-f*4, b, ms);
		world.setBlock(x+f*6, y+3, z-f*5, b, ms);
		world.setBlock(x+f*6, y+3, z-f*6, b, ms);
		world.setBlock(x+f*6, y+3, z-f*10, b, ms);
		world.setBlock(x+f*6, y+4, z-f*0, b, ms);
		world.setBlock(x+f*6, y+4, z-f*4, b, ms);
		world.setBlock(x+f*6, y+4, z-f*5, b, ms);
		world.setBlock(x+f*6, y+4, z-f*6, b, ms);
		world.setBlock(x+f*6, y+4, z-f*10, b, ms);
		world.setBlock(x+f*6, y+5, z-f*1, b, ms);
		world.setBlock(x+f*6, y+5, z-f*2, b, ms);
		world.setBlock(x+f*6, y+5, z-f*8, b, ms);
		world.setBlock(x+f*6, y+5, z-f*9, b, ms);
		world.setBlock(x+f*6, y+6, z-f*3, b, ms);
		world.setBlock(x+f*6, y+6, z-f*4, b, ms);
		world.setBlock(x+f*6, y+6, z-f*5, b, ms);
		world.setBlock(x+f*6, y+6, z-f*6, b, ms);
		world.setBlock(x+f*6, y+6, z-f*7, b, ms);
		world.setBlock(x+f*7, y+0, z-f*1, b, ms);
		world.setBlock(x+f*7, y+0, z-f*2, b, ms);
		world.setBlock(x+f*7, y+0, z-f*3, b, ms);
		world.setBlock(x+f*7, y+0, z-f*4, b, ms);
		world.setBlock(x+f*7, y+0, z-f*5, b, ms);
		world.setBlock(x+f*7, y+0, z-f*6, b, ms);
		world.setBlock(x+f*7, y+0, z-f*7, b, ms);
		world.setBlock(x+f*7, y+0, z-f*8, b, ms);
		world.setBlock(x+f*7, y+0, z-f*9, b, ms);
		world.setBlock(x+f*7, y+1, z-f*1, b, ms);
		world.setBlock(x+f*7, y+1, z-f*9, b, ms);
		world.setBlock(x+f*7, y+2, z-f*1, b, ms);
		world.setBlock(x+f*7, y+2, z-f*9, b, ms);
		world.setBlock(x+f*7, y+3, z-f*1, b, ms);
		world.setBlock(x+f*7, y+3, z-f*9, b, ms);
		world.setBlock(x+f*7, y+4, z-f*1, b, ms);
		world.setBlock(x+f*7, y+4, z-f*4, b, ms);
		world.setBlock(x+f*7, y+4, z-f*5, b, ml);
		world.setBlock(x+f*7, y+4, z-f*6, b, ms);
		world.setBlock(x+f*7, y+4, z-f*9, b, ms);
		world.setBlock(x+f*7, y+5, z-f*2, b, ms);
		world.setBlock(x+f*7, y+5, z-f*8, b, ms);
		world.setBlock(x+f*7, y+6, z-f*3, b, ms);
		world.setBlock(x+f*7, y+6, z-f*4, b, ms);
		world.setBlock(x+f*7, y+6, z-f*5, b, ms);
		world.setBlock(x+f*7, y+6, z-f*6, b, ms);
		world.setBlock(x+f*7, y+6, z-f*7, b, ms);
		world.setBlock(x+f*8, y+0, z-f*2, b, ms);
		world.setBlock(x+f*8, y+0, z-f*3, b, ms);
		world.setBlock(x+f*8, y+0, z-f*4, b, ms);
		world.setBlock(x+f*8, y+0, z-f*5, b, ms);
		world.setBlock(x+f*8, y+0, z-f*6, b, ms);
		world.setBlock(x+f*8, y+0, z-f*7, b, ms);
		world.setBlock(x+f*8, y+0, z-f*8, b, ms);
		world.setBlock(x+f*8, y+1, z-f*2, b, ms);
		world.setBlock(x+f*8, y+1, z-f*3, b, ms);
		world.setBlock(x+f*8, y+1, z-f*4, b, ms);
		world.setBlock(x+f*8, y+1, z-f*5, b, ms);
		world.setBlock(x+f*8, y+1, z-f*6, b, ms);
		world.setBlock(x+f*8, y+1, z-f*7, b, ms);
		world.setBlock(x+f*8, y+1, z-f*8, b, ms);
		world.setBlock(x+f*8, y+2, z-f*2, b, ms);
		world.setBlock(x+f*8, y+2, z-f*3, b, ms);
		world.setBlock(x+f*8, y+2, z-f*4, b, ms);
		world.setBlock(x+f*8, y+2, z-f*5, b, ms);
		world.setBlock(x+f*8, y+2, z-f*6, b, ms);
		world.setBlock(x+f*8, y+2, z-f*7, b, ms);
		world.setBlock(x+f*8, y+2, z-f*8, b, ms);
		world.setBlock(x+f*8, y+3, z-f*2, b, ms);
		world.setBlock(x+f*8, y+3, z-f*3, b, ms);
		world.setBlock(x+f*8, y+3, z-f*4, b, ms);
		world.setBlock(x+f*8, y+3, z-f*5, b, ms);
		world.setBlock(x+f*8, y+3, z-f*6, b, ms);
		world.setBlock(x+f*8, y+3, z-f*7, b, ms);
		world.setBlock(x+f*8, y+3, z-f*8, b, ms);
		world.setBlock(x+f*8, y+4, z-f*2, b, ms);
		world.setBlock(x+f*8, y+4, z-f*3, b, ms);
		world.setBlock(x+f*8, y+4, z-f*4, b, ms);
		world.setBlock(x+f*8, y+4, z-f*5, b, ms);
		world.setBlock(x+f*8, y+4, z-f*6, b, ms);
		world.setBlock(x+f*8, y+4, z-f*7, b, ms);
		world.setBlock(x+f*8, y+4, z-f*8, b, ms);
		world.setBlock(x+f*8, y+5, z-f*3, b, ms);
		world.setBlock(x+f*8, y+5, z-f*4, b, ms);
		world.setBlock(x+f*8, y+5, z-f*5, b, ms);
		world.setBlock(x+f*8, y+5, z-f*6, b, ms);
		world.setBlock(x+f*8, y+5, z-f*7, b, ms);
	}

	private void generateAir(ChunkSplicedGenerationCache world, int x, int y, int z) {

		int f = shouldFlip ? -1 : 1;

		world.setBlock(x+f*1, y+1, z-f*2, Blocks.air);
		world.setBlock(x+f*1, y+1, z-f*3, Blocks.air);
		world.setBlock(x+f*1, y+1, z-f*4, Blocks.air);
		world.setBlock(x+f*1, y+1, z-f*5, Blocks.air);
		world.setBlock(x+f*1, y+1, z-f*6, Blocks.air);
		world.setBlock(x+f*1, y+1, z-f*7, Blocks.air);
		world.setBlock(x+f*1, y+1, z-f*8, Blocks.air);
		world.setBlock(x+f*1, y+2, z-f*2, Blocks.air);
		world.setBlock(x+f*1, y+2, z-f*3, Blocks.air);
		world.setBlock(x+f*1, y+2, z-f*4, Blocks.air);
		world.setBlock(x+f*1, y+2, z-f*5, Blocks.air);
		world.setBlock(x+f*1, y+2, z-f*6, Blocks.air);
		world.setBlock(x+f*1, y+2, z-f*7, Blocks.air);
		world.setBlock(x+f*1, y+2, z-f*8, Blocks.air);
		world.setBlock(x+f*1, y+3, z-f*2, Blocks.air);
		world.setBlock(x+f*1, y+3, z-f*3, Blocks.air);
		world.setBlock(x+f*1, y+3, z-f*4, Blocks.air);
		world.setBlock(x+f*1, y+3, z-f*5, Blocks.air);
		world.setBlock(x+f*1, y+3, z-f*6, Blocks.air);
		world.setBlock(x+f*1, y+3, z-f*7, Blocks.air);
		world.setBlock(x+f*1, y+3, z-f*8, Blocks.air);
		world.setBlock(x+f*1, y+4, z-f*2, Blocks.air);
		world.setBlock(x+f*1, y+4, z-f*3, Blocks.air);
		world.setBlock(x+f*1, y+4, z-f*7, Blocks.air);
		world.setBlock(x+f*1, y+4, z-f*8, Blocks.air);
		world.setBlock(x+f*1, y+5, z-f*3, Blocks.air);
		world.setBlock(x+f*1, y+5, z-f*4, Blocks.air);
		world.setBlock(x+f*1, y+5, z-f*5, Blocks.air);
		world.setBlock(x+f*1, y+5, z-f*6, Blocks.air);
		world.setBlock(x+f*1, y+5, z-f*7, Blocks.air);
		world.setBlock(x+f*2, y+1, z-f*1, Blocks.air);
		world.setBlock(x+f*2, y+1, z-f*2, Blocks.air);
		world.setBlock(x+f*2, y+1, z-f*3, Blocks.air);
		world.setBlock(x+f*2, y+1, z-f*7, Blocks.air);
		world.setBlock(x+f*2, y+1, z-f*8, Blocks.air);
		world.setBlock(x+f*2, y+1, z-f*9, Blocks.air);
		world.setBlock(x+f*2, y+2, z-f*1, Blocks.air);
		world.setBlock(x+f*2, y+2, z-f*2, Blocks.air);
		world.setBlock(x+f*2, y+2, z-f*3, Blocks.air);
		world.setBlock(x+f*2, y+2, z-f*7, Blocks.air);
		world.setBlock(x+f*2, y+2, z-f*8, Blocks.air);
		world.setBlock(x+f*2, y+2, z-f*9, Blocks.air);
		world.setBlock(x+f*2, y+3, z-f*1, Blocks.air);
		world.setBlock(x+f*2, y+3, z-f*2, Blocks.air);
		world.setBlock(x+f*2, y+3, z-f*3, Blocks.air);
		world.setBlock(x+f*2, y+3, z-f*7, Blocks.air);
		world.setBlock(x+f*2, y+3, z-f*8, Blocks.air);
		world.setBlock(x+f*2, y+3, z-f*9, Blocks.air);
		world.setBlock(x+f*2, y+4, z-f*1, Blocks.air);
		world.setBlock(x+f*2, y+4, z-f*2, Blocks.air);
		world.setBlock(x+f*2, y+4, z-f*3, Blocks.air);
		world.setBlock(x+f*2, y+4, z-f*7, Blocks.air);
		world.setBlock(x+f*2, y+4, z-f*8, Blocks.air);
		world.setBlock(x+f*2, y+4, z-f*9, Blocks.air);
		world.setBlock(x+f*2, y+5, z-f*3, Blocks.air);
		world.setBlock(x+f*2, y+5, z-f*4, Blocks.air);
		world.setBlock(x+f*2, y+5, z-f*5, Blocks.air);
		world.setBlock(x+f*2, y+5, z-f*6, Blocks.air);
		world.setBlock(x+f*2, y+5, z-f*7, Blocks.air);
		world.setBlock(x+f*3, y+1, z-f*1, Blocks.air);
		world.setBlock(x+f*3, y+1, z-f*2, Blocks.air);
		world.setBlock(x+f*3, y+1, z-f*4, Blocks.air);
		world.setBlock(x+f*3, y+1, z-f*5, Blocks.air);
		world.setBlock(x+f*3, y+1, z-f*6, Blocks.air);
		world.setBlock(x+f*3, y+1, z-f*8, Blocks.air);
		world.setBlock(x+f*3, y+1, z-f*9, Blocks.air);
		world.setBlock(x+f*3, y+1, z-f*10, Blocks.air);
		world.setBlock(x+f*3, y+2, z-f*1, Blocks.air);
		world.setBlock(x+f*3, y+2, z-f*2, Blocks.air);
		world.setBlock(x+f*3, y+2, z-f*4, Blocks.air);
		world.setBlock(x+f*3, y+2, z-f*5, Blocks.air);
		world.setBlock(x+f*3, y+2, z-f*6, Blocks.air);
		world.setBlock(x+f*3, y+2, z-f*8, Blocks.air);
		world.setBlock(x+f*3, y+2, z-f*9, Blocks.air);
		world.setBlock(x+f*3, y+2, z-f*10, Blocks.air);
		world.setBlock(x+f*3, y+3, z-f*1, Blocks.air);
		world.setBlock(x+f*3, y+3, z-f*2, Blocks.air);
		world.setBlock(x+f*3, y+3, z-f*4, Blocks.air);
		world.setBlock(x+f*3, y+3, z-f*5, Blocks.air);
		world.setBlock(x+f*3, y+3, z-f*6, Blocks.air);
		world.setBlock(x+f*3, y+3, z-f*8, Blocks.air);
		world.setBlock(x+f*3, y+3, z-f*9, Blocks.air);
		world.setBlock(x+f*3, y+3, z-f*10, Blocks.air);
		world.setBlock(x+f*3, y+4, z-f*1, Blocks.air);
		world.setBlock(x+f*3, y+4, z-f*2, Blocks.air);
		world.setBlock(x+f*3, y+4, z-f*4, Blocks.air);
		world.setBlock(x+f*3, y+4, z-f*5, Blocks.air);
		world.setBlock(x+f*3, y+4, z-f*6, Blocks.air);
		world.setBlock(x+f*3, y+4, z-f*8, Blocks.air);
		world.setBlock(x+f*3, y+4, z-f*9, Blocks.air);
		world.setBlock(x+f*3, y+5, z-f*4, Blocks.air);
		world.setBlock(x+f*3, y+5, z-f*5, Blocks.air);
		world.setBlock(x+f*3, y+5, z-f*6, Blocks.air);
		world.setBlock(x+f*4, y+1, z-f*1, Blocks.air);
		world.setBlock(x+f*4, y+1, z-f*2, Blocks.air);
		world.setBlock(x+f*4, y+1, z-f*4, Blocks.air);
		world.setBlock(x+f*4, y+1, z-f*5, Blocks.air);
		world.setBlock(x+f*4, y+1, z-f*6, Blocks.air);
		world.setBlock(x+f*4, y+1, z-f*8, Blocks.air);
		world.setBlock(x+f*4, y+1, z-f*9, Blocks.air);
		world.setBlock(x+f*4, y+1, z-f*10, Blocks.air);
		world.setBlock(x+f*4, y+2, z-f*1, Blocks.air);
		world.setBlock(x+f*4, y+2, z-f*2, Blocks.air);
		world.setBlock(x+f*4, y+2, z-f*4, Blocks.air);
		world.setBlock(x+f*4, y+2, z-f*6, Blocks.air);
		world.setBlock(x+f*4, y+2, z-f*8, Blocks.air);
		world.setBlock(x+f*4, y+2, z-f*9, Blocks.air);
		world.setBlock(x+f*4, y+2, z-f*10, Blocks.air);
		world.setBlock(x+f*4, y+3, z-f*1, Blocks.air);
		world.setBlock(x+f*4, y+3, z-f*2, Blocks.air);
		world.setBlock(x+f*4, y+3, z-f*4, Blocks.air);
		world.setBlock(x+f*4, y+3, z-f*5, Blocks.air);
		world.setBlock(x+f*4, y+3, z-f*6, Blocks.air);
		world.setBlock(x+f*4, y+3, z-f*8, Blocks.air);
		world.setBlock(x+f*4, y+3, z-f*9, Blocks.air);
		world.setBlock(x+f*4, y+3, z-f*10, Blocks.air);
		world.setBlock(x+f*4, y+4, z-f*4, Blocks.air);
		world.setBlock(x+f*4, y+4, z-f*5, Blocks.air);
		world.setBlock(x+f*4, y+4, z-f*6, Blocks.air);
		world.setBlock(x+f*4, y+4, z-f*8, Blocks.air);
		world.setBlock(x+f*4, y+4, z-f*9, Blocks.air);
		world.setBlock(x+f*4, y+5, z-f*4, Blocks.air);
		world.setBlock(x+f*4, y+5, z-f*5, Blocks.air);
		world.setBlock(x+f*4, y+5, z-f*6, Blocks.air);
		world.setBlock(x+f*5, y+1, z-f*1, Blocks.air);
		world.setBlock(x+f*5, y+1, z-f*2, Blocks.air);
		world.setBlock(x+f*5, y+1, z-f*4, Blocks.air);
		world.setBlock(x+f*5, y+1, z-f*5, Blocks.air);
		world.setBlock(x+f*5, y+1, z-f*6, Blocks.air);
		world.setBlock(x+f*5, y+1, z-f*8, Blocks.air);
		world.setBlock(x+f*5, y+1, z-f*9, Blocks.air);
		world.setBlock(x+f*5, y+1, z-f*10, Blocks.air);
		world.setBlock(x+f*5, y+2, z-f*1, Blocks.air);
		world.setBlock(x+f*5, y+2, z-f*2, Blocks.air);
		world.setBlock(x+f*5, y+2, z-f*4, Blocks.air);
		world.setBlock(x+f*5, y+2, z-f*5, Blocks.air);
		world.setBlock(x+f*5, y+2, z-f*6, Blocks.air);
		world.setBlock(x+f*5, y+2, z-f*8, Blocks.air);
		world.setBlock(x+f*5, y+2, z-f*9, Blocks.air);
		world.setBlock(x+f*5, y+2, z-f*10, Blocks.air);
		world.setBlock(x+f*5, y+3, z-f*1, Blocks.air);
		world.setBlock(x+f*5, y+3, z-f*2, Blocks.air);
		world.setBlock(x+f*5, y+3, z-f*4, Blocks.air);
		world.setBlock(x+f*5, y+3, z-f*5, Blocks.air);
		world.setBlock(x+f*5, y+3, z-f*6, Blocks.air);
		world.setBlock(x+f*5, y+3, z-f*8, Blocks.air);
		world.setBlock(x+f*5, y+3, z-f*9, Blocks.air);
		world.setBlock(x+f*5, y+3, z-f*10, Blocks.air);
		world.setBlock(x+f*5, y+4, z-f*1, Blocks.air);
		world.setBlock(x+f*5, y+4, z-f*2, Blocks.air);
		world.setBlock(x+f*5, y+4, z-f*4, Blocks.air);
		world.setBlock(x+f*5, y+4, z-f*5, Blocks.air);
		world.setBlock(x+f*5, y+4, z-f*6, Blocks.air);
		world.setBlock(x+f*5, y+4, z-f*8, Blocks.air);
		world.setBlock(x+f*5, y+4, z-f*9, Blocks.air);
		world.setBlock(x+f*5, y+5, z-f*4, Blocks.air);
		world.setBlock(x+f*5, y+5, z-f*5, Blocks.air);
		world.setBlock(x+f*5, y+5, z-f*6, Blocks.air);
		world.setBlock(x+f*6, y+1, z-f*1, Blocks.air);
		world.setBlock(x+f*6, y+1, z-f*2, Blocks.air);
		world.setBlock(x+f*6, y+1, z-f*3, Blocks.air);
		world.setBlock(x+f*6, y+1, z-f*7, Blocks.air);
		world.setBlock(x+f*6, y+1, z-f*8, Blocks.air);
		world.setBlock(x+f*6, y+1, z-f*9, Blocks.air);
		world.setBlock(x+f*6, y+2, z-f*1, Blocks.air);
		world.setBlock(x+f*6, y+2, z-f*2, Blocks.air);
		world.setBlock(x+f*6, y+2, z-f*3, Blocks.air);
		world.setBlock(x+f*6, y+2, z-f*7, Blocks.air);
		world.setBlock(x+f*6, y+2, z-f*8, Blocks.air);
		world.setBlock(x+f*6, y+2, z-f*9, Blocks.air);
		world.setBlock(x+f*6, y+3, z-f*1, Blocks.air);
		world.setBlock(x+f*6, y+3, z-f*2, Blocks.air);
		world.setBlock(x+f*6, y+3, z-f*3, Blocks.air);
		world.setBlock(x+f*6, y+3, z-f*7, Blocks.air);
		world.setBlock(x+f*6, y+3, z-f*8, Blocks.air);
		world.setBlock(x+f*6, y+3, z-f*9, Blocks.air);
		world.setBlock(x+f*6, y+4, z-f*1, Blocks.air);
		world.setBlock(x+f*6, y+4, z-f*2, Blocks.air);
		world.setBlock(x+f*6, y+4, z-f*3, Blocks.air);
		world.setBlock(x+f*6, y+4, z-f*7, Blocks.air);
		world.setBlock(x+f*6, y+4, z-f*8, Blocks.air);
		world.setBlock(x+f*6, y+4, z-f*9, Blocks.air);
		world.setBlock(x+f*6, y+5, z-f*3, Blocks.air);
		world.setBlock(x+f*6, y+5, z-f*4, Blocks.air);
		world.setBlock(x+f*6, y+5, z-f*5, Blocks.air);
		world.setBlock(x+f*6, y+5, z-f*6, Blocks.air);
		world.setBlock(x+f*6, y+5, z-f*7, Blocks.air);
		world.setBlock(x+f*7, y+1, z-f*2, Blocks.air);
		world.setBlock(x+f*7, y+1, z-f*3, Blocks.air);
		world.setBlock(x+f*7, y+1, z-f*4, Blocks.air);
		world.setBlock(x+f*7, y+1, z-f*5, Blocks.air);
		world.setBlock(x+f*7, y+1, z-f*6, Blocks.air);
		world.setBlock(x+f*7, y+1, z-f*7, Blocks.air);
		world.setBlock(x+f*7, y+1, z-f*8, Blocks.air);
		world.setBlock(x+f*7, y+2, z-f*2, Blocks.air);
		world.setBlock(x+f*7, y+2, z-f*3, Blocks.air);
		world.setBlock(x+f*7, y+2, z-f*4, Blocks.air);
		world.setBlock(x+f*7, y+2, z-f*5, Blocks.air);
		world.setBlock(x+f*7, y+2, z-f*6, Blocks.air);
		world.setBlock(x+f*7, y+2, z-f*7, Blocks.air);
		world.setBlock(x+f*7, y+2, z-f*8, Blocks.air);
		world.setBlock(x+f*7, y+3, z-f*2, Blocks.air);
		world.setBlock(x+f*7, y+3, z-f*3, Blocks.air);
		world.setBlock(x+f*7, y+3, z-f*4, Blocks.air);
		world.setBlock(x+f*7, y+3, z-f*5, Blocks.air);
		world.setBlock(x+f*7, y+3, z-f*6, Blocks.air);
		world.setBlock(x+f*7, y+3, z-f*7, Blocks.air);
		world.setBlock(x+f*7, y+3, z-f*8, Blocks.air);
		world.setBlock(x+f*7, y+4, z-f*2, Blocks.air);
		world.setBlock(x+f*7, y+4, z-f*3, Blocks.air);
		world.setBlock(x+f*7, y+4, z-f*7, Blocks.air);
		world.setBlock(x+f*7, y+4, z-f*8, Blocks.air);
		world.setBlock(x+f*7, y+5, z-f*3, Blocks.air);
		world.setBlock(x+f*7, y+5, z-f*4, Blocks.air);
		world.setBlock(x+f*7, y+5, z-f*5, Blocks.air);
		world.setBlock(x+f*7, y+5, z-f*6, Blocks.air);
		world.setBlock(x+f*7, y+5, z-f*7, Blocks.air);
	}

}
