/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2015
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
package Reika.ChromatiCraft.World.Dimension.Structure.TDMaze;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import Reika.ChromatiCraft.Base.DimensionStructureGenerator;
import Reika.ChromatiCraft.Base.StructurePiece;
import Reika.ChromatiCraft.Block.Worldgen.BlockStructureShield.BlockType;
import Reika.ChromatiCraft.Registry.ChromaBlocks;
import Reika.DragonAPI.Instantiable.Worldgen.ChunkSplicedGenerationCache;

public class TDMazeEntrance extends StructurePiece {

	public TDMazeEntrance(DimensionStructureGenerator g) {
		super(g);
	}

	@Override
	public void generate(ChunkSplicedGenerationCache world, int i, int j, int k) {
		i -= 6;
		k -= 6;
		Block sh = ChromaBlocks.STRUCTSHIELD.getBlockInstance();
		int ml = BlockType.LIGHT.metadata;
		int ms = BlockType.STONE.metadata;
		Block b = ChromaBlocks.PYLONSTRUCT.getBlockInstance();
		world.setBlock(i+0, j+0, k+0, b, 2);
		world.setBlock(i+0, j+0, k+1, Blocks.air);
		world.setBlock(i+0, j+0, k+2, Blocks.air);
		world.setBlock(i+0, j+0, k+3, Blocks.air);
		world.setBlock(i+0, j+0, k+4, b, 2);
		world.setBlock(i+0, j+0, k+5, Blocks.air);
		world.setBlock(i+0, j+0, k+6, Blocks.air);
		world.setBlock(i+0, j+0, k+7, Blocks.air);
		world.setBlock(i+0, j+0, k+8, b, 2);
		world.setBlock(i+0, j+0, k+9, Blocks.air);
		world.setBlock(i+0, j+0, k+10, Blocks.air);
		world.setBlock(i+0, j+0, k+11, Blocks.air);
		world.setBlock(i+0, j+0, k+12, b, 2);
		world.setBlock(i+0, j+1, k+0, sh, ml);
		world.setBlock(i+0, j+1, k+1, Blocks.air);
		world.setBlock(i+0, j+1, k+2, Blocks.air);
		world.setBlock(i+0, j+1, k+3, Blocks.air);
		world.setBlock(i+0, j+1, k+4, b, 2);
		world.setBlock(i+0, j+1, k+5, Blocks.air);
		world.setBlock(i+0, j+1, k+6, Blocks.air);
		world.setBlock(i+0, j+1, k+7, Blocks.air);
		world.setBlock(i+0, j+1, k+8, b, 2);
		world.setBlock(i+0, j+1, k+9, Blocks.air);
		world.setBlock(i+0, j+1, k+10, Blocks.air);
		world.setBlock(i+0, j+1, k+11, Blocks.air);
		world.setBlock(i+0, j+1, k+12, sh, ml);
		world.setBlock(i+0, j+2, k+0, Blocks.air);
		world.setBlock(i+0, j+2, k+1, Blocks.air);
		world.setBlock(i+0, j+2, k+2, Blocks.air);
		world.setBlock(i+0, j+2, k+3, Blocks.air);
		world.setBlock(i+0, j+2, k+4, b, 2);
		world.setBlock(i+0, j+2, k+5, Blocks.air);
		world.setBlock(i+0, j+2, k+6, Blocks.air);
		world.setBlock(i+0, j+2, k+7, Blocks.air);
		world.setBlock(i+0, j+2, k+8, b, 2);
		world.setBlock(i+0, j+2, k+9, Blocks.air);
		world.setBlock(i+0, j+2, k+10, Blocks.air);
		world.setBlock(i+0, j+2, k+11, Blocks.air);
		world.setBlock(i+0, j+2, k+12, Blocks.air);
		world.setBlock(i+0, j+3, k+0, Blocks.air);
		world.setBlock(i+0, j+3, k+1, Blocks.air);
		world.setBlock(i+0, j+3, k+2, Blocks.air);
		world.setBlock(i+0, j+3, k+3, Blocks.air);
		world.setBlock(i+0, j+3, k+4, b, 7);
		world.setBlock(i+0, j+3, k+5, b, 1);
		world.setBlock(i+0, j+3, k+6, b, 1);
		world.setBlock(i+0, j+3, k+7, b, 1);
		world.setBlock(i+0, j+3, k+8, b, 7);
		world.setBlock(i+0, j+3, k+9, Blocks.air);
		world.setBlock(i+0, j+3, k+10, Blocks.air);
		world.setBlock(i+0, j+3, k+11, Blocks.air);
		world.setBlock(i+0, j+3, k+12, Blocks.air);
		world.setBlock(i+0, j+4, k+0, Blocks.air);
		world.setBlock(i+0, j+4, k+1, Blocks.air);
		world.setBlock(i+0, j+4, k+2, Blocks.air);
		world.setBlock(i+0, j+4, k+3, Blocks.air);
		world.setBlock(i+0, j+4, k+4, Blocks.air);
		world.setBlock(i+0, j+4, k+5, Blocks.air);
		world.setBlock(i+0, j+4, k+6, Blocks.air);
		world.setBlock(i+0, j+4, k+7, Blocks.air);
		world.setBlock(i+0, j+4, k+8, Blocks.air);
		world.setBlock(i+0, j+4, k+9, Blocks.air);
		world.setBlock(i+0, j+4, k+10, Blocks.air);
		world.setBlock(i+0, j+4, k+11, Blocks.air);
		world.setBlock(i+0, j+4, k+12, Blocks.air);
		world.setBlock(i+0, j+5, k+0, Blocks.air);
		world.setBlock(i+0, j+5, k+1, Blocks.air);
		world.setBlock(i+0, j+5, k+2, Blocks.air);
		world.setBlock(i+0, j+5, k+3, Blocks.air);
		world.setBlock(i+0, j+5, k+4, Blocks.air);
		world.setBlock(i+0, j+5, k+5, Blocks.air);
		world.setBlock(i+0, j+5, k+6, Blocks.air);
		world.setBlock(i+0, j+5, k+7, Blocks.air);
		world.setBlock(i+0, j+5, k+8, Blocks.air);
		world.setBlock(i+0, j+5, k+9, Blocks.air);
		world.setBlock(i+0, j+5, k+10, Blocks.air);
		world.setBlock(i+0, j+5, k+11, Blocks.air);
		world.setBlock(i+0, j+5, k+12, Blocks.air);
		world.setBlock(i+1, j+0, k+0, Blocks.air);
		world.setBlock(i+1, j+0, k+1, Blocks.air);
		world.setBlock(i+1, j+0, k+2, Blocks.air);
		world.setBlock(i+1, j+0, k+3, Blocks.air);
		world.setBlock(i+1, j+0, k+4, sh, ms);
		world.setBlock(i+1, j+0, k+5, Blocks.air);
		world.setBlock(i+1, j+0, k+6, Blocks.air);
		world.setBlock(i+1, j+0, k+7, Blocks.air);
		world.setBlock(i+1, j+0, k+8, sh, ms);
		world.setBlock(i+1, j+0, k+9, Blocks.air);
		world.setBlock(i+1, j+0, k+10, Blocks.air);
		world.setBlock(i+1, j+0, k+11, Blocks.air);
		world.setBlock(i+1, j+0, k+12, Blocks.air);
		world.setBlock(i+1, j+1, k+0, Blocks.air);
		world.setBlock(i+1, j+1, k+1, Blocks.air);
		world.setBlock(i+1, j+1, k+2, Blocks.air);
		world.setBlock(i+1, j+1, k+3, Blocks.air);
		world.setBlock(i+1, j+1, k+4, sh, ms);
		world.setBlock(i+1, j+1, k+5, Blocks.air);
		world.setBlock(i+1, j+1, k+6, Blocks.air);
		world.setBlock(i+1, j+1, k+7, Blocks.air);
		world.setBlock(i+1, j+1, k+8, sh, ms);
		world.setBlock(i+1, j+1, k+9, Blocks.air);
		world.setBlock(i+1, j+1, k+10, Blocks.air);
		world.setBlock(i+1, j+1, k+11, Blocks.air);
		world.setBlock(i+1, j+1, k+12, Blocks.air);
		world.setBlock(i+1, j+2, k+0, Blocks.air);
		world.setBlock(i+1, j+2, k+1, Blocks.air);
		world.setBlock(i+1, j+2, k+2, Blocks.air);
		world.setBlock(i+1, j+2, k+3, Blocks.air);
		world.setBlock(i+1, j+2, k+4, sh, ms);
		world.setBlock(i+1, j+2, k+5, Blocks.air);
		world.setBlock(i+1, j+2, k+6, Blocks.air);
		world.setBlock(i+1, j+2, k+7, Blocks.air);
		world.setBlock(i+1, j+2, k+8, sh, ms);
		world.setBlock(i+1, j+2, k+9, Blocks.air);
		world.setBlock(i+1, j+2, k+10, Blocks.air);
		world.setBlock(i+1, j+2, k+11, Blocks.air);
		world.setBlock(i+1, j+2, k+12, Blocks.air);
		world.setBlock(i+1, j+3, k+0, Blocks.air);
		world.setBlock(i+1, j+3, k+1, Blocks.air);
		world.setBlock(i+1, j+3, k+2, Blocks.air);
		world.setBlock(i+1, j+3, k+3, Blocks.air);
		world.setBlock(i+1, j+3, k+4, b, 1);
		world.setBlock(i+1, j+3, k+5, sh, ms);
		world.setBlock(i+1, j+3, k+6, sh, ms);
		world.setBlock(i+1, j+3, k+7, sh, ms);
		world.setBlock(i+1, j+3, k+8, b, 1);
		world.setBlock(i+1, j+3, k+9, Blocks.air);
		world.setBlock(i+1, j+3, k+10, Blocks.air);
		world.setBlock(i+1, j+3, k+11, Blocks.air);
		world.setBlock(i+1, j+3, k+12, Blocks.air);
		world.setBlock(i+1, j+4, k+0, Blocks.air);
		world.setBlock(i+1, j+4, k+1, Blocks.air);
		world.setBlock(i+1, j+4, k+2, Blocks.air);
		world.setBlock(i+1, j+4, k+3, Blocks.air);
		world.setBlock(i+1, j+4, k+4, Blocks.air);
		world.setBlock(i+1, j+4, k+5, Blocks.air);
		world.setBlock(i+1, j+4, k+6, Blocks.air);
		world.setBlock(i+1, j+4, k+7, Blocks.air);
		world.setBlock(i+1, j+4, k+8, Blocks.air);
		world.setBlock(i+1, j+4, k+9, Blocks.air);
		world.setBlock(i+1, j+4, k+10, Blocks.air);
		world.setBlock(i+1, j+4, k+11, Blocks.air);
		world.setBlock(i+1, j+4, k+12, Blocks.air);
		world.setBlock(i+1, j+5, k+0, Blocks.air);
		world.setBlock(i+1, j+5, k+1, Blocks.air);
		world.setBlock(i+1, j+5, k+2, Blocks.air);
		world.setBlock(i+1, j+5, k+3, Blocks.air);
		world.setBlock(i+1, j+5, k+4, Blocks.air);
		world.setBlock(i+1, j+5, k+5, Blocks.air);
		world.setBlock(i+1, j+5, k+6, Blocks.air);
		world.setBlock(i+1, j+5, k+7, Blocks.air);
		world.setBlock(i+1, j+5, k+8, Blocks.air);
		world.setBlock(i+1, j+5, k+9, Blocks.air);
		world.setBlock(i+1, j+5, k+10, Blocks.air);
		world.setBlock(i+1, j+5, k+11, Blocks.air);
		world.setBlock(i+1, j+5, k+12, Blocks.air);
		world.setBlock(i+2, j+0, k+0, Blocks.air);
		world.setBlock(i+2, j+0, k+1, Blocks.air);
		world.setBlock(i+2, j+0, k+2, Blocks.air);
		world.setBlock(i+2, j+0, k+3, Blocks.air);
		world.setBlock(i+2, j+0, k+4, sh, ms);
		world.setBlock(i+2, j+0, k+5, Blocks.air);
		world.setBlock(i+2, j+0, k+6, Blocks.air);
		world.setBlock(i+2, j+0, k+7, Blocks.air);
		world.setBlock(i+2, j+0, k+8, sh, ms);
		world.setBlock(i+2, j+0, k+9, Blocks.air);
		world.setBlock(i+2, j+0, k+10, Blocks.air);
		world.setBlock(i+2, j+0, k+11, Blocks.air);
		world.setBlock(i+2, j+0, k+12, Blocks.air);
		world.setBlock(i+2, j+1, k+0, Blocks.air);
		world.setBlock(i+2, j+1, k+1, Blocks.air);
		world.setBlock(i+2, j+1, k+2, Blocks.air);
		world.setBlock(i+2, j+1, k+3, Blocks.air);
		world.setBlock(i+2, j+1, k+4, sh, ms);
		world.setBlock(i+2, j+1, k+5, Blocks.air);
		world.setBlock(i+2, j+1, k+6, Blocks.air);
		world.setBlock(i+2, j+1, k+7, Blocks.air);
		world.setBlock(i+2, j+1, k+8, sh, ms);
		world.setBlock(i+2, j+1, k+9, Blocks.air);
		world.setBlock(i+2, j+1, k+10, Blocks.air);
		world.setBlock(i+2, j+1, k+11, Blocks.air);
		world.setBlock(i+2, j+1, k+12, Blocks.air);
		world.setBlock(i+2, j+2, k+0, Blocks.air);
		world.setBlock(i+2, j+2, k+1, Blocks.air);
		world.setBlock(i+2, j+2, k+2, Blocks.air);
		world.setBlock(i+2, j+2, k+3, Blocks.air);
		world.setBlock(i+2, j+2, k+4, sh, ms);
		world.setBlock(i+2, j+2, k+5, Blocks.air);
		world.setBlock(i+2, j+2, k+6, Blocks.air);
		world.setBlock(i+2, j+2, k+7, Blocks.air);
		world.setBlock(i+2, j+2, k+8, sh, ms);
		world.setBlock(i+2, j+2, k+9, Blocks.air);
		world.setBlock(i+2, j+2, k+10, Blocks.air);
		world.setBlock(i+2, j+2, k+11, Blocks.air);
		world.setBlock(i+2, j+2, k+12, Blocks.air);
		world.setBlock(i+2, j+3, k+0, Blocks.air);
		world.setBlock(i+2, j+3, k+1, Blocks.air);
		world.setBlock(i+2, j+3, k+2, Blocks.air);
		world.setBlock(i+2, j+3, k+3, Blocks.air);
		world.setBlock(i+2, j+3, k+4, b, 1);
		world.setBlock(i+2, j+3, k+5, sh, ms);
		world.setBlock(i+2, j+3, k+6, sh, ml);
		world.setBlock(i+2, j+3, k+7, sh, ms);
		world.setBlock(i+2, j+3, k+8, b, 1);
		world.setBlock(i+2, j+3, k+9, Blocks.air);
		world.setBlock(i+2, j+3, k+10, Blocks.air);
		world.setBlock(i+2, j+3, k+11, Blocks.air);
		world.setBlock(i+2, j+3, k+12, Blocks.air);
		world.setBlock(i+2, j+4, k+0, Blocks.air);
		world.setBlock(i+2, j+4, k+1, Blocks.air);
		world.setBlock(i+2, j+4, k+2, Blocks.air);
		world.setBlock(i+2, j+4, k+3, Blocks.air);
		world.setBlock(i+2, j+4, k+4, Blocks.air);
		world.setBlock(i+2, j+4, k+5, Blocks.air);
		world.setBlock(i+2, j+4, k+6, Blocks.air);
		world.setBlock(i+2, j+4, k+7, Blocks.air);
		world.setBlock(i+2, j+4, k+8, Blocks.air);
		world.setBlock(i+2, j+4, k+9, Blocks.air);
		world.setBlock(i+2, j+4, k+10, Blocks.air);
		world.setBlock(i+2, j+4, k+11, Blocks.air);
		world.setBlock(i+2, j+4, k+12, Blocks.air);
		world.setBlock(i+2, j+5, k+0, Blocks.air);
		world.setBlock(i+2, j+5, k+1, Blocks.air);
		world.setBlock(i+2, j+5, k+2, Blocks.air);
		world.setBlock(i+2, j+5, k+3, Blocks.air);
		world.setBlock(i+2, j+5, k+4, Blocks.air);
		world.setBlock(i+2, j+5, k+5, Blocks.air);
		world.setBlock(i+2, j+5, k+6, Blocks.air);
		world.setBlock(i+2, j+5, k+7, Blocks.air);
		world.setBlock(i+2, j+5, k+8, Blocks.air);
		world.setBlock(i+2, j+5, k+9, Blocks.air);
		world.setBlock(i+2, j+5, k+10, Blocks.air);
		world.setBlock(i+2, j+5, k+11, Blocks.air);
		world.setBlock(i+2, j+5, k+12, Blocks.air);
		world.setBlock(i+3, j+0, k+0, Blocks.air);
		world.setBlock(i+3, j+0, k+1, Blocks.air);
		world.setBlock(i+3, j+0, k+2, Blocks.air);
		world.setBlock(i+3, j+0, k+3, Blocks.air);
		world.setBlock(i+3, j+0, k+4, sh, ms);
		world.setBlock(i+3, j+0, k+5, Blocks.air);
		world.setBlock(i+3, j+0, k+6, Blocks.air);
		world.setBlock(i+3, j+0, k+7, Blocks.air);
		world.setBlock(i+3, j+0, k+8, sh, ms);
		world.setBlock(i+3, j+0, k+9, Blocks.air);
		world.setBlock(i+3, j+0, k+10, Blocks.air);
		world.setBlock(i+3, j+0, k+11, Blocks.air);
		world.setBlock(i+3, j+0, k+12, Blocks.air);
		world.setBlock(i+3, j+1, k+0, Blocks.air);
		world.setBlock(i+3, j+1, k+1, Blocks.air);
		world.setBlock(i+3, j+1, k+2, Blocks.air);
		world.setBlock(i+3, j+1, k+3, Blocks.air);
		world.setBlock(i+3, j+1, k+4, sh, ms);
		world.setBlock(i+3, j+1, k+5, Blocks.air);
		world.setBlock(i+3, j+1, k+6, Blocks.air);
		world.setBlock(i+3, j+1, k+7, Blocks.air);
		world.setBlock(i+3, j+1, k+8, sh, ms);
		world.setBlock(i+3, j+1, k+9, Blocks.air);
		world.setBlock(i+3, j+1, k+10, Blocks.air);
		world.setBlock(i+3, j+1, k+11, Blocks.air);
		world.setBlock(i+3, j+1, k+12, Blocks.air);
		world.setBlock(i+3, j+2, k+0, Blocks.air);
		world.setBlock(i+3, j+2, k+1, Blocks.air);
		world.setBlock(i+3, j+2, k+2, Blocks.air);
		world.setBlock(i+3, j+2, k+3, Blocks.air);
		world.setBlock(i+3, j+2, k+4, sh, ms);
		world.setBlock(i+3, j+2, k+5, Blocks.air);
		world.setBlock(i+3, j+2, k+6, Blocks.air);
		world.setBlock(i+3, j+2, k+7, Blocks.air);
		world.setBlock(i+3, j+2, k+8, sh, ms);
		world.setBlock(i+3, j+2, k+9, Blocks.air);
		world.setBlock(i+3, j+2, k+10, Blocks.air);
		world.setBlock(i+3, j+2, k+11, Blocks.air);
		world.setBlock(i+3, j+2, k+12, Blocks.air);
		world.setBlock(i+3, j+3, k+0, Blocks.air);
		world.setBlock(i+3, j+3, k+1, Blocks.air);
		world.setBlock(i+3, j+3, k+2, Blocks.air);
		world.setBlock(i+3, j+3, k+3, Blocks.air);
		world.setBlock(i+3, j+3, k+4, b, 1);
		world.setBlock(i+3, j+3, k+5, sh, ms);
		world.setBlock(i+3, j+3, k+6, sh, ms);
		world.setBlock(i+3, j+3, k+7, sh, ms);
		world.setBlock(i+3, j+3, k+8, b, 1);
		world.setBlock(i+3, j+3, k+9, Blocks.air);
		world.setBlock(i+3, j+3, k+10, Blocks.air);
		world.setBlock(i+3, j+3, k+11, Blocks.air);
		world.setBlock(i+3, j+3, k+12, Blocks.air);
		world.setBlock(i+3, j+4, k+0, Blocks.air);
		world.setBlock(i+3, j+4, k+1, Blocks.air);
		world.setBlock(i+3, j+4, k+2, Blocks.air);
		world.setBlock(i+3, j+4, k+3, Blocks.air);
		world.setBlock(i+3, j+4, k+4, Blocks.air);
		world.setBlock(i+3, j+4, k+5, Blocks.air);
		world.setBlock(i+3, j+4, k+6, Blocks.air);
		world.setBlock(i+3, j+4, k+7, Blocks.air);
		world.setBlock(i+3, j+4, k+8, Blocks.air);
		world.setBlock(i+3, j+4, k+9, Blocks.air);
		world.setBlock(i+3, j+4, k+10, Blocks.air);
		world.setBlock(i+3, j+4, k+11, Blocks.air);
		world.setBlock(i+3, j+4, k+12, Blocks.air);
		world.setBlock(i+3, j+5, k+0, Blocks.air);
		world.setBlock(i+3, j+5, k+1, Blocks.air);
		world.setBlock(i+3, j+5, k+2, Blocks.air);
		world.setBlock(i+3, j+5, k+3, Blocks.air);
		world.setBlock(i+3, j+5, k+4, Blocks.air);
		world.setBlock(i+3, j+5, k+5, Blocks.air);
		world.setBlock(i+3, j+5, k+6, Blocks.air);
		world.setBlock(i+3, j+5, k+7, Blocks.air);
		world.setBlock(i+3, j+5, k+8, Blocks.air);
		world.setBlock(i+3, j+5, k+9, Blocks.air);
		world.setBlock(i+3, j+5, k+10, Blocks.air);
		world.setBlock(i+3, j+5, k+11, Blocks.air);
		world.setBlock(i+3, j+5, k+12, Blocks.air);
		world.setBlock(i+4, j+0, k+0, b, 2);
		world.setBlock(i+4, j+0, k+1, sh, ms);
		world.setBlock(i+4, j+0, k+2, sh, ms);
		world.setBlock(i+4, j+0, k+3, sh, ms);
		world.setBlock(i+4, j+0, k+4, b, 2);
		world.setBlock(i+4, j+0, k+5, Blocks.air);
		world.setBlock(i+4, j+0, k+6, Blocks.air);
		world.setBlock(i+4, j+0, k+7, Blocks.air);
		world.setBlock(i+4, j+0, k+8, b, 2);
		world.setBlock(i+4, j+0, k+9, sh, ms);
		world.setBlock(i+4, j+0, k+10, sh, ms);
		world.setBlock(i+4, j+0, k+11, sh, ms);
		world.setBlock(i+4, j+0, k+12, b, 2);
		world.setBlock(i+4, j+1, k+0, b, 2);
		world.setBlock(i+4, j+1, k+1, sh, ms);
		world.setBlock(i+4, j+1, k+2, sh, ms);
		world.setBlock(i+4, j+1, k+3, sh, ms);
		world.setBlock(i+4, j+1, k+4, b, 2);
		world.setBlock(i+4, j+1, k+5, Blocks.air);
		world.setBlock(i+4, j+1, k+6, Blocks.air);
		world.setBlock(i+4, j+1, k+7, Blocks.air);
		world.setBlock(i+4, j+1, k+8, b, 2);
		world.setBlock(i+4, j+1, k+9, sh, ms);
		world.setBlock(i+4, j+1, k+10, sh, ms);
		world.setBlock(i+4, j+1, k+11, sh, ms);
		world.setBlock(i+4, j+1, k+12, b, 2);
		world.setBlock(i+4, j+2, k+0, b, 2);
		world.setBlock(i+4, j+2, k+1, sh, ms);
		world.setBlock(i+4, j+2, k+2, sh, ms);
		world.setBlock(i+4, j+2, k+3, sh, ms);
		world.setBlock(i+4, j+2, k+4, b, 2);
		world.setBlock(i+4, j+2, k+5, Blocks.air);
		world.setBlock(i+4, j+2, k+6, Blocks.air);
		world.setBlock(i+4, j+2, k+7, Blocks.air);
		world.setBlock(i+4, j+2, k+8, b, 2);
		world.setBlock(i+4, j+2, k+9, sh, ms);
		world.setBlock(i+4, j+2, k+10, sh, ms);
		world.setBlock(i+4, j+2, k+11, sh, ms);
		world.setBlock(i+4, j+2, k+12, b, 2);
		world.setBlock(i+4, j+3, k+0, b, 7);
		world.setBlock(i+4, j+3, k+1, b, 1);
		world.setBlock(i+4, j+3, k+2, b, 1);
		world.setBlock(i+4, j+3, k+3, b, 1);
		world.setBlock(i+4, j+3, k+4, b, 8);
		world.setBlock(i+4, j+3, k+5, b, 1);
		world.setBlock(i+4, j+3, k+6, b, 1);
		world.setBlock(i+4, j+3, k+7, b, 1);
		world.setBlock(i+4, j+3, k+8, b, 8);
		world.setBlock(i+4, j+3, k+9, b, 1);
		world.setBlock(i+4, j+3, k+10, b, 1);
		world.setBlock(i+4, j+3, k+11, b, 1);
		world.setBlock(i+4, j+3, k+12, b, 7);
		world.setBlock(i+4, j+4, k+0, Blocks.air);
		world.setBlock(i+4, j+4, k+1, Blocks.air);
		world.setBlock(i+4, j+4, k+2, Blocks.air);
		world.setBlock(i+4, j+4, k+3, Blocks.air);
		world.setBlock(i+4, j+4, k+4, b, 2);
		world.setBlock(i+4, j+4, k+5, sh, ms);
		world.setBlock(i+4, j+4, k+6, sh, ms);
		world.setBlock(i+4, j+4, k+7, sh, ms);
		world.setBlock(i+4, j+4, k+8, b, 2);
		world.setBlock(i+4, j+4, k+9, Blocks.air);
		world.setBlock(i+4, j+4, k+10, Blocks.air);
		world.setBlock(i+4, j+4, k+11, Blocks.air);
		world.setBlock(i+4, j+4, k+12, Blocks.air);
		world.setBlock(i+4, j+5, k+0, Blocks.air);
		world.setBlock(i+4, j+5, k+1, Blocks.air);
		world.setBlock(i+4, j+5, k+2, Blocks.air);
		world.setBlock(i+4, j+5, k+3, Blocks.air);
		world.setBlock(i+4, j+5, k+4, b, 7);
		world.setBlock(i+4, j+5, k+5, b, 1);
		world.setBlock(i+4, j+5, k+6, b, 1);
		world.setBlock(i+4, j+5, k+7, b, 1);
		world.setBlock(i+4, j+5, k+8, b, 7);
		world.setBlock(i+4, j+5, k+9, Blocks.air);
		world.setBlock(i+4, j+5, k+10, Blocks.air);
		world.setBlock(i+4, j+5, k+11, Blocks.air);
		world.setBlock(i+4, j+5, k+12, Blocks.air);
		world.setBlock(i+5, j+0, k+0, Blocks.air);
		world.setBlock(i+5, j+0, k+1, Blocks.air);
		world.setBlock(i+5, j+0, k+2, Blocks.air);
		world.setBlock(i+5, j+0, k+3, Blocks.air);
		world.setBlock(i+5, j+0, k+4, Blocks.air);
		world.setBlock(i+5, j+0, k+5, Blocks.air);
		world.setBlock(i+5, j+0, k+6, Blocks.air);
		world.setBlock(i+5, j+0, k+7, Blocks.air);
		world.setBlock(i+5, j+0, k+8, Blocks.air);
		world.setBlock(i+5, j+0, k+9, Blocks.air);
		world.setBlock(i+5, j+0, k+10, Blocks.air);
		world.setBlock(i+5, j+0, k+11, Blocks.air);
		world.setBlock(i+5, j+0, k+12, Blocks.air);
		world.setBlock(i+5, j+1, k+0, Blocks.air);
		world.setBlock(i+5, j+1, k+1, Blocks.air);
		world.setBlock(i+5, j+1, k+2, Blocks.air);
		world.setBlock(i+5, j+1, k+3, Blocks.air);
		world.setBlock(i+5, j+1, k+4, Blocks.air);
		world.setBlock(i+5, j+1, k+5, Blocks.air);
		world.setBlock(i+5, j+1, k+6, Blocks.air);
		world.setBlock(i+5, j+1, k+7, Blocks.air);
		world.setBlock(i+5, j+1, k+8, Blocks.air);
		world.setBlock(i+5, j+1, k+9, Blocks.air);
		world.setBlock(i+5, j+1, k+10, Blocks.air);
		world.setBlock(i+5, j+1, k+11, Blocks.air);
		world.setBlock(i+5, j+1, k+12, Blocks.air);
		world.setBlock(i+5, j+2, k+0, Blocks.air);
		world.setBlock(i+5, j+2, k+1, Blocks.air);
		world.setBlock(i+5, j+2, k+2, Blocks.air);
		world.setBlock(i+5, j+2, k+3, Blocks.air);
		world.setBlock(i+5, j+2, k+4, Blocks.air);
		world.setBlock(i+5, j+2, k+5, Blocks.air);
		world.setBlock(i+5, j+2, k+6, Blocks.air);
		world.setBlock(i+5, j+2, k+7, Blocks.air);
		world.setBlock(i+5, j+2, k+8, Blocks.air);
		world.setBlock(i+5, j+2, k+9, Blocks.air);
		world.setBlock(i+5, j+2, k+10, Blocks.air);
		world.setBlock(i+5, j+2, k+11, Blocks.air);
		world.setBlock(i+5, j+2, k+12, Blocks.air);
		world.setBlock(i+5, j+3, k+0, b, 1);
		world.setBlock(i+5, j+3, k+1, sh, ms);
		world.setBlock(i+5, j+3, k+2, sh, ms);
		world.setBlock(i+5, j+3, k+3, sh, ms);
		world.setBlock(i+5, j+3, k+4, b, 1);
		world.setBlock(i+5, j+3, k+5, Blocks.air);
		world.setBlock(i+5, j+3, k+6, Blocks.air);
		world.setBlock(i+5, j+3, k+7, Blocks.air);
		world.setBlock(i+5, j+3, k+8, b, 1);
		world.setBlock(i+5, j+3, k+9, sh, ms);
		world.setBlock(i+5, j+3, k+10, sh, ms);
		world.setBlock(i+5, j+3, k+11, sh, ms);
		world.setBlock(i+5, j+3, k+12, b, 1);
		world.setBlock(i+5, j+4, k+0, Blocks.air);
		world.setBlock(i+5, j+4, k+1, Blocks.air);
		world.setBlock(i+5, j+4, k+2, Blocks.air);
		world.setBlock(i+5, j+4, k+3, Blocks.air);
		world.setBlock(i+5, j+4, k+4, sh, ms);
		world.setBlock(i+5, j+4, k+5, Blocks.air);
		world.setBlock(i+5, j+4, k+6, Blocks.air);
		world.setBlock(i+5, j+4, k+7, Blocks.air);
		world.setBlock(i+5, j+4, k+8, sh, ms);
		world.setBlock(i+5, j+4, k+9, Blocks.air);
		world.setBlock(i+5, j+4, k+10, Blocks.air);
		world.setBlock(i+5, j+4, k+11, Blocks.air);
		world.setBlock(i+5, j+4, k+12, Blocks.air);
		world.setBlock(i+5, j+5, k+0, Blocks.air);
		world.setBlock(i+5, j+5, k+1, Blocks.air);
		world.setBlock(i+5, j+5, k+2, Blocks.air);
		world.setBlock(i+5, j+5, k+3, Blocks.air);
		world.setBlock(i+5, j+5, k+4, b, 1);
		world.setBlock(i+5, j+5, k+5, sh, ms);
		world.setBlock(i+5, j+5, k+6, sh, ms);
		world.setBlock(i+5, j+5, k+7, sh, ms);
		world.setBlock(i+5, j+5, k+8, b, 1);
		world.setBlock(i+5, j+5, k+9, Blocks.air);
		world.setBlock(i+5, j+5, k+10, Blocks.air);
		world.setBlock(i+5, j+5, k+11, Blocks.air);
		world.setBlock(i+5, j+5, k+12, Blocks.air);
		world.setBlock(i+6, j+0, k+0, Blocks.air);
		world.setBlock(i+6, j+0, k+1, Blocks.air);
		world.setBlock(i+6, j+0, k+2, Blocks.air);
		world.setBlock(i+6, j+0, k+3, Blocks.air);
		world.setBlock(i+6, j+0, k+4, Blocks.air);
		world.setBlock(i+6, j+0, k+5, Blocks.air);
		world.setBlock(i+6, j+0, k+6, Blocks.air);
		world.setBlock(i+6, j+0, k+7, Blocks.air);
		world.setBlock(i+6, j+0, k+8, Blocks.air);
		world.setBlock(i+6, j+0, k+9, Blocks.air);
		world.setBlock(i+6, j+0, k+10, Blocks.air);
		world.setBlock(i+6, j+0, k+11, Blocks.air);
		world.setBlock(i+6, j+0, k+12, Blocks.air);
		world.setBlock(i+6, j+1, k+0, Blocks.air);
		world.setBlock(i+6, j+1, k+1, Blocks.air);
		world.setBlock(i+6, j+1, k+2, Blocks.air);
		world.setBlock(i+6, j+1, k+3, Blocks.air);
		world.setBlock(i+6, j+1, k+4, Blocks.air);
		world.setBlock(i+6, j+1, k+5, Blocks.air);
		world.setBlock(i+6, j+1, k+6, Blocks.air);
		world.setBlock(i+6, j+1, k+7, Blocks.air);
		world.setBlock(i+6, j+1, k+8, Blocks.air);
		world.setBlock(i+6, j+1, k+9, Blocks.air);
		world.setBlock(i+6, j+1, k+10, Blocks.air);
		world.setBlock(i+6, j+1, k+11, Blocks.air);
		world.setBlock(i+6, j+1, k+12, Blocks.air);
		world.setBlock(i+6, j+2, k+0, Blocks.air);
		world.setBlock(i+6, j+2, k+1, Blocks.air);
		world.setBlock(i+6, j+2, k+2, Blocks.air);
		world.setBlock(i+6, j+2, k+3, Blocks.air);
		world.setBlock(i+6, j+2, k+4, Blocks.air);
		world.setBlock(i+6, j+2, k+5, Blocks.air);
		world.setBlock(i+6, j+2, k+6, Blocks.air);
		world.setBlock(i+6, j+2, k+7, Blocks.air);
		world.setBlock(i+6, j+2, k+8, Blocks.air);
		world.setBlock(i+6, j+2, k+9, Blocks.air);
		world.setBlock(i+6, j+2, k+10, Blocks.air);
		world.setBlock(i+6, j+2, k+11, Blocks.air);
		world.setBlock(i+6, j+2, k+12, Blocks.air);
		world.setBlock(i+6, j+3, k+0, b, 1);
		world.setBlock(i+6, j+3, k+1, sh, ms);
		world.setBlock(i+6, j+3, k+2, sh, ml);
		world.setBlock(i+6, j+3, k+3, sh, ms);
		world.setBlock(i+6, j+3, k+4, b, 1);
		world.setBlock(i+6, j+3, k+5, Blocks.air);
		world.setBlock(i+6, j+3, k+6, sh, ml);
		world.setBlock(i+6, j+3, k+7, Blocks.air);
		world.setBlock(i+6, j+3, k+8, b, 1);
		world.setBlock(i+6, j+3, k+9, sh, ms);
		world.setBlock(i+6, j+3, k+10, sh, ml);
		world.setBlock(i+6, j+3, k+11, sh, ms);
		world.setBlock(i+6, j+3, k+12, b, 1);
		world.setBlock(i+6, j+4, k+0, Blocks.air);
		world.setBlock(i+6, j+4, k+1, Blocks.air);
		world.setBlock(i+6, j+4, k+2, Blocks.air);
		world.setBlock(i+6, j+4, k+3, Blocks.air);
		world.setBlock(i+6, j+4, k+4, sh, ms);
		world.setBlock(i+6, j+4, k+5, Blocks.air);
		world.setBlock(i+6, j+4, k+6, b, 2);
		world.setBlock(i+6, j+4, k+7, Blocks.air);
		world.setBlock(i+6, j+4, k+8, sh, ms);
		world.setBlock(i+6, j+4, k+9, Blocks.air);
		world.setBlock(i+6, j+4, k+10, Blocks.air);
		world.setBlock(i+6, j+4, k+11, Blocks.air);
		world.setBlock(i+6, j+4, k+12, Blocks.air);
		world.setBlock(i+6, j+5, k+0, Blocks.air);
		world.setBlock(i+6, j+5, k+1, Blocks.air);
		world.setBlock(i+6, j+5, k+2, Blocks.air);
		world.setBlock(i+6, j+5, k+3, Blocks.air);
		world.setBlock(i+6, j+5, k+4, b, 1);
		world.setBlock(i+6, j+5, k+5, sh, ms);
		world.setBlock(i+6, j+5, k+6, sh, ms);
		world.setBlock(i+6, j+5, k+7, sh, ms);
		world.setBlock(i+6, j+5, k+8, b, 1);
		world.setBlock(i+6, j+5, k+9, Blocks.air);
		world.setBlock(i+6, j+5, k+10, Blocks.air);
		world.setBlock(i+6, j+5, k+11, Blocks.air);
		world.setBlock(i+6, j+5, k+12, Blocks.air);
		world.setBlock(i+7, j+0, k+0, Blocks.air);
		world.setBlock(i+7, j+0, k+1, Blocks.air);
		world.setBlock(i+7, j+0, k+2, Blocks.air);
		world.setBlock(i+7, j+0, k+3, Blocks.air);
		world.setBlock(i+7, j+0, k+4, Blocks.air);
		world.setBlock(i+7, j+0, k+5, Blocks.air);
		world.setBlock(i+7, j+0, k+6, Blocks.air);
		world.setBlock(i+7, j+0, k+7, Blocks.air);
		world.setBlock(i+7, j+0, k+8, Blocks.air);
		world.setBlock(i+7, j+0, k+9, Blocks.air);
		world.setBlock(i+7, j+0, k+10, Blocks.air);
		world.setBlock(i+7, j+0, k+11, Blocks.air);
		world.setBlock(i+7, j+0, k+12, Blocks.air);
		world.setBlock(i+7, j+1, k+0, Blocks.air);
		world.setBlock(i+7, j+1, k+1, Blocks.air);
		world.setBlock(i+7, j+1, k+2, Blocks.air);
		world.setBlock(i+7, j+1, k+3, Blocks.air);
		world.setBlock(i+7, j+1, k+4, Blocks.air);
		world.setBlock(i+7, j+1, k+5, Blocks.air);
		world.setBlock(i+7, j+1, k+6, Blocks.air);
		world.setBlock(i+7, j+1, k+7, Blocks.air);
		world.setBlock(i+7, j+1, k+8, Blocks.air);
		world.setBlock(i+7, j+1, k+9, Blocks.air);
		world.setBlock(i+7, j+1, k+10, Blocks.air);
		world.setBlock(i+7, j+1, k+11, Blocks.air);
		world.setBlock(i+7, j+1, k+12, Blocks.air);
		world.setBlock(i+7, j+2, k+0, Blocks.air);
		world.setBlock(i+7, j+2, k+1, Blocks.air);
		world.setBlock(i+7, j+2, k+2, Blocks.air);
		world.setBlock(i+7, j+2, k+3, Blocks.air);
		world.setBlock(i+7, j+2, k+4, Blocks.air);
		world.setBlock(i+7, j+2, k+5, Blocks.air);
		world.setBlock(i+7, j+2, k+6, Blocks.air);
		world.setBlock(i+7, j+2, k+7, Blocks.air);
		world.setBlock(i+7, j+2, k+8, Blocks.air);
		world.setBlock(i+7, j+2, k+9, Blocks.air);
		world.setBlock(i+7, j+2, k+10, Blocks.air);
		world.setBlock(i+7, j+2, k+11, Blocks.air);
		world.setBlock(i+7, j+2, k+12, Blocks.air);
		world.setBlock(i+7, j+3, k+0, b, 1);
		world.setBlock(i+7, j+3, k+1, sh, ms);
		world.setBlock(i+7, j+3, k+2, sh, ms);
		world.setBlock(i+7, j+3, k+3, sh, ms);
		world.setBlock(i+7, j+3, k+4, b, 1);
		world.setBlock(i+7, j+3, k+5, Blocks.air);
		world.setBlock(i+7, j+3, k+6, Blocks.air);
		world.setBlock(i+7, j+3, k+7, Blocks.air);
		world.setBlock(i+7, j+3, k+8, b, 1);
		world.setBlock(i+7, j+3, k+9, sh, ms);
		world.setBlock(i+7, j+3, k+10, sh, ms);
		world.setBlock(i+7, j+3, k+11, sh, ms);
		world.setBlock(i+7, j+3, k+12, b, 1);
		world.setBlock(i+7, j+4, k+0, Blocks.air);
		world.setBlock(i+7, j+4, k+1, Blocks.air);
		world.setBlock(i+7, j+4, k+2, Blocks.air);
		world.setBlock(i+7, j+4, k+3, Blocks.air);
		world.setBlock(i+7, j+4, k+4, sh, ms);
		world.setBlock(i+7, j+4, k+5, Blocks.air);
		world.setBlock(i+7, j+4, k+6, Blocks.air);
		world.setBlock(i+7, j+4, k+7, Blocks.air);
		world.setBlock(i+7, j+4, k+8, sh, ms);
		world.setBlock(i+7, j+4, k+9, Blocks.air);
		world.setBlock(i+7, j+4, k+10, Blocks.air);
		world.setBlock(i+7, j+4, k+11, Blocks.air);
		world.setBlock(i+7, j+4, k+12, Blocks.air);
		world.setBlock(i+7, j+5, k+0, Blocks.air);
		world.setBlock(i+7, j+5, k+1, Blocks.air);
		world.setBlock(i+7, j+5, k+2, Blocks.air);
		world.setBlock(i+7, j+5, k+3, Blocks.air);
		world.setBlock(i+7, j+5, k+4, b, 1);
		world.setBlock(i+7, j+5, k+5, sh, ms);
		world.setBlock(i+7, j+5, k+6, sh, ms);
		world.setBlock(i+7, j+5, k+7, sh, ms);
		world.setBlock(i+7, j+5, k+8, b, 1);
		world.setBlock(i+7, j+5, k+9, Blocks.air);
		world.setBlock(i+7, j+5, k+10, Blocks.air);
		world.setBlock(i+7, j+5, k+11, Blocks.air);
		world.setBlock(i+7, j+5, k+12, Blocks.air);
		world.setBlock(i+8, j+0, k+0, b, 2);
		world.setBlock(i+8, j+0, k+1, sh, ms);
		world.setBlock(i+8, j+0, k+2, sh, ms);
		world.setBlock(i+8, j+0, k+3, sh, ms);
		world.setBlock(i+8, j+0, k+4, b, 2);
		world.setBlock(i+8, j+0, k+5, Blocks.air);
		world.setBlock(i+8, j+0, k+6, Blocks.air);
		world.setBlock(i+8, j+0, k+7, Blocks.air);
		world.setBlock(i+8, j+0, k+8, b, 2);
		world.setBlock(i+8, j+0, k+9, sh, ms);
		world.setBlock(i+8, j+0, k+10, sh, ms);
		world.setBlock(i+8, j+0, k+11, sh, ms);
		world.setBlock(i+8, j+0, k+12, b, 2);
		world.setBlock(i+8, j+1, k+0, b, 2);
		world.setBlock(i+8, j+1, k+1, sh, ms);
		world.setBlock(i+8, j+1, k+2, sh, ms);
		world.setBlock(i+8, j+1, k+3, sh, ms);
		world.setBlock(i+8, j+1, k+4, b, 2);
		world.setBlock(i+8, j+1, k+5, Blocks.air);
		world.setBlock(i+8, j+1, k+6, Blocks.air);
		world.setBlock(i+8, j+1, k+7, Blocks.air);
		world.setBlock(i+8, j+1, k+8, b, 2);
		world.setBlock(i+8, j+1, k+9, sh, ms);
		world.setBlock(i+8, j+1, k+10, sh, ms);
		world.setBlock(i+8, j+1, k+11, sh, ms);
		world.setBlock(i+8, j+1, k+12, b, 2);
		world.setBlock(i+8, j+2, k+0, b, 2);
		world.setBlock(i+8, j+2, k+1, sh, ms);
		world.setBlock(i+8, j+2, k+2, sh, ms);
		world.setBlock(i+8, j+2, k+3, sh, ms);
		world.setBlock(i+8, j+2, k+4, b, 2);
		world.setBlock(i+8, j+2, k+5, Blocks.air);
		world.setBlock(i+8, j+2, k+6, Blocks.air);
		world.setBlock(i+8, j+2, k+7, Blocks.air);
		world.setBlock(i+8, j+2, k+8, b, 2);
		world.setBlock(i+8, j+2, k+9, sh, ms);
		world.setBlock(i+8, j+2, k+10, sh, ms);
		world.setBlock(i+8, j+2, k+11, sh, ms);
		world.setBlock(i+8, j+2, k+12, b, 2);
		world.setBlock(i+8, j+3, k+0, b, 7);
		world.setBlock(i+8, j+3, k+1, b, 1);
		world.setBlock(i+8, j+3, k+2, b, 1);
		world.setBlock(i+8, j+3, k+3, b, 1);
		world.setBlock(i+8, j+3, k+4, b, 8);
		world.setBlock(i+8, j+3, k+5, b, 1);
		world.setBlock(i+8, j+3, k+6, b, 1);
		world.setBlock(i+8, j+3, k+7, b, 1);
		world.setBlock(i+8, j+3, k+8, b, 8);
		world.setBlock(i+8, j+3, k+9, b, 1);
		world.setBlock(i+8, j+3, k+10, b, 1);
		world.setBlock(i+8, j+3, k+11, b, 1);
		world.setBlock(i+8, j+3, k+12, b, 7);
		world.setBlock(i+8, j+4, k+0, Blocks.air);
		world.setBlock(i+8, j+4, k+1, Blocks.air);
		world.setBlock(i+8, j+4, k+2, Blocks.air);
		world.setBlock(i+8, j+4, k+3, Blocks.air);
		world.setBlock(i+8, j+4, k+4, b, 2);
		world.setBlock(i+8, j+4, k+5, sh, ms);
		world.setBlock(i+8, j+4, k+6, sh, ms);
		world.setBlock(i+8, j+4, k+7, sh, ms);
		world.setBlock(i+8, j+4, k+8, b, 2);
		world.setBlock(i+8, j+4, k+9, Blocks.air);
		world.setBlock(i+8, j+4, k+10, Blocks.air);
		world.setBlock(i+8, j+4, k+11, Blocks.air);
		world.setBlock(i+8, j+4, k+12, Blocks.air);
		world.setBlock(i+8, j+5, k+0, Blocks.air);
		world.setBlock(i+8, j+5, k+1, Blocks.air);
		world.setBlock(i+8, j+5, k+2, Blocks.air);
		world.setBlock(i+8, j+5, k+3, Blocks.air);
		world.setBlock(i+8, j+5, k+4, b, 7);
		world.setBlock(i+8, j+5, k+5, b, 1);
		world.setBlock(i+8, j+5, k+6, b, 1);
		world.setBlock(i+8, j+5, k+7, b, 1);
		world.setBlock(i+8, j+5, k+8, b, 7);
		world.setBlock(i+8, j+5, k+9, Blocks.air);
		world.setBlock(i+8, j+5, k+10, Blocks.air);
		world.setBlock(i+8, j+5, k+11, Blocks.air);
		world.setBlock(i+8, j+5, k+12, Blocks.air);
		world.setBlock(i+9, j+0, k+0, Blocks.air);
		world.setBlock(i+9, j+0, k+1, Blocks.air);
		world.setBlock(i+9, j+0, k+2, Blocks.air);
		world.setBlock(i+9, j+0, k+3, Blocks.air);
		world.setBlock(i+9, j+0, k+4, sh, ms);
		world.setBlock(i+9, j+0, k+5, Blocks.air);
		world.setBlock(i+9, j+0, k+6, Blocks.air);
		world.setBlock(i+9, j+0, k+7, Blocks.air);
		world.setBlock(i+9, j+0, k+8, sh, ms);
		world.setBlock(i+9, j+0, k+9, Blocks.air);
		world.setBlock(i+9, j+0, k+10, Blocks.air);
		world.setBlock(i+9, j+0, k+11, Blocks.air);
		world.setBlock(i+9, j+0, k+12, Blocks.air);
		world.setBlock(i+9, j+1, k+0, Blocks.air);
		world.setBlock(i+9, j+1, k+1, Blocks.air);
		world.setBlock(i+9, j+1, k+2, Blocks.air);
		world.setBlock(i+9, j+1, k+3, Blocks.air);
		world.setBlock(i+9, j+1, k+4, sh, ms);
		world.setBlock(i+9, j+1, k+5, Blocks.air);
		world.setBlock(i+9, j+1, k+6, Blocks.air);
		world.setBlock(i+9, j+1, k+7, Blocks.air);
		world.setBlock(i+9, j+1, k+8, sh, ms);
		world.setBlock(i+9, j+1, k+9, Blocks.air);
		world.setBlock(i+9, j+1, k+10, Blocks.air);
		world.setBlock(i+9, j+1, k+11, Blocks.air);
		world.setBlock(i+9, j+1, k+12, Blocks.air);
		world.setBlock(i+9, j+2, k+0, Blocks.air);
		world.setBlock(i+9, j+2, k+1, Blocks.air);
		world.setBlock(i+9, j+2, k+2, Blocks.air);
		world.setBlock(i+9, j+2, k+3, Blocks.air);
		world.setBlock(i+9, j+2, k+4, sh, ms);
		world.setBlock(i+9, j+2, k+5, Blocks.air);
		world.setBlock(i+9, j+2, k+6, Blocks.air);
		world.setBlock(i+9, j+2, k+7, Blocks.air);
		world.setBlock(i+9, j+2, k+8, sh, ms);
		world.setBlock(i+9, j+2, k+9, Blocks.air);
		world.setBlock(i+9, j+2, k+10, Blocks.air);
		world.setBlock(i+9, j+2, k+11, Blocks.air);
		world.setBlock(i+9, j+2, k+12, Blocks.air);
		world.setBlock(i+9, j+3, k+0, Blocks.air);
		world.setBlock(i+9, j+3, k+1, Blocks.air);
		world.setBlock(i+9, j+3, k+2, Blocks.air);
		world.setBlock(i+9, j+3, k+3, Blocks.air);
		world.setBlock(i+9, j+3, k+4, b, 1);
		world.setBlock(i+9, j+3, k+5, sh, ms);
		world.setBlock(i+9, j+3, k+6, sh, ms);
		world.setBlock(i+9, j+3, k+7, sh, ms);
		world.setBlock(i+9, j+3, k+8, b, 1);
		world.setBlock(i+9, j+3, k+9, Blocks.air);
		world.setBlock(i+9, j+3, k+10, Blocks.air);
		world.setBlock(i+9, j+3, k+11, Blocks.air);
		world.setBlock(i+9, j+3, k+12, Blocks.air);
		world.setBlock(i+9, j+4, k+0, Blocks.air);
		world.setBlock(i+9, j+4, k+1, Blocks.air);
		world.setBlock(i+9, j+4, k+2, Blocks.air);
		world.setBlock(i+9, j+4, k+3, Blocks.air);
		world.setBlock(i+9, j+4, k+4, Blocks.air);
		world.setBlock(i+9, j+4, k+5, Blocks.air);
		world.setBlock(i+9, j+4, k+6, Blocks.air);
		world.setBlock(i+9, j+4, k+7, Blocks.air);
		world.setBlock(i+9, j+4, k+8, Blocks.air);
		world.setBlock(i+9, j+4, k+9, Blocks.air);
		world.setBlock(i+9, j+4, k+10, Blocks.air);
		world.setBlock(i+9, j+4, k+11, Blocks.air);
		world.setBlock(i+9, j+4, k+12, Blocks.air);
		world.setBlock(i+9, j+5, k+0, Blocks.air);
		world.setBlock(i+9, j+5, k+1, Blocks.air);
		world.setBlock(i+9, j+5, k+2, Blocks.air);
		world.setBlock(i+9, j+5, k+3, Blocks.air);
		world.setBlock(i+9, j+5, k+4, Blocks.air);
		world.setBlock(i+9, j+5, k+5, Blocks.air);
		world.setBlock(i+9, j+5, k+6, Blocks.air);
		world.setBlock(i+9, j+5, k+7, Blocks.air);
		world.setBlock(i+9, j+5, k+8, Blocks.air);
		world.setBlock(i+9, j+5, k+9, Blocks.air);
		world.setBlock(i+9, j+5, k+10, Blocks.air);
		world.setBlock(i+9, j+5, k+11, Blocks.air);
		world.setBlock(i+9, j+5, k+12, Blocks.air);
		world.setBlock(i+10, j+0, k+0, Blocks.air);
		world.setBlock(i+10, j+0, k+1, Blocks.air);
		world.setBlock(i+10, j+0, k+2, Blocks.air);
		world.setBlock(i+10, j+0, k+3, Blocks.air);
		world.setBlock(i+10, j+0, k+4, sh, ms);
		world.setBlock(i+10, j+0, k+5, Blocks.air);
		world.setBlock(i+10, j+0, k+6, Blocks.air);
		world.setBlock(i+10, j+0, k+7, Blocks.air);
		world.setBlock(i+10, j+0, k+8, sh, ms);
		world.setBlock(i+10, j+0, k+9, Blocks.air);
		world.setBlock(i+10, j+0, k+10, Blocks.air);
		world.setBlock(i+10, j+0, k+11, Blocks.air);
		world.setBlock(i+10, j+0, k+12, Blocks.air);
		world.setBlock(i+10, j+1, k+0, Blocks.air);
		world.setBlock(i+10, j+1, k+1, Blocks.air);
		world.setBlock(i+10, j+1, k+2, Blocks.air);
		world.setBlock(i+10, j+1, k+3, Blocks.air);
		world.setBlock(i+10, j+1, k+4, sh, ms);
		world.setBlock(i+10, j+1, k+5, Blocks.air);
		world.setBlock(i+10, j+1, k+6, Blocks.air);
		world.setBlock(i+10, j+1, k+7, Blocks.air);
		world.setBlock(i+10, j+1, k+8, sh, ms);
		world.setBlock(i+10, j+1, k+9, Blocks.air);
		world.setBlock(i+10, j+1, k+10, Blocks.air);
		world.setBlock(i+10, j+1, k+11, Blocks.air);
		world.setBlock(i+10, j+1, k+12, Blocks.air);
		world.setBlock(i+10, j+2, k+0, Blocks.air);
		world.setBlock(i+10, j+2, k+1, Blocks.air);
		world.setBlock(i+10, j+2, k+2, Blocks.air);
		world.setBlock(i+10, j+2, k+3, Blocks.air);
		world.setBlock(i+10, j+2, k+4, sh, ms);
		world.setBlock(i+10, j+2, k+5, Blocks.air);
		world.setBlock(i+10, j+2, k+6, Blocks.air);
		world.setBlock(i+10, j+2, k+7, Blocks.air);
		world.setBlock(i+10, j+2, k+8, sh, ms);
		world.setBlock(i+10, j+2, k+9, Blocks.air);
		world.setBlock(i+10, j+2, k+10, Blocks.air);
		world.setBlock(i+10, j+2, k+11, Blocks.air);
		world.setBlock(i+10, j+2, k+12, Blocks.air);
		world.setBlock(i+10, j+3, k+0, Blocks.air);
		world.setBlock(i+10, j+3, k+1, Blocks.air);
		world.setBlock(i+10, j+3, k+2, Blocks.air);
		world.setBlock(i+10, j+3, k+3, Blocks.air);
		world.setBlock(i+10, j+3, k+4, b, 1);
		world.setBlock(i+10, j+3, k+5, sh, ms);
		world.setBlock(i+10, j+3, k+6, sh, ml);
		world.setBlock(i+10, j+3, k+7, sh, ms);
		world.setBlock(i+10, j+3, k+8, b, 1);
		world.setBlock(i+10, j+3, k+9, Blocks.air);
		world.setBlock(i+10, j+3, k+10, Blocks.air);
		world.setBlock(i+10, j+3, k+11, Blocks.air);
		world.setBlock(i+10, j+3, k+12, Blocks.air);
		world.setBlock(i+10, j+4, k+0, Blocks.air);
		world.setBlock(i+10, j+4, k+1, Blocks.air);
		world.setBlock(i+10, j+4, k+2, Blocks.air);
		world.setBlock(i+10, j+4, k+3, Blocks.air);
		world.setBlock(i+10, j+4, k+4, Blocks.air);
		world.setBlock(i+10, j+4, k+5, Blocks.air);
		world.setBlock(i+10, j+4, k+6, Blocks.air);
		world.setBlock(i+10, j+4, k+7, Blocks.air);
		world.setBlock(i+10, j+4, k+8, Blocks.air);
		world.setBlock(i+10, j+4, k+9, Blocks.air);
		world.setBlock(i+10, j+4, k+10, Blocks.air);
		world.setBlock(i+10, j+4, k+11, Blocks.air);
		world.setBlock(i+10, j+4, k+12, Blocks.air);
		world.setBlock(i+10, j+5, k+0, Blocks.air);
		world.setBlock(i+10, j+5, k+1, Blocks.air);
		world.setBlock(i+10, j+5, k+2, Blocks.air);
		world.setBlock(i+10, j+5, k+3, Blocks.air);
		world.setBlock(i+10, j+5, k+4, Blocks.air);
		world.setBlock(i+10, j+5, k+5, Blocks.air);
		world.setBlock(i+10, j+5, k+6, Blocks.air);
		world.setBlock(i+10, j+5, k+7, Blocks.air);
		world.setBlock(i+10, j+5, k+8, Blocks.air);
		world.setBlock(i+10, j+5, k+9, Blocks.air);
		world.setBlock(i+10, j+5, k+10, Blocks.air);
		world.setBlock(i+10, j+5, k+11, Blocks.air);
		world.setBlock(i+10, j+5, k+12, Blocks.air);
		world.setBlock(i+11, j+0, k+0, Blocks.air);
		world.setBlock(i+11, j+0, k+1, Blocks.air);
		world.setBlock(i+11, j+0, k+2, Blocks.air);
		world.setBlock(i+11, j+0, k+3, Blocks.air);
		world.setBlock(i+11, j+0, k+4, sh, ms);
		world.setBlock(i+11, j+0, k+5, Blocks.air);
		world.setBlock(i+11, j+0, k+6, Blocks.air);
		world.setBlock(i+11, j+0, k+7, Blocks.air);
		world.setBlock(i+11, j+0, k+8, sh, ms);
		world.setBlock(i+11, j+0, k+9, Blocks.air);
		world.setBlock(i+11, j+0, k+10, Blocks.air);
		world.setBlock(i+11, j+0, k+11, Blocks.air);
		world.setBlock(i+11, j+0, k+12, Blocks.air);
		world.setBlock(i+11, j+1, k+0, Blocks.air);
		world.setBlock(i+11, j+1, k+1, Blocks.air);
		world.setBlock(i+11, j+1, k+2, Blocks.air);
		world.setBlock(i+11, j+1, k+3, Blocks.air);
		world.setBlock(i+11, j+1, k+4, sh, ms);
		world.setBlock(i+11, j+1, k+5, Blocks.air);
		world.setBlock(i+11, j+1, k+6, Blocks.air);
		world.setBlock(i+11, j+1, k+7, Blocks.air);
		world.setBlock(i+11, j+1, k+8, sh, ms);
		world.setBlock(i+11, j+1, k+9, Blocks.air);
		world.setBlock(i+11, j+1, k+10, Blocks.air);
		world.setBlock(i+11, j+1, k+11, Blocks.air);
		world.setBlock(i+11, j+1, k+12, Blocks.air);
		world.setBlock(i+11, j+2, k+0, Blocks.air);
		world.setBlock(i+11, j+2, k+1, Blocks.air);
		world.setBlock(i+11, j+2, k+2, Blocks.air);
		world.setBlock(i+11, j+2, k+3, Blocks.air);
		world.setBlock(i+11, j+2, k+4, sh, ms);
		world.setBlock(i+11, j+2, k+5, Blocks.air);
		world.setBlock(i+11, j+2, k+6, Blocks.air);
		world.setBlock(i+11, j+2, k+7, Blocks.air);
		world.setBlock(i+11, j+2, k+8, sh, ms);
		world.setBlock(i+11, j+2, k+9, Blocks.air);
		world.setBlock(i+11, j+2, k+10, Blocks.air);
		world.setBlock(i+11, j+2, k+11, Blocks.air);
		world.setBlock(i+11, j+2, k+12, Blocks.air);
		world.setBlock(i+11, j+3, k+0, Blocks.air);
		world.setBlock(i+11, j+3, k+1, Blocks.air);
		world.setBlock(i+11, j+3, k+2, Blocks.air);
		world.setBlock(i+11, j+3, k+3, Blocks.air);
		world.setBlock(i+11, j+3, k+4, b, 1);
		world.setBlock(i+11, j+3, k+5, sh, ms);
		world.setBlock(i+11, j+3, k+6, sh, ms);
		world.setBlock(i+11, j+3, k+7, sh, ms);
		world.setBlock(i+11, j+3, k+8, b, 1);
		world.setBlock(i+11, j+3, k+9, Blocks.air);
		world.setBlock(i+11, j+3, k+10, Blocks.air);
		world.setBlock(i+11, j+3, k+11, Blocks.air);
		world.setBlock(i+11, j+3, k+12, Blocks.air);
		world.setBlock(i+11, j+4, k+0, Blocks.air);
		world.setBlock(i+11, j+4, k+1, Blocks.air);
		world.setBlock(i+11, j+4, k+2, Blocks.air);
		world.setBlock(i+11, j+4, k+3, Blocks.air);
		world.setBlock(i+11, j+4, k+4, Blocks.air);
		world.setBlock(i+11, j+4, k+5, Blocks.air);
		world.setBlock(i+11, j+4, k+6, Blocks.air);
		world.setBlock(i+11, j+4, k+7, Blocks.air);
		world.setBlock(i+11, j+4, k+8, Blocks.air);
		world.setBlock(i+11, j+4, k+9, Blocks.air);
		world.setBlock(i+11, j+4, k+10, Blocks.air);
		world.setBlock(i+11, j+4, k+11, Blocks.air);
		world.setBlock(i+11, j+4, k+12, Blocks.air);
		world.setBlock(i+11, j+5, k+0, Blocks.air);
		world.setBlock(i+11, j+5, k+1, Blocks.air);
		world.setBlock(i+11, j+5, k+2, Blocks.air);
		world.setBlock(i+11, j+5, k+3, Blocks.air);
		world.setBlock(i+11, j+5, k+4, Blocks.air);
		world.setBlock(i+11, j+5, k+5, Blocks.air);
		world.setBlock(i+11, j+5, k+6, Blocks.air);
		world.setBlock(i+11, j+5, k+7, Blocks.air);
		world.setBlock(i+11, j+5, k+8, Blocks.air);
		world.setBlock(i+11, j+5, k+9, Blocks.air);
		world.setBlock(i+11, j+5, k+10, Blocks.air);
		world.setBlock(i+11, j+5, k+11, Blocks.air);
		world.setBlock(i+11, j+5, k+12, Blocks.air);
		world.setBlock(i+12, j+0, k+0, b, 2);
		world.setBlock(i+12, j+0, k+1, Blocks.air);
		world.setBlock(i+12, j+0, k+2, Blocks.air);
		world.setBlock(i+12, j+0, k+3, Blocks.air);
		world.setBlock(i+12, j+0, k+4, b, 2);
		world.setBlock(i+12, j+0, k+5, Blocks.air);
		world.setBlock(i+12, j+0, k+6, Blocks.air);
		world.setBlock(i+12, j+0, k+7, Blocks.air);
		world.setBlock(i+12, j+0, k+8, b, 2);
		world.setBlock(i+12, j+0, k+9, Blocks.air);
		world.setBlock(i+12, j+0, k+10, Blocks.air);
		world.setBlock(i+12, j+0, k+11, Blocks.air);
		world.setBlock(i+12, j+0, k+12, b, 2);
		world.setBlock(i+12, j+1, k+0, sh, ml);
		world.setBlock(i+12, j+1, k+1, Blocks.air);
		world.setBlock(i+12, j+1, k+2, Blocks.air);
		world.setBlock(i+12, j+1, k+3, Blocks.air);
		world.setBlock(i+12, j+1, k+4, b, 2);
		world.setBlock(i+12, j+1, k+5, Blocks.air);
		world.setBlock(i+12, j+1, k+6, Blocks.air);
		world.setBlock(i+12, j+1, k+7, Blocks.air);
		world.setBlock(i+12, j+1, k+8, b, 2);
		world.setBlock(i+12, j+1, k+9, Blocks.air);
		world.setBlock(i+12, j+1, k+10, Blocks.air);
		world.setBlock(i+12, j+1, k+11, Blocks.air);
		world.setBlock(i+12, j+1, k+12, sh, ml);
		world.setBlock(i+12, j+2, k+0, Blocks.air);
		world.setBlock(i+12, j+2, k+1, Blocks.air);
		world.setBlock(i+12, j+2, k+2, Blocks.air);
		world.setBlock(i+12, j+2, k+3, Blocks.air);
		world.setBlock(i+12, j+2, k+4, b, 2);
		world.setBlock(i+12, j+2, k+5, Blocks.air);
		world.setBlock(i+12, j+2, k+6, Blocks.air);
		world.setBlock(i+12, j+2, k+7, Blocks.air);
		world.setBlock(i+12, j+2, k+8, b, 2);
		world.setBlock(i+12, j+2, k+9, Blocks.air);
		world.setBlock(i+12, j+2, k+10, Blocks.air);
		world.setBlock(i+12, j+2, k+11, Blocks.air);
		world.setBlock(i+12, j+2, k+12, Blocks.air);
		world.setBlock(i+12, j+3, k+0, Blocks.air);
		world.setBlock(i+12, j+3, k+1, Blocks.air);
		world.setBlock(i+12, j+3, k+2, Blocks.air);
		world.setBlock(i+12, j+3, k+3, Blocks.air);
		world.setBlock(i+12, j+3, k+4, b, 7);
		world.setBlock(i+12, j+3, k+5, b, 1);
		world.setBlock(i+12, j+3, k+6, b, 1);
		world.setBlock(i+12, j+3, k+7, b, 1);
		world.setBlock(i+12, j+3, k+8, b, 7);
		world.setBlock(i+12, j+3, k+9, Blocks.air);
		world.setBlock(i+12, j+3, k+10, Blocks.air);
		world.setBlock(i+12, j+3, k+11, Blocks.air);
		world.setBlock(i+12, j+3, k+12, Blocks.air);
		world.setBlock(i+12, j+4, k+0, Blocks.air);
		world.setBlock(i+12, j+4, k+1, Blocks.air);
		world.setBlock(i+12, j+4, k+2, Blocks.air);
		world.setBlock(i+12, j+4, k+3, Blocks.air);
		world.setBlock(i+12, j+4, k+4, Blocks.air);
		world.setBlock(i+12, j+4, k+5, Blocks.air);
		world.setBlock(i+12, j+4, k+6, Blocks.air);
		world.setBlock(i+12, j+4, k+7, Blocks.air);
		world.setBlock(i+12, j+4, k+8, Blocks.air);
		world.setBlock(i+12, j+4, k+9, Blocks.air);
		world.setBlock(i+12, j+4, k+10, Blocks.air);
		world.setBlock(i+12, j+4, k+11, Blocks.air);
		world.setBlock(i+12, j+4, k+12, Blocks.air);
		world.setBlock(i+12, j+5, k+0, Blocks.air);
		world.setBlock(i+12, j+5, k+1, Blocks.air);
		world.setBlock(i+12, j+5, k+2, Blocks.air);
		world.setBlock(i+12, j+5, k+3, Blocks.air);
		world.setBlock(i+12, j+5, k+4, Blocks.air);
		world.setBlock(i+12, j+5, k+5, Blocks.air);
		world.setBlock(i+12, j+5, k+6, Blocks.air);
		world.setBlock(i+12, j+5, k+7, Blocks.air);
		world.setBlock(i+12, j+5, k+8, Blocks.air);
		world.setBlock(i+12, j+5, k+9, Blocks.air);
		world.setBlock(i+12, j+5, k+10, Blocks.air);
		world.setBlock(i+12, j+5, k+11, Blocks.air);
		world.setBlock(i+12, j+5, k+12, Blocks.air);
	}

}
