package Reika.ChromatiCraft.Auxiliary.Structure;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;

import Reika.ChromatiCraft.Base.ChromaStructureBase;
import Reika.ChromatiCraft.Block.BlockPylonStructure.StoneTypes;
import Reika.ChromatiCraft.Block.Dimension.BlockDimensionDeco.DimDecoTypes;
import Reika.ChromatiCraft.Registry.ChromaBlocks;
import Reika.ChromatiCraft.Registry.ChromaTiles;
import Reika.ChromatiCraft.TileEntity.Networking.TileEntityCrystalBroadcaster;
import Reika.DragonAPI.Instantiable.Data.BlockStruct.FilledBlockArray;


public class BroadcasterStructure extends ChromaStructureBase {

	private static final int x0 = 6;
	private static final int y0 = 23;
	private static final int z0 = 6;

	private int potentialGlass;

	@Override
	public void resetToDefaults() {
		super.resetToDefaults();
		potentialGlass = 0;
	}

	@Override
	public FilledBlockArray getArray(World world, int x, int y, int z) {
		FilledBlockArray array = new FilledBlockArray(world);

		x -= 6;
		y -= 23;
		z -= 6;

		array.setBlock(x+0, y+3, z+5, crystalstone, 10);
		array.setBlock(x+0, y+3, z+6, crystalstone, 10);
		array.setBlock(x+0, y+3, z+7, crystalstone, 10);
		array.setBlock(x+1, y+3, z+5, crystalstone, 10);
		array.setBlock(x+1, y+3, z+6, crystalstone, 10);
		array.setBlock(x+1, y+3, z+7, crystalstone, 10);
		array.setBlock(x+2, y+3, z+4, crystalstone, 0);
		array.setBlock(x+2, y+3, z+5, crystalstone, 10);
		array.setBlock(x+2, y+3, z+6, crystalstone, 10);
		array.setBlock(x+2, y+3, z+7, crystalstone, 10);
		array.setBlock(x+2, y+3, z+8, crystalstone, 0);
		array.setBlock(x+3, y+2, z+5, crystalstone, 0);
		array.setBlock(x+3, y+2, z+6, crystalstone, 0);
		array.setBlock(x+3, y+2, z+7, crystalstone, 0);
		array.setBlock(x+3, y+3, z+3, crystalstone, 0);
		array.setBlock(x+3, y+3, z+4, crystalstone, 0);
		array.setBlock(x+3, y+3, z+5, crystalstone, 10);
		array.setBlock(x+3, y+3, z+6, crystalstone, 10);
		array.setBlock(x+3, y+3, z+7, crystalstone, 10);
		array.setBlock(x+3, y+3, z+8, crystalstone, 0);
		array.setBlock(x+3, y+3, z+9, crystalstone, 0);
		array.setBlock(x+3, y+4, z+4, crystalstone, 0);
		array.setBlock(x+3, y+4, z+8, crystalstone, 0);
		array.setBlock(x+3, y+5, z+4, crystalstone, 2);
		array.setBlock(x+3, y+5, z+8, crystalstone, 2);
		array.setBlock(x+3, y+6, z+4, crystalstone, 2);
		array.setBlock(x+3, y+6, z+8, crystalstone, 2);
		array.setBlock(x+3, y+7, z+4, crystalstone, 2);
		array.setBlock(x+3, y+7, z+8, crystalstone, 2);
		array.setBlock(x+3, y+8, z+4, crystalstone, 12);
		array.setBlock(x+3, y+8, z+5, crystalstone, 12);
		array.setBlock(x+3, y+8, z+6, crystalstone, 12);
		array.setBlock(x+3, y+8, z+7, crystalstone, 12);
		array.setBlock(x+3, y+8, z+8, crystalstone, 12);
		array.setBlock(x+3, y+9, z+4, crystalstone, 6);
		array.setBlock(x+3, y+9, z+5, crystalstone, 12);
		array.setBlock(x+3, y+9, z+6, crystalstone, 0);
		array.setBlock(x+3, y+9, z+7, crystalstone, 12);
		array.setBlock(x+3, y+9, z+8, crystalstone, 6);
		array.setBlock(x+3, y+10, z+5, crystalstone, 2);
		array.setBlock(x+3, y+10, z+6, crystalstone, 0);
		array.setBlock(x+3, y+10, z+7, crystalstone, 2);
		array.setBlock(x+3, y+11, z+5, crystalstone, 2);
		array.setBlock(x+3, y+11, z+6, crystalstone, 13);
		array.setBlock(x+3, y+11, z+7, crystalstone, 2);
		array.setBlock(x+3, y+12, z+5, crystalstone, 6);
		array.setBlock(x+3, y+12, z+6, crystalstone, 12);
		array.setBlock(x+3, y+12, z+7, crystalstone, 6);
		array.setBlock(x+3, y+13, z+6, crystalstone, 2);
		array.setBlock(x+3, y+14, z+6, crystalstone, 8);
		array.setBlock(x+4, y+1, z+5, crystalstone, 0);
		array.setBlock(x+4, y+1, z+6, crystalstone, 0);
		array.setBlock(x+4, y+1, z+7, crystalstone, 0);
		array.setBlock(x+4, y+2, z+4, crystalstone, 0);
		array.setBlock(x+4, y+2, z+5, crystalstone, 0);
		array.setBlock(x+4, y+2, z+6, crystalstone, 0);
		array.setBlock(x+4, y+2, z+7, crystalstone, 0);
		array.setBlock(x+4, y+2, z+8, crystalstone, 0);
		array.setBlock(x+4, y+3, z+2, crystalstone, 0);
		array.setBlock(x+4, y+3, z+3, crystalstone, 0);
		array.setBlock(x+4, y+3, z+4, crystalstone, 0);
		array.setBlock(x+4, y+3, z+5, crystalstone, 0);
		array.setBlock(x+4, y+3, z+6, crystalstone, 0);
		array.setBlock(x+4, y+3, z+7, crystalstone, 0);
		array.setBlock(x+4, y+3, z+8, crystalstone, 0);
		array.setBlock(x+4, y+3, z+9, crystalstone, 0);
		array.setBlock(x+4, y+3, z+10, crystalstone, 0);
		array.setBlock(x+4, y+4, z+3, crystalstone, 0);
		array.setBlock(x+4, y+4, z+4, crystalstone, 0);
		array.setBlock(x+4, y+4, z+5, crystalstone, 1);
		array.setBlock(x+4, y+4, z+6, crystalstone, 1);
		array.setBlock(x+4, y+4, z+7, crystalstone, 1);
		array.setBlock(x+4, y+4, z+8, crystalstone, 0);
		array.setBlock(x+4, y+4, z+9, crystalstone, 0);
		array.setBlock(x+4, y+5, z+3, crystalstone, 2);
		array.setBlock(x+4, y+5, z+4, crystalstone, 0);
		array.setBlock(x+4, y+5, z+8, crystalstone, 0);
		array.setBlock(x+4, y+5, z+9, crystalstone, 2);
		array.setBlock(x+4, y+6, z+3, crystalstone, 2);
		array.setBlock(x+4, y+6, z+4, crystalstone, 0);
		array.setBlock(x+4, y+6, z+8, crystalstone, 0);
		array.setBlock(x+4, y+6, z+9, crystalstone, 2);
		array.setBlock(x+4, y+7, z+3, crystalstone, 2);
		array.setBlock(x+4, y+7, z+4, crystalstone, 0);
		array.setBlock(x+4, y+7, z+5, crystalstone, 1);
		array.setBlock(x+4, y+7, z+6, crystalstone, 1);
		array.setBlock(x+4, y+7, z+7, crystalstone, 1);
		array.setBlock(x+4, y+7, z+8, crystalstone, 0);
		array.setBlock(x+4, y+7, z+9, crystalstone, 2);
		array.setBlock(x+4, y+8, z+3, crystalstone, 12);
		array.setBlock(x+4, y+8, z+4, crystalstone, 0);
		array.setBlock(x+4, y+8, z+5, crystalstone, 0);
		array.setBlock(x+4, y+8, z+6, crystalstone, 0);
		array.setBlock(x+4, y+8, z+7, crystalstone, 0);
		array.setBlock(x+4, y+8, z+8, crystalstone, 0);
		array.setBlock(x+4, y+8, z+9, crystalstone, 12);
		array.setBlock(x+4, y+9, z+3, crystalstone, 6);
		array.setBlock(x+4, y+9, z+4, crystalstone, 0);
		array.setBlock(x+4, y+9, z+5, crystalstone, 0);
		array.setBlock(x+4, y+9, z+6, crystalstone, 0);
		array.setBlock(x+4, y+9, z+7, crystalstone, 0);
		array.setBlock(x+4, y+9, z+8, crystalstone, 0);
		array.setBlock(x+4, y+9, z+9, crystalstone, 6);
		array.setBlock(x+4, y+10, z+4, crystalstone, 2);
		array.setBlock(x+4, y+10, z+5, crystalstone, 0);
		array.setBlock(x+4, y+10, z+6, crystalstone, 0);
		array.setBlock(x+4, y+10, z+7, crystalstone, 0);
		array.setBlock(x+4, y+10, z+8, crystalstone, 2);
		array.setBlock(x+4, y+11, z+4, crystalstone, 2);
		array.setBlock(x+4, y+11, z+5, crystalstone, 0);
		array.setBlock(x+4, y+11, z+6, crystalstone, 0);
		array.setBlock(x+4, y+11, z+7, crystalstone, 0);
		array.setBlock(x+4, y+11, z+8, crystalstone, 2);
		array.setBlock(x+4, y+12, z+4, crystalstone, 2);
		array.setBlock(x+4, y+12, z+5, crystalstone, 0);
		array.setBlock(x+4, y+12, z+6, crystalstone, 0);
		array.setBlock(x+4, y+12, z+7, crystalstone, 0);
		array.setBlock(x+4, y+12, z+8, crystalstone, 2);
		array.setBlock(x+4, y+13, z+4, crystalstone, 2);
		array.setBlock(x+4, y+13, z+5, crystalstone, 0);
		array.setBlock(x+4, y+13, z+6, crystalstone, 0);
		array.setBlock(x+4, y+13, z+7, crystalstone, 0);
		array.setBlock(x+4, y+13, z+8, crystalstone, 2);
		array.setBlock(x+4, y+14, z+4, crystalstone, 2);
		array.setBlock(x+4, y+14, z+5, crystalstone, 0);
		array.setBlock(x+4, y+14, z+6, crystalstone, 0);
		array.setBlock(x+4, y+14, z+7, crystalstone, 0);
		array.setBlock(x+4, y+14, z+8, crystalstone, 2);
		array.setBlock(x+4, y+15, z+4, crystalstone, 6);
		array.setBlock(x+4, y+15, z+5, crystalstone, 12);
		array.setBlock(x+4, y+15, z+6, crystalstone, 12);
		array.setBlock(x+4, y+15, z+7, crystalstone, 12);
		array.setBlock(x+4, y+15, z+8, crystalstone, 6);
		array.setBlock(x+4, y+16, z+5, crystalstone, 2);
		array.setBlock(x+4, y+16, z+6, crystalstone, 0);
		array.setBlock(x+4, y+16, z+7, crystalstone, 2);
		array.setBlock(x+4, y+17, z+5, crystalstone, 2);
		array.setBlock(x+4, y+17, z+6, crystalstone, 14);
		array.setBlock(x+4, y+17, z+7, crystalstone, 2);
		array.setBlock(x+4, y+18, z+5, crystalstone, 6);
		array.setBlock(x+4, y+18, z+6, crystalstone, 12);
		array.setBlock(x+4, y+18, z+7, crystalstone, 6);
		array.setBlock(x+4, y+19, z+6, crystalstone, 2);
		array.setBlock(x+4, y+20, z+6, crystalstone, 7);
		array.setBlock(x+5, y+0, z+5, crystalstone, 0);
		array.setBlock(x+5, y+0, z+6, crystalstone, 0);
		array.setBlock(x+5, y+0, z+7, crystalstone, 0);
		array.setBlock(x+5, y+1, z+4, crystalstone, 0);
		array.setBlock(x+5, y+1, z+5, crystalstone, 0);
		array.setBlock(x+5, y+1, z+6, crystalstone, 0);
		array.setBlock(x+5, y+1, z+7, crystalstone, 0);
		array.setBlock(x+5, y+1, z+8, crystalstone, 0);
		array.setBlock(x+5, y+2, z+3, crystalstone, 0);
		array.setBlock(x+5, y+2, z+4, crystalstone, 0);
		array.setBlock(x+5, y+2, z+5, crystalstone, 0);
		array.setBlock(x+5, y+2, z+6, crystalstone, 0);
		array.setBlock(x+5, y+2, z+7, crystalstone, 0);
		array.setBlock(x+5, y+2, z+8, crystalstone, 0);
		array.setBlock(x+5, y+2, z+9, crystalstone, 0);
		array.setBlock(x+5, y+3, z+0, crystalstone, 11);
		array.setBlock(x+5, y+3, z+1, crystalstone, 11);
		array.setBlock(x+5, y+3, z+2, crystalstone, 11);
		array.setBlock(x+5, y+3, z+3, crystalstone, 11);
		array.setBlock(x+5, y+3, z+4, crystalstone, 0);
		array.setBlock(x+5, y+3, z+5, crystalstone, 0);
		array.setBlock(x+5, y+3, z+6, crystalstone, 0);
		array.setBlock(x+5, y+3, z+7, crystalstone, 0);
		array.setBlock(x+5, y+3, z+8, crystalstone, 0);
		array.setBlock(x+5, y+3, z+9, crystalstone, 11);
		array.setBlock(x+5, y+3, z+10, crystalstone, 11);
		array.setBlock(x+5, y+3, z+11, crystalstone, 11);
		array.setBlock(x+5, y+3, z+12, crystalstone, 11);
		array.setBlock(x+5, y+4, z+4, crystalstone, 1);
		array.setBlock(x+5, y+4, z+5, crystalstone, 0);
		array.setBlock(x+5, y+4, z+6, crystalstone, 0);
		array.setBlock(x+5, y+4, z+7, crystalstone, 0);
		array.setBlock(x+5, y+4, z+8, crystalstone, 1);
		array.setBlock(x+5, y+5, z+5, crystalstone, 0);
		array.setBlock(x+5, y+5, z+6, crystalstone, 0);
		array.setBlock(x+5, y+5, z+7, crystalstone, 0);
		array.setBlock(x+5, y+6, z+5, crystalstone, 0);
		array.setBlock(x+5, y+6, z+7, crystalstone, 0);
		array.setBlock(x+5, y+7, z+4, crystalstone, 1);
		array.setBlock(x+5, y+7, z+5, crystalstone, 0);
		array.setBlock(x+5, y+7, z+6, crystalstone, 0);
		array.setBlock(x+5, y+7, z+7, crystalstone, 0);
		array.setBlock(x+5, y+7, z+8, crystalstone, 1);
		array.setBlock(x+5, y+8, z+3, crystalstone, 12);
		array.setBlock(x+5, y+8, z+4, crystalstone, 0);
		array.setBlock(x+5, y+8, z+5, crystalstone, 0);
		array.setBlock(x+5, y+8, z+6, crystalstone, 0);
		array.setBlock(x+5, y+8, z+7, crystalstone, 0);
		array.setBlock(x+5, y+8, z+8, crystalstone, 0);
		array.setBlock(x+5, y+8, z+9, crystalstone, 12);
		array.setBlock(x+5, y+9, z+3, crystalstone, 12);
		array.setBlock(x+5, y+9, z+4, crystalstone, 0);
		array.setBlock(x+5, y+9, z+5, crystalstone, 0);
		array.setBlock(x+5, y+9, z+6, crystalstone, 0);
		array.setBlock(x+5, y+9, z+7, crystalstone, 0);
		array.setBlock(x+5, y+9, z+8, crystalstone, 0);
		array.setBlock(x+5, y+9, z+9, crystalstone, 12);
		array.setBlock(x+5, y+10, z+3, crystalstone, 2);
		array.setBlock(x+5, y+10, z+4, crystalstone, 0);
		array.setBlock(x+5, y+10, z+5, crystalstone, 0);
		array.setBlock(x+5, y+10, z+6, crystalstone, 0);
		array.setBlock(x+5, y+10, z+7, crystalstone, 0);
		array.setBlock(x+5, y+10, z+8, crystalstone, 0);
		array.setBlock(x+5, y+10, z+9, crystalstone, 2);
		array.setBlock(x+5, y+11, z+3, crystalstone, 2);
		array.setBlock(x+5, y+11, z+4, crystalstone, 0);
		array.setBlock(x+5, y+11, z+5, crystalstone, 0);
		array.setBlock(x+5, y+11, z+6, crystalstone, 0);
		array.setBlock(x+5, y+11, z+7, crystalstone, 0);
		array.setBlock(x+5, y+11, z+8, crystalstone, 0);
		array.setBlock(x+5, y+11, z+9, crystalstone, 2);
		array.setBlock(x+5, y+12, z+3, crystalstone, 6);
		array.setBlock(x+5, y+12, z+4, crystalstone, 0);
		array.setBlock(x+5, y+12, z+5, crystalstone, 0);
		array.setBlock(x+5, y+12, z+6, crystalstone, 0);
		array.setBlock(x+5, y+12, z+7, crystalstone, 0);
		array.setBlock(x+5, y+12, z+8, crystalstone, 0);
		array.setBlock(x+5, y+12, z+9, crystalstone, 6);
		array.setBlock(x+5, y+13, z+4, crystalstone, 0);
		array.setBlock(x+5, y+13, z+5, crystalstone, 0);
		array.setBlock(x+5, y+13, z+6, crystalstone, 0);
		array.setBlock(x+5, y+13, z+7, crystalstone, 0);
		array.setBlock(x+5, y+13, z+8, crystalstone, 0);
		array.setBlock(x+5, y+14, z+4, crystalstone, 0);
		array.setBlock(x+5, y+14, z+5, crystalstone, 0);
		array.setBlock(x+5, y+14, z+6, crystalstone, 0);
		array.setBlock(x+5, y+14, z+7, crystalstone, 0);
		array.setBlock(x+5, y+14, z+8, crystalstone, 0);
		array.setBlock(x+5, y+15, z+4, crystalstone, 12);
		array.setBlock(x+5, y+15, z+5, crystalstone, 0);
		array.setBlock(x+5, y+15, z+6, crystalstone, 0);
		array.setBlock(x+5, y+15, z+7, crystalstone, 0);
		array.setBlock(x+5, y+15, z+8, crystalstone, 12);
		array.setBlock(x+5, y+16, z+4, crystalstone, 2);
		array.setBlock(x+5, y+16, z+5, crystalstone, 0);
		array.setBlock(x+5, y+16, z+6, crystalstone, 0);
		array.setBlock(x+5, y+16, z+7, crystalstone, 0);
		array.setBlock(x+5, y+16, z+8, crystalstone, 2);
		array.setBlock(x+5, y+17, z+4, crystalstone, 2);
		array.setBlock(x+5, y+17, z+5, crystalstone, 0);
		array.setBlock(x+5, y+17, z+6, crystalstone, 0);
		array.setBlock(x+5, y+17, z+7, crystalstone, 0);
		array.setBlock(x+5, y+17, z+8, crystalstone, 2);
		array.setBlock(x+5, y+18, z+4, crystalstone, 6);
		array.setBlock(x+5, y+18, z+5, crystalstone, 0);
		array.setBlock(x+5, y+18, z+6, crystalstone, 0);
		array.setBlock(x+5, y+18, z+7, crystalstone, 0);
		array.setBlock(x+5, y+18, z+8, crystalstone, 6);
		array.setBlock(x+5, y+19, z+5, crystalstone, 2);
		array.setBlock(x+5, y+19, z+6, crystalstone, 0);
		array.setBlock(x+5, y+19, z+7, crystalstone, 2);
		array.setBlock(x+5, y+20, z+5, crystalstone, 2);
		array.setBlock(x+5, y+20, z+6, crystalstone, 0);
		array.setBlock(x+5, y+20, z+7, crystalstone, 2);
		array.setBlock(x+5, y+21, z+5, crystalstone, 2);
		array.setBlock(x+5, y+21, z+6, crystalstone, 0);
		array.setBlock(x+5, y+21, z+7, crystalstone, 2);
		array.setBlock(x+5, y+22, z+5, crystalstone, 2);
		array.setBlock(x+5, y+22, z+6, crystalstone, 12);
		array.setBlock(x+5, y+22, z+7, crystalstone, 2);
		array.setBlock(x+5, y+23, z+5, crystalstone, 2);
		array.setBlock(x+5, y+23, z+7, crystalstone, 2);
		array.setBlock(x+5, y+24, z+5, crystalstone, 15);
		array.setBlock(x+5, y+24, z+6, crystalstone, 15);
		array.setBlock(x+5, y+24, z+7, crystalstone, 15);
		array.setBlock(x+5, y+25, z+6, crystalstone, 0);
		array.setBlock(x+6, y+0, z+5, crystalstone, 0);
		array.setBlock(x+6, y+0, z+7, crystalstone, 0);
		array.setBlock(x+6, y+1, z+4, crystalstone, 0);
		array.setBlock(x+6, y+1, z+5, crystalstone, 0);
		array.setBlock(x+6, y+1, z+7, crystalstone, 0);
		array.setBlock(x+6, y+1, z+8, crystalstone, 0);
		array.setBlock(x+6, y+2, z+3, crystalstone, 0);
		array.setBlock(x+6, y+2, z+4, crystalstone, 0);
		array.setBlock(x+6, y+2, z+5, crystalstone, 0);
		array.setBlock(x+6, y+2, z+7, crystalstone, 0);
		array.setBlock(x+6, y+2, z+8, crystalstone, 0);
		array.setBlock(x+6, y+2, z+9, crystalstone, 0);
		array.setBlock(x+6, y+3, z+0, crystalstone, 11);
		array.setBlock(x+6, y+3, z+1, crystalstone, 11);
		array.setBlock(x+6, y+3, z+2, crystalstone, 11);
		array.setBlock(x+6, y+3, z+3, crystalstone, 11);
		array.setBlock(x+6, y+3, z+4, crystalstone, 0);
		array.setBlock(x+6, y+3, z+5, crystalstone, 0);
		array.setBlock(x+6, y+3, z+7, crystalstone, 0);
		array.setBlock(x+6, y+3, z+8, crystalstone, 0);
		array.setBlock(x+6, y+3, z+9, crystalstone, 11);
		array.setBlock(x+6, y+3, z+10, crystalstone, 11);
		array.setBlock(x+6, y+3, z+11, crystalstone, 11);
		array.setBlock(x+6, y+3, z+12, crystalstone, 11);
		array.setBlock(x+6, y+4, z+4, crystalstone, 1);
		array.setBlock(x+6, y+4, z+5, crystalstone, 0);
		array.setBlock(x+6, y+4, z+7, crystalstone, 0);
		array.setBlock(x+6, y+4, z+8, crystalstone, 1);
		array.setBlock(x+6, y+5, z+5, crystalstone, 0);
		array.setBlock(x+6, y+5, z+7, crystalstone, 0);
		array.setBlock(x+6, y+7, z+4, crystalstone, 1);
		array.setBlock(x+6, y+7, z+5, crystalstone, 0);
		array.setBlock(x+6, y+7, z+7, crystalstone, 0);
		array.setBlock(x+6, y+7, z+8, crystalstone, 1);
		array.setBlock(x+6, y+8, z+3, crystalstone, 12);
		array.setBlock(x+6, y+8, z+4, crystalstone, 0);
		array.setBlock(x+6, y+8, z+5, crystalstone, 0);
		array.setBlock(x+6, y+8, z+7, crystalstone, 0);
		array.setBlock(x+6, y+8, z+8, crystalstone, 0);
		array.setBlock(x+6, y+8, z+9, crystalstone, 12);
		array.setBlock(x+6, y+9, z+3, crystalstone, 0);
		array.setBlock(x+6, y+9, z+4, crystalstone, 0);
		array.setBlock(x+6, y+9, z+5, crystalstone, 0);
		array.setBlock(x+6, y+9, z+7, crystalstone, 0);
		array.setBlock(x+6, y+9, z+8, crystalstone, 0);
		array.setBlock(x+6, y+9, z+9, crystalstone, 0);
		array.setBlock(x+6, y+10, z+3, crystalstone, 0);
		array.setBlock(x+6, y+10, z+4, crystalstone, 0);
		array.setBlock(x+6, y+10, z+5, crystalstone, 0);
		array.setBlock(x+6, y+10, z+7, crystalstone, 0);
		array.setBlock(x+6, y+10, z+8, crystalstone, 0);
		array.setBlock(x+6, y+10, z+9, crystalstone, 0);
		array.setBlock(x+6, y+11, z+3, crystalstone, 13);
		array.setBlock(x+6, y+11, z+4, crystalstone, 0);
		array.setBlock(x+6, y+11, z+5, crystalstone, 0);
		array.setBlock(x+6, y+11, z+7, crystalstone, 0);
		array.setBlock(x+6, y+11, z+8, crystalstone, 0);
		array.setBlock(x+6, y+11, z+9, crystalstone, 13);
		array.setBlock(x+6, y+12, z+3, crystalstone, 12);
		array.setBlock(x+6, y+12, z+4, crystalstone, 0);
		array.setBlock(x+6, y+12, z+5, crystalstone, 0);
		array.setBlock(x+6, y+12, z+7, crystalstone, 0);
		array.setBlock(x+6, y+12, z+8, crystalstone, 0);
		array.setBlock(x+6, y+12, z+9, crystalstone, 12);
		array.setBlock(x+6, y+13, z+3, crystalstone, 2);
		array.setBlock(x+6, y+13, z+4, crystalstone, 0);
		array.setBlock(x+6, y+13, z+5, crystalstone, 0);
		array.setBlock(x+6, y+13, z+7, crystalstone, 0);
		array.setBlock(x+6, y+13, z+8, crystalstone, 0);
		array.setBlock(x+6, y+13, z+9, crystalstone, 2);
		array.setBlock(x+6, y+14, z+3, crystalstone, 8);
		array.setBlock(x+6, y+14, z+4, crystalstone, 0);
		array.setBlock(x+6, y+14, z+5, crystalstone, 0);
		array.setBlock(x+6, y+14, z+7, crystalstone, 0);
		array.setBlock(x+6, y+14, z+8, crystalstone, 0);
		array.setBlock(x+6, y+14, z+9, crystalstone, 8);
		array.setBlock(x+6, y+15, z+4, crystalstone, 12);
		array.setBlock(x+6, y+15, z+5, crystalstone, 0);
		array.setBlock(x+6, y+15, z+7, crystalstone, 0);
		array.setBlock(x+6, y+15, z+8, crystalstone, 12);
		array.setBlock(x+6, y+16, z+4, crystalstone, 0);
		array.setBlock(x+6, y+16, z+5, crystalstone, 0);
		array.setBlock(x+6, y+16, z+7, crystalstone, 0);
		array.setBlock(x+6, y+16, z+8, crystalstone, 0);
		array.setBlock(x+6, y+17, z+4, crystalstone, 14);
		array.setBlock(x+6, y+17, z+5, crystalstone, 0);
		array.setBlock(x+6, y+17, z+7, crystalstone, 0);
		array.setBlock(x+6, y+17, z+8, crystalstone, 14);
		array.setBlock(x+6, y+18, z+4, crystalstone, 12);
		array.setBlock(x+6, y+18, z+5, crystalstone, 0);
		array.setBlock(x+6, y+18, z+7, crystalstone, 0);
		array.setBlock(x+6, y+18, z+8, crystalstone, 12);
		array.setBlock(x+6, y+19, z+4, crystalstone, 2);
		array.setBlock(x+6, y+19, z+5, crystalstone, 0);
		array.setBlock(x+6, y+19, z+7, crystalstone, 0);
		array.setBlock(x+6, y+19, z+8, crystalstone, 2);
		array.setBlock(x+6, y+20, z+4, crystalstone, 7);
		array.setBlock(x+6, y+20, z+5, crystalstone, 0);
		array.setBlock(x+6, y+20, z+7, crystalstone, 0);
		array.setBlock(x+6, y+20, z+8, crystalstone, 7);
		array.setBlock(x+6, y+21, z+5, crystalstone, 0);
		array.setBlock(x+6, y+21, z+7, crystalstone, 0);
		array.setBlock(x+6, y+22, z+5, crystalstone, 12);
		array.setBlock(x+6, y+22, z+7, crystalstone, 12);
		array.setBlock(x+6, y+24, z+5, crystalstone, 15);
		array.setBlock(x+6, y+24, z+7, crystalstone, 15);
		array.setBlock(x+6, y+25, z+5, crystalstone, 0);
		array.setBlock(x+6, y+25, z+7, crystalstone, 0);
		array.setBlock(x+7, y+0, z+5, crystalstone, 0);
		array.setBlock(x+7, y+0, z+6, crystalstone, 0);
		array.setBlock(x+7, y+0, z+7, crystalstone, 0);
		array.setBlock(x+7, y+1, z+4, crystalstone, 0);
		array.setBlock(x+7, y+1, z+5, crystalstone, 0);
		array.setBlock(x+7, y+1, z+6, crystalstone, 0);
		array.setBlock(x+7, y+1, z+7, crystalstone, 0);
		array.setBlock(x+7, y+1, z+8, crystalstone, 0);
		array.setBlock(x+7, y+2, z+3, crystalstone, 0);
		array.setBlock(x+7, y+2, z+4, crystalstone, 0);
		array.setBlock(x+7, y+2, z+5, crystalstone, 0);
		array.setBlock(x+7, y+2, z+6, crystalstone, 0);
		array.setBlock(x+7, y+2, z+7, crystalstone, 0);
		array.setBlock(x+7, y+2, z+8, crystalstone, 0);
		array.setBlock(x+7, y+2, z+9, crystalstone, 0);
		array.setBlock(x+7, y+3, z+0, crystalstone, 11);
		array.setBlock(x+7, y+3, z+1, crystalstone, 11);
		array.setBlock(x+7, y+3, z+2, crystalstone, 11);
		array.setBlock(x+7, y+3, z+3, crystalstone, 11);
		array.setBlock(x+7, y+3, z+4, crystalstone, 0);
		array.setBlock(x+7, y+3, z+5, crystalstone, 0);
		array.setBlock(x+7, y+3, z+6, crystalstone, 0);
		array.setBlock(x+7, y+3, z+7, crystalstone, 0);
		array.setBlock(x+7, y+3, z+8, crystalstone, 0);
		array.setBlock(x+7, y+3, z+9, crystalstone, 11);
		array.setBlock(x+7, y+3, z+10, crystalstone, 11);
		array.setBlock(x+7, y+3, z+11, crystalstone, 11);
		array.setBlock(x+7, y+3, z+12, crystalstone, 11);
		array.setBlock(x+7, y+4, z+4, crystalstone, 1);
		array.setBlock(x+7, y+4, z+5, crystalstone, 0);
		array.setBlock(x+7, y+4, z+6, crystalstone, 0);
		array.setBlock(x+7, y+4, z+7, crystalstone, 0);
		array.setBlock(x+7, y+4, z+8, crystalstone, 1);
		array.setBlock(x+7, y+5, z+5, crystalstone, 0);
		array.setBlock(x+7, y+5, z+6, crystalstone, 0);
		array.setBlock(x+7, y+5, z+7, crystalstone, 0);
		array.setBlock(x+7, y+6, z+5, crystalstone, 0);
		array.setBlock(x+7, y+6, z+7, crystalstone, 0);
		array.setBlock(x+7, y+7, z+4, crystalstone, 1);
		array.setBlock(x+7, y+7, z+5, crystalstone, 0);
		array.setBlock(x+7, y+7, z+6, crystalstone, 0);
		array.setBlock(x+7, y+7, z+7, crystalstone, 0);
		array.setBlock(x+7, y+7, z+8, crystalstone, 1);
		array.setBlock(x+7, y+8, z+3, crystalstone, 12);
		array.setBlock(x+7, y+8, z+4, crystalstone, 0);
		array.setBlock(x+7, y+8, z+5, crystalstone, 0);
		array.setBlock(x+7, y+8, z+6, crystalstone, 0);
		array.setBlock(x+7, y+8, z+7, crystalstone, 0);
		array.setBlock(x+7, y+8, z+8, crystalstone, 0);
		array.setBlock(x+7, y+8, z+9, crystalstone, 12);
		array.setBlock(x+7, y+9, z+3, crystalstone, 12);
		array.setBlock(x+7, y+9, z+4, crystalstone, 0);
		array.setBlock(x+7, y+9, z+5, crystalstone, 0);
		array.setBlock(x+7, y+9, z+6, crystalstone, 0);
		array.setBlock(x+7, y+9, z+7, crystalstone, 0);
		array.setBlock(x+7, y+9, z+8, crystalstone, 0);
		array.setBlock(x+7, y+9, z+9, crystalstone, 12);
		array.setBlock(x+7, y+10, z+3, crystalstone, 2);
		array.setBlock(x+7, y+10, z+4, crystalstone, 0);
		array.setBlock(x+7, y+10, z+5, crystalstone, 0);
		array.setBlock(x+7, y+10, z+6, crystalstone, 0);
		array.setBlock(x+7, y+10, z+7, crystalstone, 0);
		array.setBlock(x+7, y+10, z+8, crystalstone, 0);
		array.setBlock(x+7, y+10, z+9, crystalstone, 2);
		array.setBlock(x+7, y+11, z+3, crystalstone, 2);
		array.setBlock(x+7, y+11, z+4, crystalstone, 0);
		array.setBlock(x+7, y+11, z+5, crystalstone, 0);
		array.setBlock(x+7, y+11, z+6, crystalstone, 0);
		array.setBlock(x+7, y+11, z+7, crystalstone, 0);
		array.setBlock(x+7, y+11, z+8, crystalstone, 0);
		array.setBlock(x+7, y+11, z+9, crystalstone, 2);
		array.setBlock(x+7, y+12, z+3, crystalstone, 6);
		array.setBlock(x+7, y+12, z+4, crystalstone, 0);
		array.setBlock(x+7, y+12, z+5, crystalstone, 0);
		array.setBlock(x+7, y+12, z+6, crystalstone, 0);
		array.setBlock(x+7, y+12, z+7, crystalstone, 0);
		array.setBlock(x+7, y+12, z+8, crystalstone, 0);
		array.setBlock(x+7, y+12, z+9, crystalstone, 6);
		array.setBlock(x+7, y+13, z+4, crystalstone, 0);
		array.setBlock(x+7, y+13, z+5, crystalstone, 0);
		array.setBlock(x+7, y+13, z+6, crystalstone, 0);
		array.setBlock(x+7, y+13, z+7, crystalstone, 0);
		array.setBlock(x+7, y+13, z+8, crystalstone, 0);
		array.setBlock(x+7, y+14, z+4, crystalstone, 0);
		array.setBlock(x+7, y+14, z+5, crystalstone, 0);
		array.setBlock(x+7, y+14, z+6, crystalstone, 0);
		array.setBlock(x+7, y+14, z+7, crystalstone, 0);
		array.setBlock(x+7, y+14, z+8, crystalstone, 0);
		array.setBlock(x+7, y+15, z+4, crystalstone, 12);
		array.setBlock(x+7, y+15, z+5, crystalstone, 0);
		array.setBlock(x+7, y+15, z+6, crystalstone, 0);
		array.setBlock(x+7, y+15, z+7, crystalstone, 0);
		array.setBlock(x+7, y+15, z+8, crystalstone, 12);
		array.setBlock(x+7, y+16, z+4, crystalstone, 2);
		array.setBlock(x+7, y+16, z+5, crystalstone, 0);
		array.setBlock(x+7, y+16, z+6, crystalstone, 0);
		array.setBlock(x+7, y+16, z+7, crystalstone, 0);
		array.setBlock(x+7, y+16, z+8, crystalstone, 2);
		array.setBlock(x+7, y+17, z+4, crystalstone, 2);
		array.setBlock(x+7, y+17, z+5, crystalstone, 0);
		array.setBlock(x+7, y+17, z+6, crystalstone, 0);
		array.setBlock(x+7, y+17, z+7, crystalstone, 0);
		array.setBlock(x+7, y+17, z+8, crystalstone, 2);
		array.setBlock(x+7, y+18, z+4, crystalstone, 6);
		array.setBlock(x+7, y+18, z+5, crystalstone, 0);
		array.setBlock(x+7, y+18, z+6, crystalstone, 0);
		array.setBlock(x+7, y+18, z+7, crystalstone, 0);
		array.setBlock(x+7, y+18, z+8, crystalstone, 6);
		array.setBlock(x+7, y+19, z+5, crystalstone, 2);
		array.setBlock(x+7, y+19, z+6, crystalstone, 0);
		array.setBlock(x+7, y+19, z+7, crystalstone, 2);
		array.setBlock(x+7, y+20, z+5, crystalstone, 2);
		array.setBlock(x+7, y+20, z+6, crystalstone, 0);
		array.setBlock(x+7, y+20, z+7, crystalstone, 2);
		array.setBlock(x+7, y+21, z+5, crystalstone, 2);
		array.setBlock(x+7, y+21, z+6, crystalstone, 0);
		array.setBlock(x+7, y+21, z+7, crystalstone, 2);
		array.setBlock(x+7, y+22, z+5, crystalstone, 2);
		array.setBlock(x+7, y+22, z+6, crystalstone, 12);
		array.setBlock(x+7, y+22, z+7, crystalstone, 2);
		array.setBlock(x+7, y+23, z+5, crystalstone, 2);
		array.setBlock(x+7, y+23, z+7, crystalstone, 2);
		array.setBlock(x+7, y+24, z+5, crystalstone, 15);
		array.setBlock(x+7, y+24, z+6, crystalstone, 15);
		array.setBlock(x+7, y+24, z+7, crystalstone, 15);
		array.setBlock(x+7, y+25, z+6, crystalstone, 0);
		array.setBlock(x+8, y+1, z+5, crystalstone, 0);
		array.setBlock(x+8, y+1, z+6, crystalstone, 0);
		array.setBlock(x+8, y+1, z+7, crystalstone, 0);
		array.setBlock(x+8, y+2, z+4, crystalstone, 0);
		array.setBlock(x+8, y+2, z+5, crystalstone, 0);
		array.setBlock(x+8, y+2, z+6, crystalstone, 0);
		array.setBlock(x+8, y+2, z+7, crystalstone, 0);
		array.setBlock(x+8, y+2, z+8, crystalstone, 0);
		array.setBlock(x+8, y+3, z+2, crystalstone, 0);
		array.setBlock(x+8, y+3, z+3, crystalstone, 0);
		array.setBlock(x+8, y+3, z+4, crystalstone, 0);
		array.setBlock(x+8, y+3, z+5, crystalstone, 0);
		array.setBlock(x+8, y+3, z+6, crystalstone, 0);
		array.setBlock(x+8, y+3, z+7, crystalstone, 0);
		array.setBlock(x+8, y+3, z+8, crystalstone, 0);
		array.setBlock(x+8, y+3, z+9, crystalstone, 0);
		array.setBlock(x+8, y+3, z+10, crystalstone, 0);
		array.setBlock(x+8, y+4, z+3, crystalstone, 0);
		array.setBlock(x+8, y+4, z+4, crystalstone, 0);
		array.setBlock(x+8, y+4, z+5, crystalstone, 1);
		array.setBlock(x+8, y+4, z+6, crystalstone, 1);
		array.setBlock(x+8, y+4, z+7, crystalstone, 1);
		array.setBlock(x+8, y+4, z+8, crystalstone, 0);
		array.setBlock(x+8, y+4, z+9, crystalstone, 0);
		array.setBlock(x+8, y+5, z+3, crystalstone, 2);
		array.setBlock(x+8, y+5, z+4, crystalstone, 0);
		array.setBlock(x+8, y+5, z+8, crystalstone, 0);
		array.setBlock(x+8, y+5, z+9, crystalstone, 2);
		array.setBlock(x+8, y+6, z+3, crystalstone, 2);
		array.setBlock(x+8, y+6, z+4, crystalstone, 0);
		array.setBlock(x+8, y+6, z+8, crystalstone, 0);
		array.setBlock(x+8, y+6, z+9, crystalstone, 2);
		array.setBlock(x+8, y+7, z+3, crystalstone, 2);
		array.setBlock(x+8, y+7, z+4, crystalstone, 0);
		array.setBlock(x+8, y+7, z+5, crystalstone, 1);
		array.setBlock(x+8, y+7, z+6, crystalstone, 1);
		array.setBlock(x+8, y+7, z+7, crystalstone, 1);
		array.setBlock(x+8, y+7, z+8, crystalstone, 0);
		array.setBlock(x+8, y+7, z+9, crystalstone, 2);
		array.setBlock(x+8, y+8, z+3, crystalstone, 12);
		array.setBlock(x+8, y+8, z+4, crystalstone, 0);
		array.setBlock(x+8, y+8, z+5, crystalstone, 0);
		array.setBlock(x+8, y+8, z+6, crystalstone, 0);
		array.setBlock(x+8, y+8, z+7, crystalstone, 0);
		array.setBlock(x+8, y+8, z+8, crystalstone, 0);
		array.setBlock(x+8, y+8, z+9, crystalstone, 12);
		array.setBlock(x+8, y+9, z+3, crystalstone, 6);
		array.setBlock(x+8, y+9, z+4, crystalstone, 0);
		array.setBlock(x+8, y+9, z+5, crystalstone, 0);
		array.setBlock(x+8, y+9, z+6, crystalstone, 0);
		array.setBlock(x+8, y+9, z+7, crystalstone, 0);
		array.setBlock(x+8, y+9, z+8, crystalstone, 0);
		array.setBlock(x+8, y+9, z+9, crystalstone, 6);
		array.setBlock(x+8, y+10, z+4, crystalstone, 2);
		array.setBlock(x+8, y+10, z+5, crystalstone, 0);
		array.setBlock(x+8, y+10, z+6, crystalstone, 0);
		array.setBlock(x+8, y+10, z+7, crystalstone, 0);
		array.setBlock(x+8, y+10, z+8, crystalstone, 2);
		array.setBlock(x+8, y+11, z+4, crystalstone, 2);
		array.setBlock(x+8, y+11, z+5, crystalstone, 0);
		array.setBlock(x+8, y+11, z+6, crystalstone, 0);
		array.setBlock(x+8, y+11, z+7, crystalstone, 0);
		array.setBlock(x+8, y+11, z+8, crystalstone, 2);
		array.setBlock(x+8, y+12, z+4, crystalstone, 2);
		array.setBlock(x+8, y+12, z+5, crystalstone, 0);
		array.setBlock(x+8, y+12, z+6, crystalstone, 0);
		array.setBlock(x+8, y+12, z+7, crystalstone, 0);
		array.setBlock(x+8, y+12, z+8, crystalstone, 2);
		array.setBlock(x+8, y+13, z+4, crystalstone, 2);
		array.setBlock(x+8, y+13, z+5, crystalstone, 0);
		array.setBlock(x+8, y+13, z+6, crystalstone, 0);
		array.setBlock(x+8, y+13, z+7, crystalstone, 0);
		array.setBlock(x+8, y+13, z+8, crystalstone, 2);
		array.setBlock(x+8, y+14, z+4, crystalstone, 2);
		array.setBlock(x+8, y+14, z+5, crystalstone, 0);
		array.setBlock(x+8, y+14, z+6, crystalstone, 0);
		array.setBlock(x+8, y+14, z+7, crystalstone, 0);
		array.setBlock(x+8, y+14, z+8, crystalstone, 2);
		array.setBlock(x+8, y+15, z+4, crystalstone, 6);
		array.setBlock(x+8, y+15, z+5, crystalstone, 12);
		array.setBlock(x+8, y+15, z+6, crystalstone, 12);
		array.setBlock(x+8, y+15, z+7, crystalstone, 12);
		array.setBlock(x+8, y+15, z+8, crystalstone, 6);
		array.setBlock(x+8, y+16, z+5, crystalstone, 2);
		array.setBlock(x+8, y+16, z+6, crystalstone, 0);
		array.setBlock(x+8, y+16, z+7, crystalstone, 2);
		array.setBlock(x+8, y+17, z+5, crystalstone, 2);
		array.setBlock(x+8, y+17, z+6, crystalstone, 14);
		array.setBlock(x+8, y+17, z+7, crystalstone, 2);
		array.setBlock(x+8, y+18, z+5, crystalstone, 6);
		array.setBlock(x+8, y+18, z+6, crystalstone, 12);
		array.setBlock(x+8, y+18, z+7, crystalstone, 6);
		array.setBlock(x+8, y+19, z+6, crystalstone, 2);
		array.setBlock(x+8, y+20, z+6, crystalstone, 7);
		array.setBlock(x+9, y+2, z+5, crystalstone, 0);
		array.setBlock(x+9, y+2, z+6, crystalstone, 0);
		array.setBlock(x+9, y+2, z+7, crystalstone, 0);
		array.setBlock(x+9, y+3, z+3, crystalstone, 0);
		array.setBlock(x+9, y+3, z+4, crystalstone, 0);
		array.setBlock(x+9, y+3, z+5, crystalstone, 10);
		array.setBlock(x+9, y+3, z+6, crystalstone, 10);
		array.setBlock(x+9, y+3, z+7, crystalstone, 10);
		array.setBlock(x+9, y+3, z+8, crystalstone, 0);
		array.setBlock(x+9, y+3, z+9, crystalstone, 0);
		array.setBlock(x+9, y+4, z+4, crystalstone, 0);
		array.setBlock(x+9, y+4, z+8, crystalstone, 0);
		array.setBlock(x+9, y+5, z+4, crystalstone, 2);
		array.setBlock(x+9, y+5, z+8, crystalstone, 2);
		array.setBlock(x+9, y+6, z+4, crystalstone, 2);
		array.setBlock(x+9, y+6, z+8, crystalstone, 2);
		array.setBlock(x+9, y+7, z+4, crystalstone, 2);
		array.setBlock(x+9, y+7, z+8, crystalstone, 2);
		array.setBlock(x+9, y+8, z+4, crystalstone, 12);
		array.setBlock(x+9, y+8, z+5, crystalstone, 12);
		array.setBlock(x+9, y+8, z+6, crystalstone, 12);
		array.setBlock(x+9, y+8, z+7, crystalstone, 12);
		array.setBlock(x+9, y+8, z+8, crystalstone, 12);
		array.setBlock(x+9, y+9, z+4, crystalstone, 6);
		array.setBlock(x+9, y+9, z+5, crystalstone, 12);
		array.setBlock(x+9, y+9, z+6, crystalstone, 0);
		array.setBlock(x+9, y+9, z+7, crystalstone, 12);
		array.setBlock(x+9, y+9, z+8, crystalstone, 6);
		array.setBlock(x+9, y+10, z+5, crystalstone, 2);
		array.setBlock(x+9, y+10, z+6, crystalstone, 0);
		array.setBlock(x+9, y+10, z+7, crystalstone, 2);
		array.setBlock(x+9, y+11, z+5, crystalstone, 2);
		array.setBlock(x+9, y+11, z+6, crystalstone, 13);
		array.setBlock(x+9, y+11, z+7, crystalstone, 2);
		array.setBlock(x+9, y+12, z+5, crystalstone, 6);
		array.setBlock(x+9, y+12, z+6, crystalstone, 12);
		array.setBlock(x+9, y+12, z+7, crystalstone, 6);
		array.setBlock(x+9, y+13, z+6, crystalstone, 2);
		array.setBlock(x+9, y+14, z+6, crystalstone, 8);
		array.setBlock(x+10, y+3, z+4, crystalstone, 0);
		array.setBlock(x+10, y+3, z+5, crystalstone, 10);
		array.setBlock(x+10, y+3, z+6, crystalstone, 10);
		array.setBlock(x+10, y+3, z+7, crystalstone, 10);
		array.setBlock(x+10, y+3, z+8, crystalstone, 0);
		array.setBlock(x+11, y+3, z+5, crystalstone, 10);
		array.setBlock(x+11, y+3, z+6, crystalstone, 10);
		array.setBlock(x+11, y+3, z+7, crystalstone, 10);
		array.setBlock(x+12, y+3, z+5, crystalstone, 10);
		array.setBlock(x+12, y+3, z+6, crystalstone, 10);
		array.setBlock(x+12, y+3, z+7, crystalstone, 10);

		this.setTile(array, x+6, y+6, z+6, ChromaTiles.COMPOUND);
		this.setTile(array, x+x0, y+y0, z+z0, ChromaTiles.BROADCAST);

		array.setBlock(x+6, y+0, z+6, crystalstone, 0);

		array.setBlock(x+6, y+1, z+6, crystalstone, 12);
		array.setBlock(x+6, y+2, z+6, crystalstone, 2);
		array.addBlock(x+6, y+2, z+6, crystalstone, StoneTypes.GLOWCOL.ordinal());
		array.setBlock(x+6, y+3, z+6, crystalstone, 13);
		array.setBlock(x+6, y+4, z+6, crystalstone, 2);
		array.addBlock(x+6, y+4, z+6, crystalstone, StoneTypes.GLOWCOL.ordinal());
		array.setBlock(x+6, y+5, z+6, crystalstone, 12);

		array.setBlock(x+6, y+24, z+6, crystalstone, 0);
		array.setBlock(x+6, y+25, z+6, crystalstone, 0);

		this.setAir(array, x, 6, y, 20, z, 6);

		this.setAir(array, x, 3, y, 4, z, 5);
		this.setAir(array, x, 3, y, 4, z, 6);
		this.setAir(array, x, 3, y, 4, z, 7);
		this.setAir(array, x, 3, y, 5, z, 5);
		this.setAir(array, x, 3, y, 5, z, 6);
		this.setAir(array, x, 3, y, 5, z, 7);
		this.setAir(array, x, 3, y, 6, z, 5);
		this.setAir(array, x, 3, y, 6, z, 6);
		this.setAir(array, x, 3, y, 6, z, 7);
		this.setAir(array, x, 3, y, 7, z, 5);
		this.setAir(array, x, 3, y, 7, z, 6);
		this.setAir(array, x, 3, y, 7, z, 7);
		this.setAir(array, x, 4, y, 5, z, 5);
		this.setAir(array, x, 4, y, 5, z, 6);
		this.setAir(array, x, 4, y, 5, z, 7);
		this.setAir(array, x, 4, y, 6, z, 5);
		this.setAir(array, x, 4, y, 6, z, 6);
		this.setAir(array, x, 4, y, 6, z, 7);
		this.setAir(array, x, 5, y, 4, z, 3);
		this.setAir(array, x, 5, y, 4, z, 9);
		this.setAir(array, x, 5, y, 5, z, 3);
		this.setAir(array, x, 5, y, 5, z, 4);
		this.setAir(array, x, 5, y, 5, z, 8);
		this.setAir(array, x, 5, y, 5, z, 9);
		this.setAir(array, x, 5, y, 6, z, 3);
		this.setAir(array, x, 5, y, 6, z, 4);
		this.setAir(array, x, 5, y, 6, z, 6);
		this.setAir(array, x, 5, y, 6, z, 8);
		this.setAir(array, x, 5, y, 6, z, 9);
		this.setAir(array, x, 5, y, 7, z, 3);
		this.setAir(array, x, 5, y, 7, z, 9);
		this.setAir(array, x, 5, y, 23, z, 6);
		this.setAir(array, x, 6, y, 4, z, 3);
		this.setAir(array, x, 6, y, 4, z, 9);
		this.setAir(array, x, 6, y, 5, z, 3);
		this.setAir(array, x, 6, y, 5, z, 4);
		this.setAir(array, x, 6, y, 5, z, 8);
		this.setAir(array, x, 6, y, 5, z, 9);
		this.setAir(array, x, 6, y, 6, z, 3);
		this.setAir(array, x, 6, y, 6, z, 4);
		this.setAir(array, x, 6, y, 6, z, 5);
		this.setAir(array, x, 6, y, 6, z, 7);
		this.setAir(array, x, 6, y, 6, z, 8);
		this.setAir(array, x, 6, y, 6, z, 9);
		this.setAir(array, x, 6, y, 7, z, 3);
		this.setAir(array, x, 6, y, 7, z, 9);
		this.setAir(array, x, 6, y, 23, z, 5);
		this.setAir(array, x, 6, y, 23, z, 7);
		this.setAir(array, x, 7, y, 4, z, 3);
		this.setAir(array, x, 7, y, 4, z, 9);
		this.setAir(array, x, 7, y, 5, z, 3);
		this.setAir(array, x, 7, y, 5, z, 4);
		this.setAir(array, x, 7, y, 5, z, 8);
		this.setAir(array, x, 7, y, 5, z, 9);
		this.setAir(array, x, 7, y, 6, z, 3);
		this.setAir(array, x, 7, y, 6, z, 4);
		this.setAir(array, x, 7, y, 6, z, 6);
		this.setAir(array, x, 7, y, 6, z, 8);
		this.setAir(array, x, 7, y, 6, z, 9);
		this.setAir(array, x, 7, y, 7, z, 3);
		this.setAir(array, x, 7, y, 7, z, 9);
		this.setAir(array, x, 7, y, 23, z, 6);
		this.setAir(array, x, 8, y, 5, z, 5);
		this.setAir(array, x, 8, y, 5, z, 6);
		this.setAir(array, x, 8, y, 5, z, 7);
		this.setAir(array, x, 8, y, 6, z, 5);
		this.setAir(array, x, 8, y, 6, z, 6);
		this.setAir(array, x, 8, y, 6, z, 7);
		this.setAir(array, x, 9, y, 4, z, 5);
		this.setAir(array, x, 9, y, 4, z, 6);
		this.setAir(array, x, 9, y, 4, z, 7);
		this.setAir(array, x, 9, y, 5, z, 5);
		this.setAir(array, x, 9, y, 5, z, 6);
		this.setAir(array, x, 9, y, 5, z, 7);
		this.setAir(array, x, 9, y, 6, z, 5);
		this.setAir(array, x, 9, y, 6, z, 6);
		this.setAir(array, x, 9, y, 6, z, 7);
		this.setAir(array, x, 9, y, 7, z, 5);
		this.setAir(array, x, 9, y, 7, z, 6);
		this.setAir(array, x, 9, y, 7, z, 7);
		/*
		int rh = TileEntityCrystalBroadcaster.GLASS_RANGE_H;
		int rv = TileEntityCrystalBroadcaster.GLASS_RANGE_V;
		for (int i = -rh; i <= rh; i++) {
			for (int k = -rh; k <= rh; k++) {
				for (int j = -rv; j <= rv; j++) {
					int dx = x+x0+i;
					int dy = y+y0+j;
					int dz = z+z0+k;
					BlockKey bk = array.getBlockKeyAt(dx, dy, dz);
					if (bk != null && !bk.blockID.isAir(world, dx, dy, dz))
						continue;
					this.setAir(array, dx, 0, dy, 0, dz, 0);
					array.addBlock(dx, dy, dz, ChromaBlocks.DIMGEN.getBlockInstance(), DimDecoTypes.CLIFFGLASS.ordinal());
					potentialGlass++;
				}
			}
		}*/

		return array;
	}

	private void setAir(FilledBlockArray array, int x, int dx, int y, int dy, int z, int dz) {
		array.setBlock(x+dx, y+dy, z+dz, Blocks.air);
		int rh = TileEntityCrystalBroadcaster.GLASS_RANGE_H;
		int rv = TileEntityCrystalBroadcaster.GLASS_RANGE_V;
		if (dy >= y0-rv && dy <= y0+rv && dx >= x0-rh && dx <= x0+rh && dz >= z0-rh && dz <= z0+rh) {
			array.addBlock(x+dx, y+dy, z+dz, ChromaBlocks.DIMGEN.getBlockInstance(), DimDecoTypes.CLIFFGLASS.ordinal());
			//potentialGlass++;
		}
	}

	public int getGlassCount() {
		return potentialGlass;
	}

}
