/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2017
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 13/12/2016 5:44:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ChromatiCraft.Models;

import java.util.ArrayList;

import org.lwjgl.opengl.GL11;

import net.minecraft.tileentity.TileEntity;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;

public class ModelFocusCrystalMessy extends ModelFocusCrystalBase
{
	//fields
	LODModelPart Shape1r;
	LODModelPart Shape1s;
	LODModelPart Shape1t;
	LODModelPart Shape1u;
	LODModelPart Shape1v;
	LODModelPart Shape1x;
	LODModelPart Shape1a;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape1d;
	LODModelPart Shape1e;
	LODModelPart Shape1f;
	LODModelPart Shape1g;
	LODModelPart Shape1h;
	LODModelPart Shape1i;
	LODModelPart Shape1j;
	LODModelPart Shape1k;
	LODModelPart Shape1m;
	LODModelPart Shape1n;
	LODModelPart Shape1o;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2h;
	LODModelPart Shape2i;

	public ModelFocusCrystalMessy()
	{
		textureWidth = 64;
		textureHeight = 32;

		Shape1r = new LODModelPart(this, 0, 10);
		Shape1r.addBox(-4F, 3F, -4F, 2, 2, 2);
		Shape1r.setRotationPoint(0F, 23F, 0F);
		Shape1r.setTextureSize(64, 32);
		Shape1r.mirror = true;
		this.setRotation(Shape1r, -0.4363323F, 0.515163F, 0.4363323F);
		Shape1s = new LODModelPart(this, 0, 0);
		Shape1s.addBox(-4F, 3F, -4F, 2, 2, 2);
		Shape1s.setRotationPoint(0F, 23F, 0F);
		Shape1s.setTextureSize(64, 32);
		Shape1s.mirror = true;
		this.setRotation(Shape1s, -0.4363323F, 1.304052F, 0.4363323F);
		Shape1t = new LODModelPart(this, 0, 5);
		Shape1t.addBox(-4F, 3F, -4F, 2, 2, 2);
		Shape1t.setRotationPoint(0F, 23F, 0F);
		Shape1t.setTextureSize(64, 32);
		Shape1t.mirror = true;
		this.setRotation(Shape1t, -0.4363323F, 1.791581F, 0.4363323F);
		Shape1u = new LODModelPart(this, 0, 0);
		Shape1u.addBox(-4F, 3F, -4F, 2, 2, 2);
		Shape1u.setRotationPoint(0F, 23F, 0F);
		Shape1u.setTextureSize(64, 32);
		Shape1u.mirror = true;
		this.setRotation(Shape1u, -0.4363323F, 2.094395F, 0.4363323F);
		Shape1v = new LODModelPart(this, 9, 11);
		Shape1v.addBox(-4F, 2.5F, -4F, 2, 2, 2);
		Shape1v.setRotationPoint(0F, 23F, 0F);
		Shape1v.setTextureSize(64, 32);
		Shape1v.mirror = true;
		this.setRotation(Shape1v, -0.3246312F, 2.770128F, 0.4363323F);
		Shape1x = new LODModelPart(this, 18, 11);
		Shape1x.addBox(-4F, 3F, -4F, 2, 2, 2);
		Shape1x.setRotationPoint(0F, 23F, 0F);
		Shape1x.setTextureSize(64, 32);
		Shape1x.mirror = true;
		this.setRotation(Shape1x, -0.4363323F, -2.866122F, 0.4363323F);
		Shape1a = new LODModelPart(this, 9, 0);
		Shape1a.addBox(-4F, 3F, -4F, 2, 2, 2);
		Shape1a.setRotationPoint(0F, 23F, 0F);
		Shape1a.setTextureSize(64, 32);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, -0.4049164F, -0.5902122F, 0.3839724F);
		Shape1b = new LODModelPart(this, 18, 0);
		Shape1b.addBox(-4F, 3F, -4F, 2, 2, 2);
		Shape1b.setRotationPoint(0F, 23F, 0F);
		Shape1b.setTextureSize(64, 32);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, -0.4363323F, -0.9381145F, 0.4363323F);
		Shape1c = new LODModelPart(this, 27, 0);
		Shape1c.addBox(-4F, 2F, -4F, 2, 2, 2);
		Shape1c.setRotationPoint(0F, 23F, 0F);
		Shape1c.setTextureSize(64, 32);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, -0.3188135F, -1.451241F, 0.3700098F);
		Shape1d = new LODModelPart(this, 27, 5);
		Shape1d.addBox(-3F, 4F, -3F, 2, 2, 2);
		Shape1d.setRotationPoint(0F, 23F, 0F);
		Shape1d.setTextureSize(64, 32);
		Shape1d.mirror = true;
		this.setRotation(Shape1d, -0.3467387F, -2.048144F, 0.9564404F);
		Shape1e = new LODModelPart(this, 0, 15);
		Shape1e.addBox(-4F, 3F, -4F, 2, 2, 2);
		Shape1e.setRotationPoint(0F, 23F, 0F);
		Shape1e.setTextureSize(64, 32);
		Shape1e.mirror = true;
		this.setRotation(Shape1e, -0.4363323F, 0.1777327F, 0.4363323F);
		Shape1f = new LODModelPart(this, 14, 16);
		Shape1f.addBox(-3.5F, 2.5F, -4.5F, 1, 1, 1);
		Shape1f.setRotationPoint(0F, 23F, 0F);
		Shape1f.setTextureSize(64, 32);
		Shape1f.mirror = true;
		this.setRotation(Shape1f, -0.4363323F, -1.844522F, 0.4363323F);
		Shape1g = new LODModelPart(this, 10, 8);
		Shape1g.addBox(-1.8F, 1.8F, -1.8F, 1, 1, 1);
		Shape1g.setRotationPoint(0F, 23F, 0F);
		Shape1g.setTextureSize(64, 32);
		Shape1g.mirror = true;
		this.setRotation(Shape1g, -0.4363323F, 1.53589F, 0.4363323F);
		Shape1h = new LODModelPart(this, 10, 5);
		Shape1h.addBox(-1.8F, 1.8F, -1.8F, 1, 1, 1);
		Shape1h.setRotationPoint(0F, 23F, 0F);
		Shape1h.setTextureSize(64, 32);
		Shape1h.mirror = true;
		this.setRotation(Shape1h, -0.4363323F, 2.792527F, 0.4363323F);
		Shape1i = new LODModelPart(this, 15, 8);
		Shape1i.addBox(-1.8F, 1.8F, -1.8F, 1, 1, 1);
		Shape1i.setRotationPoint(0F, 23F, 0F);
		Shape1i.setTextureSize(64, 32);
		Shape1i.mirror = true;
		this.setRotation(Shape1i, -0.4363323F, -2.77071F, 0.4363323F);
		Shape1j = new LODModelPart(this, 15, 5);
		Shape1j.addBox(-1.8F, 1.8F, -1.8F, 1, 1, 1);
		Shape1j.setRotationPoint(0F, 23F, 0F);
		Shape1j.setTextureSize(64, 32);
		Shape1j.mirror = true;
		this.setRotation(Shape1j, -0.4363323F, -1.570796F, 0.4363323F);
		Shape1k = new LODModelPart(this, 20, 5);
		Shape1k.addBox(-1.8F, 1.8F, -1.8F, 1, 1, 1);
		Shape1k.setRotationPoint(0F, 23F, 0F);
		Shape1k.setTextureSize(64, 32);
		Shape1k.mirror = true;
		this.setRotation(Shape1k, -0.4363323F, 0.1745329F, 0.4363323F);
		Shape1m = new LODModelPart(this, 9, 16);
		Shape1m.addBox(-4.5F, 2.5F, -4.5F, 1, 1, 1);
		Shape1m.setRotationPoint(0F, 23F, 0F);
		Shape1m.setTextureSize(64, 32);
		Shape1m.mirror = true;
		this.setRotation(Shape1m, -0.4363323F, 2.094395F, 0.4363323F);
		Shape1n = new LODModelPart(this, 0, 20);
		Shape1n.addBox(-4.5F, 2.5F, -4.5F, 1, 1, 1);
		Shape1n.setRotationPoint(0F, 23F, 0F);
		Shape1n.setTextureSize(64, 32);
		Shape1n.mirror = true;
		this.setRotation(Shape1n, -0.4363323F, 0.1090831F, 0.1419534F);
		Shape1o = new LODModelPart(this, 19, 16);
		Shape1o.addBox(-4.5F, 4.5F, -4.5F, 1, 1, 1);
		Shape1o.setRotationPoint(0F, 23F, 0F);
		Shape1o.setTextureSize(64, 32);
		Shape1o.mirror = true;
		this.setRotation(Shape1o, -0.4363323F, 1.156281F, 0.4363323F);
		Shape2 = new LODModelPart(this, 8, 24);
		Shape2.addBox(-6F, 0F, -6F, 1, 3, 1);
		Shape2.setRotationPoint(0F, 21F, 0F);
		Shape2.setTextureSize(64, 32);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, -0.2181662F, 0F);
		Shape2a = new LODModelPart(this, 8, 24);
		Shape2a.addBox(-6F, 0F, -6F, 1, 3, 1);
		Shape2a.setRotationPoint(0F, 21F, 0F);
		Shape2a.setTextureSize(64, 32);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, -1.788962F, 0F);
		Shape2b = new LODModelPart(this, 8, 24);
		Shape2b.addBox(-6F, 0F, -6F, 1, 3, 1);
		Shape2b.setRotationPoint(0F, 21F, 0F);
		Shape2b.setTextureSize(64, 32);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0.2181662F, 0F);
		Shape2c = new LODModelPart(this, 0, 24);
		Shape2c.addBox(-10F, 0F, -0.5F, 1, 4, 1);
		Shape2c.setRotationPoint(0F, 20F, 0F);
		Shape2c.setTextureSize(64, 32);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 2.356194F, 0F);
		Shape2h = new LODModelPart(this, 8, 24);
		Shape2h.addBox(-6F, 0F, -6F, 1, 3, 1);
		Shape2h.setRotationPoint(0F, 21F, 0F);
		Shape2h.setTextureSize(64, 32);
		Shape2h.mirror = true;
		this.setRotation(Shape2h, 0F, 1.35263F, 0F);
		Shape2i = new LODModelPart(this, 0, 24);
		Shape2i.addBox(-10F, 0F, -0.5F, 1, 4, 1);
		Shape2i.setRotationPoint(0F, 20F, 0F);
		Shape2i.setTextureSize(64, 32);
		Shape2i.mirror = true;
		this.setRotation(Shape2i, 0F, 0.7853982F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li)
	{
		GL11.glPushMatrix();
		this.prepareOuterRing();
		this.renderPart(Shape1r, te, li);
		this.renderPart(Shape1s, te, li);
		this.renderPart(Shape1t, te, li);
		this.renderPart(Shape1u, te, li);
		this.renderPart(Shape1v, te, li);
		this.renderPart(Shape1x, te, li);
		this.renderPart(Shape1a, te, li);
		this.renderPart(Shape1b, te, li);
		this.renderPart(Shape1c, te, li);
		this.renderPart(Shape1d, te, li);
		this.renderPart(Shape1e, te, li);
		this.renderPart(Shape1f, te, li);
		this.renderPart(Shape1m, te, li);
		this.renderPart(Shape1n, te, li);
		this.renderPart(Shape1o, te, li);
		GL11.glPopMatrix();

		GL11.glPushMatrix();
		this.prepareInnerRing();
		this.renderPart(Shape1g, te, li);
		this.renderPart(Shape1h, te, li);
		this.renderPart(Shape1i, te, li);
		this.renderPart(Shape1j, te, li);
		this.renderPart(Shape1k, te, li);
		GL11.glPopMatrix();

		this.renderPart(Shape2, te, li);
		this.renderPart(Shape2a, te, li);
		this.renderPart(Shape2b, te, li);
		this.renderPart(Shape2c, te, li);
		this.renderPart(Shape2h, te, li);
		this.renderPart(Shape2i, te, li);
	}

}
