// Date: 06/05/2020 2:21:19 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ChromatiCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

import Reika.ChromatiCraft.Base.ChromaModelBase;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;

public class ModelBeeStorage extends ChromaModelBase
{
	//fields
	LODModelPart Shape2b;
	LODModelPart Shape2;
	LODModelPart Shape1;
	LODModelPart Shape1b;
	LODModelPart Shape2c;
	LODModelPart Shape2e;
	LODModelPart Shape2d;
	LODModelPart Shape1c;
	LODModelPart Shape1d;
	LODModelPart Shape1e;

	public ModelBeeStorage()
	{
		textureWidth = 128;
		textureHeight = 64;

		Shape2b = new LODModelPart(this, 57, 0);
		Shape2b.addBox(0F, 0F, 0F, 14, 1, 14);
		Shape2b.setRotationPoint(-7F, 9F, -7F);
		Shape2b.setTextureSize(128, 64);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 0, 0);
		Shape2.addBox(0F, 0F, 0F, 14, 2, 14);
		Shape2.setRotationPoint(-7F, 20F, -7F);
		Shape2.setTextureSize(128, 64);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape1 = new LODModelPart(this, 57, 17);
		Shape1.addBox(0F, 0F, 0F, 13, 14, 13);
		Shape1.setRotationPoint(-6.5F, 10F, -6.5F);
		Shape1.setTextureSize(128, 64);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape1b = new LODModelPart(this, 0, 28);
		Shape1b.addBox(0F, 0F, 0F, 3, 16, 3);
		Shape1b.setRotationPoint(-7.5F, 8.5F, 4.5F);
		Shape1b.setTextureSize(128, 64);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0F, 0F, 0F);
		Shape2c = new LODModelPart(this, 0, 48);
		Shape2c.addBox(0F, 0F, 0F, 10, 2, 10);
		Shape2c.setRotationPoint(-5F, 8F, -5F);
		Shape2c.setTextureSize(128, 64);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0F, 0F);
		Shape2e = new LODModelPart(this, 0, 0);
		Shape2e.addBox(0F, 0F, 0F, 14, 2, 14);
		Shape2e.setRotationPoint(-7F, 12F, -7F);
		Shape2e.setTextureSize(128, 64);
		Shape2e.mirror = true;
		this.setRotation(Shape2e, 0F, 0F, 0F);
		Shape2d = new LODModelPart(this, 0, 0);
		Shape2d.addBox(0F, 0F, 0F, 14, 2, 14);
		Shape2d.setRotationPoint(-7F, 16F, -7F);
		Shape2d.setTextureSize(128, 64);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 0F, 0F);
		Shape1c = new LODModelPart(this, 13, 28);
		Shape1c.addBox(0F, 0F, 0F, 3, 16, 3);
		Shape1c.setRotationPoint(-7.5F, 8.5F, -7.5F);
		Shape1c.setTextureSize(128, 64);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, 0F, 0F, 0F);
		Shape1d = new LODModelPart(this, 26, 28);
		Shape1d.addBox(0F, 0F, 0F, 3, 16, 3);
		Shape1d.setRotationPoint(4.5F, 8.5F, -7.5F);
		Shape1d.setTextureSize(128, 64);
		Shape1d.mirror = true;
		this.setRotation(Shape1d, 0F, 0F, 0F);
		Shape1e = new LODModelPart(this, 39, 28);
		Shape1e.addBox(0F, 0F, 0F, 3, 16, 3);
		Shape1e.setRotationPoint(4.5F, 8.5F, 4.5F);
		Shape1e.setTextureSize(128, 64);
		Shape1e.mirror = true;
		this.setRotation(Shape1e, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li) {
		Shape2b.render(te, f5);
		Shape2.render(te, f5);
		Shape1.render(te, f5);
		Shape1b.render(te, f5);
		Shape2c.render(te, f5);
		Shape2e.render(te, f5);
		Shape2d.render(te, f5);
		Shape1c.render(te, f5);
		Shape1d.render(te, f5);
		Shape1e.render(te, f5);
	}

	private void setRotation(LODModelPart model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
