/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2017
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 05/03/2017 7:18:32 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ChromatiCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;
import Reika.ChromatiCraft.Base.ChromaModelBase;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;

public class ModelProgressionLinker extends ChromaModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape1a;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape1d;
	LODModelPart Shape1e;
	LODModelPart Shape1f;
	LODModelPart Shape1g;
	LODModelPart Shape1h;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape2c;
	LODModelPart Shape2b;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape3d;
	LODModelPart Shape3e;

	public ModelProgressionLinker()
	{
		textureWidth = 32;
		textureHeight = 32;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(-1.5F, 0F, -5F, 3, 6, 1);
		Shape1.setRotationPoint(0F, 18F, 0F);
		Shape1.setTextureSize(32, 32);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, -2.094395F, 0F);
		Shape1a = new LODModelPart(this, 12, 0);
		Shape1a.addBox(-1F, 0F, -7F, 2, 4, 1);
		Shape1a.setRotationPoint(0F, 20F, 0F);
		Shape1a.setTextureSize(32, 32);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, 0F, -2.094395F, 0F);
		Shape1b = new LODModelPart(this, 0, 0);
		Shape1b.addBox(-1.5F, 0F, -5F, 3, 6, 1);
		Shape1b.setRotationPoint(0F, 18F, 0F);
		Shape1b.setTextureSize(32, 32);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0F, 1.047198F, 0F);
		Shape1c = new LODModelPart(this, 0, 0);
		Shape1c.addBox(-1.5F, 0F, -5F, 3, 6, 1);
		Shape1c.setRotationPoint(0F, 18F, 0F);
		Shape1c.setTextureSize(32, 32);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, 0F, 2.094395F, 0F);
		Shape1d = new LODModelPart(this, 0, 0);
		Shape1d.addBox(-1.5F, 0F, -5F, 3, 6, 1);
		Shape1d.setRotationPoint(0F, 18F, 0F);
		Shape1d.setTextureSize(32, 32);
		Shape1d.mirror = true;
		this.setRotation(Shape1d, 0F, 3.141593F, 0F);
		Shape1e = new LODModelPart(this, 0, 0);
		Shape1e.addBox(-1.5F, 0F, -5F, 3, 6, 1);
		Shape1e.setRotationPoint(0F, 18F, 0F);
		Shape1e.setTextureSize(32, 32);
		Shape1e.mirror = true;
		this.setRotation(Shape1e, 0F, -1.047198F, 0F);
		Shape1f = new LODModelPart(this, 0, 0);
		Shape1f.addBox(-1.5F, 0F, -5F, 3, 6, 1);
		Shape1f.setRotationPoint(0F, 18F, 0F);
		Shape1f.setTextureSize(32, 32);
		Shape1f.mirror = true;
		this.setRotation(Shape1f, 0F, 0F, 0F);
		Shape1g = new LODModelPart(this, 12, 0);
		Shape1g.addBox(-1F, 0F, -7F, 2, 4, 1);
		Shape1g.setRotationPoint(0F, 20F, 0F);
		Shape1g.setTextureSize(32, 32);
		Shape1g.mirror = true;
		this.setRotation(Shape1g, 0F, 0F, 0F);
		Shape1h = new LODModelPart(this, 12, 0);
		Shape1h.addBox(-1F, 0F, -7F, 2, 4, 1);
		Shape1h.setRotationPoint(0F, 20F, 0F);
		Shape1h.setTextureSize(32, 32);
		Shape1h.mirror = true;
		this.setRotation(Shape1h, 0F, 2.094395F, 0F);
		Shape2a = new LODModelPart(this, 0, 9);
		Shape2a.addBox(-4F, 0F, -7F, 8, 1, 1);
		Shape2a.setRotationPoint(0F, 23F, 0F);
		Shape2a.setTextureSize(32, 32);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 3.141593F, 0F);
		Shape3 = new LODModelPart(this, 0, 12);
		Shape3.addBox(-1.5F, 0F, -2.6F, 3, 1, 1);
		Shape3.setRotationPoint(0F, 23F, 0F);
		Shape3.setTextureSize(32, 32);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, -2.094395F, 0F);
		Shape2c = new LODModelPart(this, 0, 9);
		Shape2c.addBox(-4F, 0F, -7F, 8, 1, 1);
		Shape2c.setRotationPoint(0F, 23F, 0F);
		Shape2c.setTextureSize(32, 32);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, -1.047198F, 0F);
		Shape2b = new LODModelPart(this, 0, 9);
		Shape2b.addBox(-4F, 0F, -7F, 8, 1, 1);
		Shape2b.setRotationPoint(0F, 23F, 0F);
		Shape2b.setTextureSize(32, 32);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 1.047198F, 0F);
		Shape3a = new LODModelPart(this, 0, 12);
		Shape3a.addBox(-1.5F, 0F, -2.6F, 3, 1, 1);
		Shape3a.setRotationPoint(0F, 23F, 0F);
		Shape3a.setTextureSize(32, 32);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 3.141593F, 0F);
		Shape3b = new LODModelPart(this, 0, 12);
		Shape3b.addBox(-1.5F, 0F, -2.6F, 3, 1, 1);
		Shape3b.setRotationPoint(0F, 23F, 0F);
		Shape3b.setTextureSize(32, 32);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 2.094395F, 0F);
		Shape3c = new LODModelPart(this, 0, 12);
		Shape3c.addBox(-1.5F, 0F, -2.6F, 3, 1, 1);
		Shape3c.setRotationPoint(0F, 23F, 0F);
		Shape3c.setTextureSize(32, 32);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0F, 0F);
		Shape3d = new LODModelPart(this, 0, 12);
		Shape3d.addBox(-1.5F, 0F, -2.6F, 3, 1, 1);
		Shape3d.setRotationPoint(0F, 23F, 0F);
		Shape3d.setTextureSize(32, 32);
		Shape3d.mirror = true;
		this.setRotation(Shape3d, 0F, 1.047198F, 0F);
		Shape3e = new LODModelPart(this, 0, 12);
		Shape3e.addBox(-1.5F, 0F, -2.6F, 3, 1, 1);
		Shape3e.setRotationPoint(0F, 23F, 0F);
		Shape3e.setTextureSize(32, 32);
		Shape3e.mirror = true;
		this.setRotation(Shape3e, 0F, -1.047198F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li) {
		Shape1.render(te, f5);
		Shape1a.render(te, f5);
		Shape1b.render(te, f5);
		Shape1c.render(te, f5);
		Shape1d.render(te, f5);
		Shape1e.render(te, f5);
		Shape1f.render(te, f5);
		Shape1g.render(te, f5);
		Shape1h.render(te, f5);
		Shape2a.render(te, f5);
		Shape3.render(te, f5);
		Shape2c.render(te, f5);
		Shape2b.render(te, f5);
		Shape3a.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c.render(te, f5);
		Shape3d.render(te, f5);
		Shape3e.render(te, f5);
	}

}
