/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2015
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 06/11/2014 7:29:32 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ChromatiCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;
import Reika.ChromatiCraft.Base.ChromaModelBase;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;

public class ModelFiberEmitter extends ChromaModelBase
{
	//fields
	LODModelPart Shape1b;
	LODModelPart Shape3;
	LODModelPart Shape4a;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape21;
	LODModelPart Shape6a1;
	LODModelPart Shape2a1;
	LODModelPart Shape614;
	LODModelPart Shape1b4;
	LODModelPart Shape1b1;
	LODModelPart Shape1b2;
	LODModelPart Shape1b3;
	LODModelPart Shape1;
	LODModelPart Shape4a1;

	public ModelFiberEmitter()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1b = new LODModelPart(this, 35, 12);
		Shape1b.addBox(-3F, 2F, 0F, 6, 1, 1);
		Shape1b.setRotationPoint(0F, 16F, -1F);
		Shape1b.setTextureSize(128, 128);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 67, 22);
		Shape3.addBox(0F, 0F, 0F, 16, 16, 2);
		Shape3.setRotationPoint(-8F, 8F, 4F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape4a = new LODModelPart(this, 0, 90);
		Shape4a.addBox(0F, 0F, 0F, 14, 14, 1);
		Shape4a.setRotationPoint(-7F, 9F, 7F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 24, 65);
		Shape2.addBox(-6F, -4F, 3F, 1, 8, 1);
		Shape2.setRotationPoint(0F, 16F, -6F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape2a = new LODModelPart(this, 24, 46);
		Shape2a.addBox(5F, -4F, 3F, 1, 8, 1);
		Shape2a.setRotationPoint(0F, 16F, -6F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 37, 36);
		Shape6.addBox(-4F, 4F, 3F, 8, 1, 1);
		Shape6.setRotationPoint(0F, 17F, -6F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape6a = new LODModelPart(this, 37, 26);
		Shape6a.addBox(-4F, -6F, 3F, 8, 1, 1);
		Shape6a.setRotationPoint(0F, 16F, -6F);
		Shape6a.setTextureSize(128, 128);
		Shape6a.mirror = true;
		this.setRotation(Shape6a, 0F, 0F, 0F);
		Shape21 = new LODModelPart(this, 0, 65);
		Shape21.addBox(-7F, -4F, 0F, 1, 8, 7);
		Shape21.setRotationPoint(0F, 16F, -3F);
		Shape21.setTextureSize(128, 128);
		Shape21.mirror = true;
		this.setRotation(Shape21, 0F, 0F, 0F);
		Shape6a1 = new LODModelPart(this, 0, 21);
		Shape6a1.addBox(-4F, -7F, 0F, 8, 1, 7);
		Shape6a1.setRotationPoint(0F, 16F, -3F);
		Shape6a1.setTextureSize(128, 128);
		Shape6a1.mirror = true;
		this.setRotation(Shape6a1, 0F, 0F, 0F);
		Shape2a1 = new LODModelPart(this, 0, 46);
		Shape2a1.addBox(6F, -4F, 0F, 1, 8, 7);
		Shape2a1.setRotationPoint(0F, 16F, -3F);
		Shape2a1.setTextureSize(128, 128);
		Shape2a1.mirror = true;
		this.setRotation(Shape2a1, 0F, 0F, 0F);
		Shape614 = new LODModelPart(this, 0, 33);
		Shape614.addBox(-4F, 6F, 0F, 8, 1, 7);
		Shape614.setRotationPoint(0F, 16F, -3F);
		Shape614.setTextureSize(128, 128);
		Shape614.mirror = true;
		this.setRotation(Shape614, 0F, 0F, 0F);
		Shape1b4 = new LODModelPart(this, 38, 16);
		Shape1b4.addBox(-3F, -3F, 0F, 6, 6, 2);
		Shape1b4.setRotationPoint(0F, 16F, 0F);
		Shape1b4.setTextureSize(128, 128);
		Shape1b4.mirror = true;
		this.setRotation(Shape1b4, 0F, 0F, 0F);
		Shape1b1 = new LODModelPart(this, 52, 8);
		Shape1b1.addBox(2F, -2F, 0F, 1, 4, 1);
		Shape1b1.setRotationPoint(0F, 16F, -1F);
		Shape1b1.setTextureSize(128, 128);
		Shape1b1.mirror = true;
		this.setRotation(Shape1b1, 0F, 0F, 0F);
		Shape1b2 = new LODModelPart(this, 35, 8);
		Shape1b2.addBox(-3F, -3F, 0F, 6, 1, 1);
		Shape1b2.setRotationPoint(0F, 16F, -1F);
		Shape1b2.setTextureSize(128, 128);
		Shape1b2.mirror = true;
		this.setRotation(Shape1b2, 0F, 0F, 0F);
		Shape1b3 = new LODModelPart(this, 52, 1);
		Shape1b3.addBox(-3F, -2F, 0F, 1, 4, 1);
		Shape1b3.setRotationPoint(0F, 16F, -1F);
		Shape1b3.setTextureSize(128, 128);
		Shape1b3.mirror = true;
		this.setRotation(Shape1b3, 0F, 0F, 0F);
		Shape1 = new LODModelPart(this, 0, 111);
		Shape1.addBox(0F, 0F, 0F, 12, 12, 2);
		Shape1.setRotationPoint(-6F, 10F, 2F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape4a1 = new LODModelPart(this, 0, 0);
		Shape4a1.addBox(0F, 0F, 0F, 15, 15, 1);
		Shape4a1.setRotationPoint(-7.5F, 8.5F, 6F);
		Shape4a1.setTextureSize(128, 128);
		Shape4a1.mirror = true;
		this.setRotation(Shape4a1, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li)
	{
		Shape1b.render(te, f5);
		Shape3.render(te, f5);
		Shape4a.render(te, f5);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape6.render(te, f5);
		Shape6a.render(te, f5);
		Shape21.render(te, f5);
		Shape6a1.render(te, f5);
		Shape2a1.render(te, f5);
		Shape614.render(te, f5);
		Shape1b4.render(te, f5);
		Shape1b1.render(te, f5);
		Shape1b2.render(te, f5);
		Shape1b3.render(te, f5);
		Shape1.render(te, f5);
		Shape4a1.render(te, f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
