/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2017
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 05/09/2014 7:08:55 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package Reika.ChromatiCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;
import Reika.ChromatiCraft.Base.ChromaModelBase;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;

public class ModelCrystalBeacon extends ChromaModelBase
{
	//fields
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape4d;
	LODModelPart Shape4e;
	LODModelPart Shape4f;
	LODModelPart Shape4g;
	LODModelPart Shape1;

	public ModelCrystalBeacon()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape2 = new LODModelPart(this, 65, 0);
		Shape2.addBox(0F, 0F, 0F, 14, 1, 14);
		Shape2.setRotationPoint(-7F, 23F, -7F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 0, 0);
		Shape3.addBox(0F, 0F, 0F, 16, 2, 16);
		Shape3.setRotationPoint(-8F, 21F, -8F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 32, 60);
		Shape4.addBox(0F, 0F, 0F, 2, 2, 10);
		Shape4.setRotationPoint(5F, 19F, -5F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape4a = new LODModelPart(this, 0, 55);
		Shape4a.addBox(0F, 0F, 0F, 12, 1, 1);
		Shape4a.setRotationPoint(-6F, 18F, 5F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape4b = new LODModelPart(this, 0, 48);
		Shape4b.addBox(0F, 0F, 0F, 14, 2, 2);
		Shape4b.setRotationPoint(-7F, 19F, 5F);
		Shape4b.setTextureSize(128, 128);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0F, 0F, 0F);
		Shape4c = new LODModelPart(this, 0, 60);
		Shape4c.addBox(0F, 0F, 0F, 2, 2, 10);
		Shape4c.setRotationPoint(-7F, 19F, -5F);
		Shape4c.setTextureSize(128, 128);
		Shape4c.mirror = true;
		this.setRotation(Shape4c, 0F, 0F, 0F);
		Shape4d = new LODModelPart(this, 0, 38);
		Shape4d.addBox(0F, 0F, 0F, 14, 2, 2);
		Shape4d.setRotationPoint(-7F, 19F, -7F);
		Shape4d.setTextureSize(128, 128);
		Shape4d.mirror = true;
		this.setRotation(Shape4d, 0F, 0F, 0F);
		Shape4e = new LODModelPart(this, 24, 73);
		Shape4e.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape4e.setRotationPoint(5F, 18F, -5F);
		Shape4e.setTextureSize(128, 128);
		Shape4e.mirror = true;
		this.setRotation(Shape4e, 0F, 0F, 0F);
		Shape4f = new LODModelPart(this, 34, 42);
		Shape4f.addBox(0F, 0F, 0F, 12, 1, 1);
		Shape4f.setRotationPoint(-6F, 18F, -6F);
		Shape4f.setTextureSize(128, 128);
		Shape4f.mirror = true;
		this.setRotation(Shape4f, 0F, 0F, 0F);
		Shape4g = new LODModelPart(this, 0, 73);
		Shape4g.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape4g.setRotationPoint(-6F, 18F, -5F);
		Shape4g.setTextureSize(128, 128);
		Shape4g.mirror = true;
		this.setRotation(Shape4g, 0F, 0F, 0F);
		Shape1 = new LODModelPart(this, 0, 19);
		Shape1.addBox(0F, 0F, 0F, 4, 13, 4);
		Shape1.setRotationPoint(-2F, 8F, -2F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li)
	{
		Shape2.render(f5);
		Shape3.render(f5);
		Shape4.render(f5);
		Shape4a.render(f5);
		Shape4b.render(f5);
		Shape4c.render(f5);
		Shape4d.render(f5);
		Shape4e.render(f5);
		Shape4f.render(f5);
		Shape4g.render(f5);
		Shape1.render(f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
