/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2017
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 19/05/2017 4:36:58 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ChromatiCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;
import Reika.ChromatiCraft.Base.ChromaModelBase;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;

public class ModelMultiBuilder extends ChromaModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape1d;
	LODModelPart Shape1e;
	LODModelPart Shape1f;
	LODModelPart Shape1g;
	LODModelPart Shape1h;
	LODModelPart Shape1i;
	LODModelPart Shape1j;
	LODModelPart Shape1k;
	LODModelPart Shape1l;
	LODModelPart Shape1m;
	LODModelPart Shape1n;
	LODModelPart Shape1o;
	LODModelPart Shape1p;
	LODModelPart Shape1q;
	LODModelPart Shape1r;
	LODModelPart Shape1s;
	LODModelPart Shape1t;
	LODModelPart Shape1u;
	LODModelPart Shape1v;
	LODModelPart Shape1w;
	LODModelPart Shape1x;
	LODModelPart Shape1y;
	LODModelPart Shape1z;
	LODModelPart Shape1aa;
	LODModelPart Shape1ab;
	LODModelPart Shape1ac;
	LODModelPart Shape1ad;
	LODModelPart Shape1ae;
	LODModelPart Shape1af;
	LODModelPart Shape1ag;

	public ModelMultiBuilder()
	{
		textureWidth = 64;
		textureHeight = 64;

		Shape1 = new LODModelPart(this, 0, 30);
		Shape1.addBox(0F, 0F, 0F, 2, 12, 2);
		Shape1.setRotationPoint(-8F, 12F, 6F);
		Shape1.setTextureSize(64, 64);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape1b = new LODModelPart(this, 19, 12);
		Shape1b.addBox(0F, 0F, 0F, 1, 8, 1);
		Shape1b.setRotationPoint(-2F, 16F, 7F);
		Shape1b.setTextureSize(64, 64);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0F, 0F, 0F);
		Shape1c = new LODModelPart(this, 0, 15);
		Shape1c.addBox(0F, 0F, 0F, 2, 12, 2);
		Shape1c.setRotationPoint(6F, 12F, -8F);
		Shape1c.setTextureSize(64, 64);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, 0F, 0F, 0F);
		Shape1d = new LODModelPart(this, 0, 0);
		Shape1d.addBox(0F, 0F, 0F, 2, 12, 2);
		Shape1d.setRotationPoint(6F, 12F, 6F);
		Shape1d.setTextureSize(64, 64);
		Shape1d.mirror = true;
		this.setRotation(Shape1d, 0F, 0F, 0F);
		Shape1e = new LODModelPart(this, 0, 45);
		Shape1e.addBox(0F, 0F, 0F, 2, 12, 2);
		Shape1e.setRotationPoint(-8F, 12F, -8F);
		Shape1e.setTextureSize(64, 64);
		Shape1e.mirror = true;
		this.setRotation(Shape1e, 0F, 0F, 0F);
		Shape1f = new LODModelPart(this, 19, 0);
		Shape1f.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape1f.setRotationPoint(-4F, 14F, 7F);
		Shape1f.setTextureSize(64, 64);
		Shape1f.mirror = true;
		this.setRotation(Shape1f, 0F, 0F, 0F);
		Shape1g = new LODModelPart(this, 19, 0);
		Shape1g.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape1g.setRotationPoint(3F, 14F, 7F);
		Shape1g.setTextureSize(64, 64);
		Shape1g.mirror = true;
		this.setRotation(Shape1g, 0F, 0F, 0F);
		Shape1h = new LODModelPart(this, 19, 12);
		Shape1h.addBox(0F, 0F, 0F, 1, 8, 1);
		Shape1h.setRotationPoint(1F, 16F, 7F);
		Shape1h.setTextureSize(64, 64);
		Shape1h.mirror = true;
		this.setRotation(Shape1h, 0F, 0F, 0F);
		Shape1i = new LODModelPart(this, 24, 0);
		Shape1i.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape1i.setRotationPoint(3F, 14F, -8F);
		Shape1i.setTextureSize(64, 64);
		Shape1i.mirror = true;
		this.setRotation(Shape1i, 0F, 0F, 0F);
		Shape1j = new LODModelPart(this, 43, 0);
		Shape1j.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape1j.setRotationPoint(-2F, 19F, 3F);
		Shape1j.setTextureSize(64, 64);
		Shape1j.mirror = true;
		this.setRotation(Shape1j, 0F, 0F, 0F);
		Shape1k = new LODModelPart(this, 9, 12);
		Shape1k.addBox(0F, 0F, 0F, 1, 8, 1);
		Shape1k.setRotationPoint(7F, 16F, 1F);
		Shape1k.setTextureSize(64, 64);
		Shape1k.mirror = true;
		this.setRotation(Shape1k, 0F, 0F, 0F);
		Shape1l = new LODModelPart(this, 9, 0);
		Shape1l.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape1l.setRotationPoint(7F, 14F, 3F);
		Shape1l.setTextureSize(64, 64);
		Shape1l.mirror = true;
		this.setRotation(Shape1l, 0F, 0F, 0F);
		Shape1m = new LODModelPart(this, 29, 0);
		Shape1m.addBox(0F, 0F, 0F, 2, 7, 2);
		Shape1m.setRotationPoint(3F, 17F, 3F);
		Shape1m.setTextureSize(64, 64);
		Shape1m.mirror = true;
		this.setRotation(Shape1m, 0F, 0F, 0F);
		Shape1n = new LODModelPart(this, 24, 12);
		Shape1n.addBox(0F, 0F, 0F, 1, 8, 1);
		Shape1n.setRotationPoint(-2F, 16F, -8F);
		Shape1n.setTextureSize(64, 64);
		Shape1n.mirror = true;
		this.setRotation(Shape1n, 0F, 0F, 0F);
		Shape1o = new LODModelPart(this, 9, 12);
		Shape1o.addBox(0F, 0F, 0F, 1, 8, 1);
		Shape1o.setRotationPoint(7F, 16F, -2F);
		Shape1o.setTextureSize(64, 64);
		Shape1o.mirror = true;
		this.setRotation(Shape1o, 0F, 0F, 0F);
		Shape1p = new LODModelPart(this, 9, 0);
		Shape1p.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape1p.setRotationPoint(7F, 14F, -4F);
		Shape1p.setTextureSize(64, 64);
		Shape1p.mirror = true;
		this.setRotation(Shape1p, 0F, 0F, 0F);
		Shape1q = new LODModelPart(this, 14, 0);
		Shape1q.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape1q.setRotationPoint(-8F, 14F, -4F);
		Shape1q.setTextureSize(64, 64);
		Shape1q.mirror = true;
		this.setRotation(Shape1q, 0F, 0F, 0F);
		Shape1r = new LODModelPart(this, 14, 12);
		Shape1r.addBox(0F, 0F, 0F, 1, 8, 1);
		Shape1r.setRotationPoint(-8F, 16F, -2F);
		Shape1r.setTextureSize(64, 64);
		Shape1r.mirror = true;
		this.setRotation(Shape1r, 0F, 0F, 0F);
		Shape1s = new LODModelPart(this, 14, 12);
		Shape1s.addBox(0F, 0F, 0F, 1, 8, 1);
		Shape1s.setRotationPoint(-8F, 16F, 1F);
		Shape1s.setTextureSize(64, 64);
		Shape1s.mirror = true;
		this.setRotation(Shape1s, 0F, 0F, 0F);
		Shape1t = new LODModelPart(this, 14, 0);
		Shape1t.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape1t.setRotationPoint(-8F, 14F, 3F);
		Shape1t.setTextureSize(64, 64);
		Shape1t.mirror = true;
		this.setRotation(Shape1t, 0F, 0F, 0F);
		Shape1u = new LODModelPart(this, 24, 0);
		Shape1u.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape1u.setRotationPoint(-4F, 14F, -8F);
		Shape1u.setTextureSize(64, 64);
		Shape1u.mirror = true;
		this.setRotation(Shape1u, 0F, 0F, 0F);
		Shape1v = new LODModelPart(this, 29, 10);
		Shape1v.addBox(0F, 0F, 0F, 2, 7, 2);
		Shape1v.setRotationPoint(3F, 17F, -5F);
		Shape1v.setTextureSize(64, 64);
		Shape1v.mirror = true;
		this.setRotation(Shape1v, 0F, 0F, 0F);
		Shape1w = new LODModelPart(this, 29, 20);
		Shape1w.addBox(0F, 0F, 0F, 2, 7, 2);
		Shape1w.setRotationPoint(-5F, 17F, 3F);
		Shape1w.setTextureSize(64, 64);
		Shape1w.mirror = true;
		this.setRotation(Shape1w, 0F, 0F, 0F);
		Shape1x = new LODModelPart(this, 9, 22);
		Shape1x.addBox(0F, 0F, 0F, 2, 4, 2);
		Shape1x.setRotationPoint(-1F, 20F, -1F);
		Shape1x.setTextureSize(64, 64);
		Shape1x.mirror = true;
		this.setRotation(Shape1x, 0F, 0F, 0F);
		Shape1y = new LODModelPart(this, 24, 12);
		Shape1y.addBox(0F, 0F, 0F, 1, 8, 1);
		Shape1y.setRotationPoint(1F, 16F, -8F);
		Shape1y.setTextureSize(64, 64);
		Shape1y.mirror = true;
		this.setRotation(Shape1y, 0F, 0F, 0F);
		Shape1z = new LODModelPart(this, 48, 0);
		Shape1z.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape1z.setRotationPoint(-4F, 19F, -2F);
		Shape1z.setTextureSize(64, 64);
		Shape1z.mirror = true;
		this.setRotation(Shape1z, 0F, 0F, 0F);
		Shape1aa = new LODModelPart(this, 53, 0);
		Shape1aa.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape1aa.setRotationPoint(1F, 19F, -4F);
		Shape1aa.setTextureSize(64, 64);
		Shape1aa.mirror = true;
		this.setRotation(Shape1aa, 0F, 0F, 0F);
		Shape1ab = new LODModelPart(this, 53, 0);
		Shape1ab.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape1ab.setRotationPoint(-2F, 19F, -4F);
		Shape1ab.setTextureSize(64, 64);
		Shape1ab.mirror = true;
		this.setRotation(Shape1ab, 0F, 0F, 0F);
		Shape1ac = new LODModelPart(this, 43, 0);
		Shape1ac.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape1ac.setRotationPoint(1F, 19F, 3F);
		Shape1ac.setTextureSize(64, 64);
		Shape1ac.mirror = true;
		this.setRotation(Shape1ac, 0F, 0F, 0F);
		Shape1ad = new LODModelPart(this, 48, 0);
		Shape1ad.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape1ad.setRotationPoint(-4F, 19F, 1F);
		Shape1ad.setTextureSize(64, 64);
		Shape1ad.mirror = true;
		this.setRotation(Shape1ad, 0F, 0F, 0F);
		Shape1ae = new LODModelPart(this, 38, 0);
		Shape1ae.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape1ae.setRotationPoint(3F, 19F, 1F);
		Shape1ae.setTextureSize(64, 64);
		Shape1ae.mirror = true;
		this.setRotation(Shape1ae, 0F, 0F, 0F);
		Shape1af = new LODModelPart(this, 38, 0);
		Shape1af.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape1af.setRotationPoint(3F, 19F, -2F);
		Shape1af.setTextureSize(64, 64);
		Shape1af.mirror = true;
		this.setRotation(Shape1af, 0F, 0F, 0F);
		Shape1ag = new LODModelPart(this, 29, 30);
		Shape1ag.addBox(0F, 0F, 0F, 2, 7, 2);
		Shape1ag.setRotationPoint(-5F, 17F, -5F);
		Shape1ag.setTextureSize(64, 64);
		Shape1ag.mirror = true;
		this.setRotation(Shape1ag, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li) {
		Shape1.render(te, f5);
		Shape1b.render(te, f5);
		Shape1c.render(te, f5);
		Shape1d.render(te, f5);
		Shape1e.render(te, f5);
		Shape1f.render(te, f5);
		Shape1g.render(te, f5);
		Shape1h.render(te, f5);
		Shape1i.render(te, f5);
		Shape1j.render(te, f5);
		Shape1k.render(te, f5);
		Shape1l.render(te, f5);
		Shape1m.render(te, f5);
		Shape1n.render(te, f5);
		Shape1o.render(te, f5);
		Shape1p.render(te, f5);
		Shape1q.render(te, f5);
		Shape1r.render(te, f5);
		Shape1s.render(te, f5);
		Shape1t.render(te, f5);
		Shape1u.render(te, f5);
		Shape1v.render(te, f5);
		Shape1w.render(te, f5);
		Shape1x.render(te, f5);
		Shape1y.render(te, f5);
		Shape1z.render(te, f5);
		Shape1aa.render(te, f5);
		Shape1ab.render(te, f5);
		Shape1ac.render(te, f5);
		Shape1ad.render(te, f5);
		Shape1ae.render(te, f5);
		Shape1af.render(te, f5);
		Shape1ag.render(te, f5);
	}

}
