/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2015
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 17/03/2015 1:13:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ChromatiCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;
import Reika.ChromatiCraft.Base.ChromaModelBase;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;

public class ModelFarmer extends ChromaModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape1b;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape3;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4;
	LODModelPart Shape4d;

	public ModelFarmer()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 3, 16);
		Shape1.setRotationPoint(-8F, 8F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 92, 0);
		Shape2.addBox(0F, 0F, 0F, 2, 10, 2);
		Shape2.setRotationPoint(6F, 11F, 6F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape1b = new LODModelPart(this, 0, 71);
		Shape1b.addBox(0F, 0F, 0F, 16, 3, 16);
		Shape1b.setRotationPoint(-8F, 21F, -8F);
		Shape1b.setTextureSize(128, 128);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0F, 0F, 0F);
		Shape2b = new LODModelPart(this, 74, 0);
		Shape2b.addBox(0F, 0F, 0F, 2, 10, 2);
		Shape2b.setRotationPoint(-8F, 11F, 6F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0F);
		Shape2c = new LODModelPart(this, 83, 0);
		Shape2c.addBox(0F, 0F, 0F, 2, 10, 2);
		Shape2c.setRotationPoint(6F, 11F, -8F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0F, 0F);
		Shape2d = new LODModelPart(this, 65, 0);
		Shape2d.addBox(0F, 0F, 0F, 2, 10, 2);
		Shape2d.setRotationPoint(-8F, 11F, -8F);
		Shape2d.setTextureSize(128, 128);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 0, 33);
		Shape3.addBox(-1F, 0F, 0F, 1, 10, 12);
		Shape3.setRotationPoint(8F, 11F, -6F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, -0.2617994F, 0F);
		Shape3b = new LODModelPart(this, 0, 20);
		Shape3b.addBox(0F, 0F, 0F, 12, 10, 1);
		Shape3b.setRotationPoint(-6F, 11F, -7F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0F, 0F);
		Shape3c = new LODModelPart(this, 0, 33);
		Shape3c.addBox(0F, 0F, 0F, 1, 10, 12);
		Shape3c.setRotationPoint(-8F, 11F, -6F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0.2617994F, 0F);
		Shape4 = new LODModelPart(this, 27, 54);
		Shape4.addBox(0F, 0F, 0F, 2, 10, 6);
		Shape4.setRotationPoint(-1F, 11F, 1F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape4d = new LODModelPart(this, 0, 56);
		Shape4d.addBox(0F, 0F, 0F, 12, 10, 1);
		Shape4d.setRotationPoint(-6F, 11F, 7F);
		Shape4d.setTextureSize(128, 128);
		Shape4d.mirror = true;
		this.setRotation(Shape4d, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li)  {
		Shape1.render(te, f5);
		Shape2.render(te, f5);
		Shape1b.render(te, f5);
		Shape2b.render(te, f5);
		Shape2c.render(te, f5);
		Shape2d.render(te, f5);
		Shape3.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c.render(te, f5);
		Shape4.render(te, f5);
		Shape4d.render(te, f5);
	}

	private void setRotation(LODModelPart model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
